<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>cn.ecosync.ibms</groupId>
        <artifactId>ibms-parent</artifactId>
        <version>0.0.1-SNAPSHOT</version>
        <relativePath>../../ibms-parent</relativePath>
    </parent>

    <groupId>cn.ecosync.aiot.data</groupId>
    <artifactId>aiot-data-api-server-parent</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <packaging>pom</packaging>

    <modules>
        <module>api</module>
        <module>core</module>
        <module>boot</module>
    </modules>

    <properties>
        <protobuf.version>4.30.0</protobuf.version>
        <snappy.version>1.1.10.7</snappy.version>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>cn.ecosync.aiot.data</groupId>
                <artifactId>aiot-data-api-server-api</artifactId>
                <version>0.0.1-SNAPSHOT</version>
            </dependency>
            <dependency>
                <groupId>cn.ecosync.aiot.data</groupId>
                <artifactId>aiot-data-api-server-core</artifactId>
                <version>0.0.1-SNAPSHOT</version>
            </dependency>
            <dependency>
                <groupId>cn.ecosync.aiot.data</groupId>
                <artifactId>aiot-data-api-server-boot</artifactId>
                <version>0.0.1-SNAPSHOT</version>
            </dependency>
            <dependency>
                <groupId>com.google.protobuf</groupId>
                <artifactId>protobuf-java</artifactId>
                <version>${protobuf.version}</version>
            </dependency>
            <dependency>
                <groupId>org.xerial.snappy</groupId>
                <artifactId>snappy-java</artifactId>
                <version>${snappy.version}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>
</project>
