volumes:
  prometheus:
    name: ibms-prometheus
  grafana:
    name: ibms-grafana

services:
  prometheus:
    image: prom/prometheus:v3.2.0
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus:/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --web.route-prefix=/
      - --web.external-url=http://${IBMS_EXTERNAL_HOST:?}/prometheus
      - --web.enable-remote-write-receiver
      - --web.remote-write-receiver.accepted-protobuf-messages=io.prometheus.write.v2.Request
      - --web.listen-address=0.0.0.0:9090
  grafana:
    image: grafana/grafana:11.4.0
    environment:
      GF_DEFAULT_INSTANCE_NAME: ${COMPOSE_PROJECT_NAME}
      GF_SERVER_ROOT_URL: http://${IBMS_EXTERNAL_HOST:?}/grafana
      GF_SERVER_SERVE_FROM_SUB_PATH: true
      GF_SECURITY_ADMIN_USER: ${GRAFANA_ADMIN_USER:?}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_ADMIN_PASSWORD:?}
    volumes:
      - grafana:/var/lib/grafana
  nginx:
    image: nginx:1.27-bookworm
    restart: always
    ports:
      - '80:80'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/templates:/etc/nginx/templates
      - ./tmp/nginx:/var/log/nginx
