### 新增定时任务（读取设备状态任务）
POST http://localhost/scheduling
Content-Type: application/json

{
  "commandType": "ADD_SCHEDULING",
  "schedulingName": "example",
  "schedulingTrigger": {
    "type": "cron",
    "expression": "0 0/1 * * * ?"
  },
  "schedulingTaskParams": {
    "type": "ReadDeviceStatus",
    "deviceCode": "B830"
  }
}

### 新增定时任务（读取所有设备状态任务）
POST http://localhost/scheduling
Content-Type: application/json

{
  "commandType": "ADD_SCHEDULING",
  "schedulingName": "example_batch",
  "schedulingTrigger": {
    "type": "cron",
    "expression": "0 0/1 * * * ?"
  },
  "schedulingTaskParams": {
    "type": "ReadDeviceStatusBatch"
  }
}

### 删除定时任务
POST http://localhost/scheduling
Content-Type: application/json

{
  "commandType": "REMOVE_SCHEDULING",
  "schedulingName": "example"
}

### 启动/停止定时任务
POST http://localhost/scheduling
Content-Type: application/json

{
  "commandType": "ENABLE_OR_DISABLE_SCHEDULING",
  "schedulingName": "example_batch",
  "enabled": false
}

### 重置定时任务状态
POST http://localhost/scheduling
Content-Type: application/json

{
  "commandType": "RESET_SCHEDULING",
  "schedulingName": "example"
}
