include:
  - mysql/docker-compose.yml

services:
  ibms:
    build: .
    image: ecosync/ibms:0.0.1
    container_name: ibms
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - BACNET_SERVICE_URL=http://host.docker.internal:47808
    volumes:
      - ./target:/opt/app/modules
    command: ["java", "-jar", "ibms-bootstrap-0.0.1-SNAPSHOT.jar"]

  bacnet:
    build: ./bacnet
    image: ecosync/bacnet:0.0.1
    container_name: bacnet
    restart: always
    network_mode: host
    command: ["java", "-Xms32m", "-Xmx32m", "-Xss256k", "-jar", 'ibms-bacnet-0.0.1-SNAPSHOT.jar']
