include:
  - ibms-mysql/docker-compose.yml
  - ibms-nginx/docker-compose.yml
  - ibms-prometheus/docker-compose.yml
  - ibms-grafana/docker-compose.yml
  - ibms-gateway-starter/docker-compose.yml

volumes:
  database:

#services:
#  cadvisor:
#    image: gcr.io/cadvisor/cadvisor:v0.49.2
#    privileged: true
#    ports:
#      - "9338:8080"
#    volumes:
#      - /:/rootfs:ro
#      - /var/run:/var/run:ro
#      - /sys:/sys:ro
#      - /var/lib/docker/:/var/lib/docker:ro
#      - /dev/disk/:/dev/disk:ro
#    devices:
#      - /dev/kmsg:/dev/kmsg
