include:
  - mysql/docker-compose.yml
  - nginx/docker-compose.yml
  - otel/docker-compose.yml

services:
  ibms:
    build: .
    image: ecosync/ibms:0.0.2
    container_name: ibms
    depends_on:
      database:
        condition: service_healthy
    volumes:
      - ./ibms-bootstrap/target/ibms-bootstrap-0.0.1-SNAPSHOT.jar:/opt/app/ibms-bootstrap-0.0.1-SNAPSHOT.jar
      - ./ibms-bootstrap/src/main/resources/application.yml:/opt/app/application.yml
    command: [ "java", "-jar", "ibms-bootstrap-0.0.1-SNAPSHOT.jar" ]
