services:
  database:
    image: mysql:8.0
    network_mode: host
    environment:
      MYSQL_ROOT_PASSWORD: CJVixCszaS+7raa/5326YJDq3xrSBXHg
    healthcheck:
      test: [ "CMD", "mysqladmin", "-uroot", "-p$$MYSQL_ROOT_PASSWORD", "ping", "-h", "localhost" ]
      timeout: 10s
      interval: 30s
      retries: 10
      start_period: 180s
    volumes:
      - ./initdb.d:/docker-entrypoint-initdb.d
      - database:/var/lib/mysql
#      - ./my.cnf:/etc/mysql/conf.d/my.cnf
