scrape_config_files:
  - scrape_configs/*.yml

scrape_configs:
  - job_name: ibms-gateway
    metrics_path: /metrics
#    scrape_interval: 30s
    static_configs:
      - targets: [ localhost:8080 ]

#  - job_name: ibms-gateway-devices
#    metrics_path: /metrics/devices
#    scrape_interval: 30s
#    relabel_configs:
#      - source_labels: [ __address__ ]
#        target_label: __param_target
#      - source_labels: [ __param_target ]
#        target_label: instance
#      - target_label: __address__
#        replacement: localhost:8080
#    static_configs:
#      - targets: [ 'AHU_2_1', 'AHU_2_3', 'AHU_B1_1' ]
