// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: types.proto
// Protobuf Java Version: 4.30.0

package cn.ecosync.aiot.data.apiserver.api.prometheus;

/**
 * <pre>
 * A BucketSpan defines a number of consecutive buckets with their
 * offset. Logically, it would be more straightforward to include the
 * bucket counts in the Span. However, the protobuf representation is
 * more compact in the way the data is structured here (with all the
 * buckets in a single array separate from the Spans).
 * </pre>
 *
 * Protobuf type {@code io.prometheus.write.v2.BucketSpan}
 */
public final class BucketSpan extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:io.prometheus.write.v2.BucketSpan)
    BucketSpanOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 30,
      /* patch= */ 0,
      /* suffix= */ "",
      BucketSpan.class.getName());
  }
  // Use BucketSpan.newBuilder() to construct.
  private BucketSpan(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private BucketSpan() {
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return cn.ecosync.aiot.data.apiserver.api.prometheus.PrometheusProto.internal_static_io_prometheus_write_v2_BucketSpan_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return cn.ecosync.aiot.data.apiserver.api.prometheus.PrometheusProto.internal_static_io_prometheus_write_v2_BucketSpan_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            cn.ecosync.aiot.data.apiserver.api.prometheus.BucketSpan.class, cn.ecosync.aiot.data.apiserver.api.prometheus.BucketSpan.Builder.class);
  }

  public static final int OFFSET_FIELD_NUMBER = 1;
  private int offset_ = 0;
  /**
   * <pre>
   * Gap to previous span, or starting point for 1st span (which can be negative).
   * </pre>
   *
   * <code>sint32 offset = 1;</code>
   * @return The offset.
   */
  @java.lang.Override
  public int getOffset() {
    return offset_;
  }

  public static final int LENGTH_FIELD_NUMBER = 2;
  private int length_ = 0;
  /**
   * <pre>
   * Length of consecutive buckets.
   * </pre>
   *
   * <code>uint32 length = 2;</code>
   * @return The length.
   */
  @java.lang.Override
  public int getLength() {
    return length_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (offset_ != 0) {
      output.writeSInt32(1, offset_);
    }
    if (length_ != 0) {
      output.writeUInt32(2, length_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (offset_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeSInt32Size(1, offset_);
    }
    if (length_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(2, length_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof cn.ecosync.aiot.data.apiserver.api.prometheus.BucketSpan)) {
      return super.equals(obj);
    }
    cn.ecosync.aiot.data.apiserver.api.prometheus.BucketSpan other = (cn.ecosync.aiot.data.apiserver.api.prometheus.BucketSpan) obj;

    if (getOffset()
        != other.getOffset()) return false;
    if (getLength()
        != other.getLength()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + OFFSET_FIELD_NUMBER;
    hash = (53 * hash) + getOffset();
    hash = (37 * hash) + LENGTH_FIELD_NUMBER;
    hash = (53 * hash) + getLength();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static cn.ecosync.aiot.data.apiserver.api.prometheus.BucketSpan parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cn.ecosync.aiot.data.apiserver.api.prometheus.BucketSpan parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cn.ecosync.aiot.data.apiserver.api.prometheus.BucketSpan parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cn.ecosync.aiot.data.apiserver.api.prometheus.BucketSpan parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cn.ecosync.aiot.data.apiserver.api.prometheus.BucketSpan parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cn.ecosync.aiot.data.apiserver.api.prometheus.BucketSpan parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cn.ecosync.aiot.data.apiserver.api.prometheus.BucketSpan parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static cn.ecosync.aiot.data.apiserver.api.prometheus.BucketSpan parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static cn.ecosync.aiot.data.apiserver.api.prometheus.BucketSpan parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static cn.ecosync.aiot.data.apiserver.api.prometheus.BucketSpan parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static cn.ecosync.aiot.data.apiserver.api.prometheus.BucketSpan parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static cn.ecosync.aiot.data.apiserver.api.prometheus.BucketSpan parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(cn.ecosync.aiot.data.apiserver.api.prometheus.BucketSpan prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * A BucketSpan defines a number of consecutive buckets with their
   * offset. Logically, it would be more straightforward to include the
   * bucket counts in the Span. However, the protobuf representation is
   * more compact in the way the data is structured here (with all the
   * buckets in a single array separate from the Spans).
   * </pre>
   *
   * Protobuf type {@code io.prometheus.write.v2.BucketSpan}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:io.prometheus.write.v2.BucketSpan)
      cn.ecosync.aiot.data.apiserver.api.prometheus.BucketSpanOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cn.ecosync.aiot.data.apiserver.api.prometheus.PrometheusProto.internal_static_io_prometheus_write_v2_BucketSpan_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cn.ecosync.aiot.data.apiserver.api.prometheus.PrometheusProto.internal_static_io_prometheus_write_v2_BucketSpan_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cn.ecosync.aiot.data.apiserver.api.prometheus.BucketSpan.class, cn.ecosync.aiot.data.apiserver.api.prometheus.BucketSpan.Builder.class);
    }

    // Construct using cn.ecosync.aiot.data.apiserver.api.prometheus.BucketSpan.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      offset_ = 0;
      length_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return cn.ecosync.aiot.data.apiserver.api.prometheus.PrometheusProto.internal_static_io_prometheus_write_v2_BucketSpan_descriptor;
    }

    @java.lang.Override
    public cn.ecosync.aiot.data.apiserver.api.prometheus.BucketSpan getDefaultInstanceForType() {
      return cn.ecosync.aiot.data.apiserver.api.prometheus.BucketSpan.getDefaultInstance();
    }

    @java.lang.Override
    public cn.ecosync.aiot.data.apiserver.api.prometheus.BucketSpan build() {
      cn.ecosync.aiot.data.apiserver.api.prometheus.BucketSpan result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public cn.ecosync.aiot.data.apiserver.api.prometheus.BucketSpan buildPartial() {
      cn.ecosync.aiot.data.apiserver.api.prometheus.BucketSpan result = new cn.ecosync.aiot.data.apiserver.api.prometheus.BucketSpan(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(cn.ecosync.aiot.data.apiserver.api.prometheus.BucketSpan result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.offset_ = offset_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.length_ = length_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof cn.ecosync.aiot.data.apiserver.api.prometheus.BucketSpan) {
        return mergeFrom((cn.ecosync.aiot.data.apiserver.api.prometheus.BucketSpan)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(cn.ecosync.aiot.data.apiserver.api.prometheus.BucketSpan other) {
      if (other == cn.ecosync.aiot.data.apiserver.api.prometheus.BucketSpan.getDefaultInstance()) return this;
      if (other.getOffset() != 0) {
        setOffset(other.getOffset());
      }
      if (other.getLength() != 0) {
        setLength(other.getLength());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              offset_ = input.readSInt32();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              length_ = input.readUInt32();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int offset_ ;
    /**
     * <pre>
     * Gap to previous span, or starting point for 1st span (which can be negative).
     * </pre>
     *
     * <code>sint32 offset = 1;</code>
     * @return The offset.
     */
    @java.lang.Override
    public int getOffset() {
      return offset_;
    }
    /**
     * <pre>
     * Gap to previous span, or starting point for 1st span (which can be negative).
     * </pre>
     *
     * <code>sint32 offset = 1;</code>
     * @param value The offset to set.
     * @return This builder for chaining.
     */
    public Builder setOffset(int value) {

      offset_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Gap to previous span, or starting point for 1st span (which can be negative).
     * </pre>
     *
     * <code>sint32 offset = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearOffset() {
      bitField0_ = (bitField0_ & ~0x00000001);
      offset_ = 0;
      onChanged();
      return this;
    }

    private int length_ ;
    /**
     * <pre>
     * Length of consecutive buckets.
     * </pre>
     *
     * <code>uint32 length = 2;</code>
     * @return The length.
     */
    @java.lang.Override
    public int getLength() {
      return length_;
    }
    /**
     * <pre>
     * Length of consecutive buckets.
     * </pre>
     *
     * <code>uint32 length = 2;</code>
     * @param value The length to set.
     * @return This builder for chaining.
     */
    public Builder setLength(int value) {

      length_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Length of consecutive buckets.
     * </pre>
     *
     * <code>uint32 length = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearLength() {
      bitField0_ = (bitField0_ & ~0x00000002);
      length_ = 0;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:io.prometheus.write.v2.BucketSpan)
  }

  // @@protoc_insertion_point(class_scope:io.prometheus.write.v2.BucketSpan)
  private static final cn.ecosync.aiot.data.apiserver.api.prometheus.BucketSpan DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new cn.ecosync.aiot.data.apiserver.api.prometheus.BucketSpan();
  }

  public static cn.ecosync.aiot.data.apiserver.api.prometheus.BucketSpan getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<BucketSpan>
      PARSER = new com.google.protobuf.AbstractParser<BucketSpan>() {
    @java.lang.Override
    public BucketSpan parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<BucketSpan> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<BucketSpan> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public cn.ecosync.aiot.data.apiserver.api.prometheus.BucketSpan getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

