// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: types.proto
// Protobuf Java Version: 4.30.0

package cn.ecosync.aiot.data.apiserver.api.prometheus;

public interface BucketSpanOrBuilder extends
    // @@protoc_insertion_point(interface_extends:io.prometheus.write.v2.BucketSpan)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Gap to previous span, or starting point for 1st span (which can be negative).
   * </pre>
   *
   * <code>sint32 offset = 1;</code>
   * @return The offset.
   */
  int getOffset();

  /**
   * <pre>
   * Length of consecutive buckets.
   * </pre>
   *
   * <code>uint32 length = 2;</code>
   * @return The length.
   */
  int getLength();
}
