// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: types.proto
// Protobuf Java Version: 4.30.0

package cn.ecosync.aiot.data.apiserver.api.prometheus;

public interface ExemplarOrBuilder extends
    // @@protoc_insertion_point(interface_extends:io.prometheus.write.v2.Exemplar)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * labels_refs is an optional list of label name-value pair references, encoded
   * as indices to the Request.symbols array. This list's len is always
   * a multiple of 2, and the underlying labels should be sorted lexicographically.
   * If the exemplar references a trace it should use the `trace_id` label name, as a best practice.
   * </pre>
   *
   * <code>repeated uint32 labels_refs = 1;</code>
   * @return A list containing the labelsRefs.
   */
  java.util.List<java.lang.Integer> getLabelsRefsList();
  /**
   * <pre>
   * labels_refs is an optional list of label name-value pair references, encoded
   * as indices to the Request.symbols array. This list's len is always
   * a multiple of 2, and the underlying labels should be sorted lexicographically.
   * If the exemplar references a trace it should use the `trace_id` label name, as a best practice.
   * </pre>
   *
   * <code>repeated uint32 labels_refs = 1;</code>
   * @return The count of labelsRefs.
   */
  int getLabelsRefsCount();
  /**
   * <pre>
   * labels_refs is an optional list of label name-value pair references, encoded
   * as indices to the Request.symbols array. This list's len is always
   * a multiple of 2, and the underlying labels should be sorted lexicographically.
   * If the exemplar references a trace it should use the `trace_id` label name, as a best practice.
   * </pre>
   *
   * <code>repeated uint32 labels_refs = 1;</code>
   * @param index The index of the element to return.
   * @return The labelsRefs at the given index.
   */
  int getLabelsRefs(int index);

  /**
   * <pre>
   * value represents an exact example value. This can be useful when the exemplar
   * is attached to a histogram, which only gives an estimated value through buckets.
   * </pre>
   *
   * <code>double value = 2;</code>
   * @return The value.
   */
  double getValue();

  /**
   * <pre>
   * timestamp represents an optional timestamp of the sample in ms.
   *
   * For Go, see github.com/prometheus/prometheus/model/timestamp/timestamp.go
   * for conversion from/to time.Time to Prometheus timestamp.
   *
   * Note that the "optional" keyword is omitted due to
   * https://cloud.google.com/apis/design/design_patterns.md#optional_primitive_fields
   * Zero value means value not set. If you need to use exactly zero value for
   * the timestamp, use 1 millisecond before or after.
   * </pre>
   *
   * <code>int64 timestamp = 3;</code>
   * @return The timestamp.
   */
  long getTimestamp();
}
