// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: types.proto
// Protobuf Java Version: 4.30.0

package cn.ecosync.aiot.data.apiserver.api.prometheus;

/**
 * <pre>
 * Exemplar is an additional information attached to some series' samples.
 * It is typically used to attach an example trace or request ID associated with
 * the metric changes.
 * </pre>
 *
 * Protobuf type {@code io.prometheus.write.v2.Exemplar}
 */
public final class Exemplar extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:io.prometheus.write.v2.Exemplar)
    ExemplarOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 30,
      /* patch= */ 0,
      /* suffix= */ "",
      Exemplar.class.getName());
  }
  // Use Exemplar.newBuilder() to construct.
  private Exemplar(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private Exemplar() {
    labelsRefs_ = emptyIntList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return cn.ecosync.aiot.data.apiserver.api.prometheus.PrometheusProto.internal_static_io_prometheus_write_v2_Exemplar_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return cn.ecosync.aiot.data.apiserver.api.prometheus.PrometheusProto.internal_static_io_prometheus_write_v2_Exemplar_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            cn.ecosync.aiot.data.apiserver.api.prometheus.Exemplar.class, cn.ecosync.aiot.data.apiserver.api.prometheus.Exemplar.Builder.class);
  }

  public static final int LABELS_REFS_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private com.google.protobuf.Internal.IntList labelsRefs_ =
      emptyIntList();
  /**
   * <pre>
   * labels_refs is an optional list of label name-value pair references, encoded
   * as indices to the Request.symbols array. This list's len is always
   * a multiple of 2, and the underlying labels should be sorted lexicographically.
   * If the exemplar references a trace it should use the `trace_id` label name, as a best practice.
   * </pre>
   *
   * <code>repeated uint32 labels_refs = 1;</code>
   * @return A list containing the labelsRefs.
   */
  @java.lang.Override
  public java.util.List<java.lang.Integer>
      getLabelsRefsList() {
    return labelsRefs_;
  }
  /**
   * <pre>
   * labels_refs is an optional list of label name-value pair references, encoded
   * as indices to the Request.symbols array. This list's len is always
   * a multiple of 2, and the underlying labels should be sorted lexicographically.
   * If the exemplar references a trace it should use the `trace_id` label name, as a best practice.
   * </pre>
   *
   * <code>repeated uint32 labels_refs = 1;</code>
   * @return The count of labelsRefs.
   */
  public int getLabelsRefsCount() {
    return labelsRefs_.size();
  }
  /**
   * <pre>
   * labels_refs is an optional list of label name-value pair references, encoded
   * as indices to the Request.symbols array. This list's len is always
   * a multiple of 2, and the underlying labels should be sorted lexicographically.
   * If the exemplar references a trace it should use the `trace_id` label name, as a best practice.
   * </pre>
   *
   * <code>repeated uint32 labels_refs = 1;</code>
   * @param index The index of the element to return.
   * @return The labelsRefs at the given index.
   */
  public int getLabelsRefs(int index) {
    return labelsRefs_.getInt(index);
  }
  private int labelsRefsMemoizedSerializedSize = -1;

  public static final int VALUE_FIELD_NUMBER = 2;
  private double value_ = 0D;
  /**
   * <pre>
   * value represents an exact example value. This can be useful when the exemplar
   * is attached to a histogram, which only gives an estimated value through buckets.
   * </pre>
   *
   * <code>double value = 2;</code>
   * @return The value.
   */
  @java.lang.Override
  public double getValue() {
    return value_;
  }

  public static final int TIMESTAMP_FIELD_NUMBER = 3;
  private long timestamp_ = 0L;
  /**
   * <pre>
   * timestamp represents an optional timestamp of the sample in ms.
   *
   * For Go, see github.com/prometheus/prometheus/model/timestamp/timestamp.go
   * for conversion from/to time.Time to Prometheus timestamp.
   *
   * Note that the "optional" keyword is omitted due to
   * https://cloud.google.com/apis/design/design_patterns.md#optional_primitive_fields
   * Zero value means value not set. If you need to use exactly zero value for
   * the timestamp, use 1 millisecond before or after.
   * </pre>
   *
   * <code>int64 timestamp = 3;</code>
   * @return The timestamp.
   */
  @java.lang.Override
  public long getTimestamp() {
    return timestamp_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (getLabelsRefsList().size() > 0) {
      output.writeUInt32NoTag(10);
      output.writeUInt32NoTag(labelsRefsMemoizedSerializedSize);
    }
    for (int i = 0; i < labelsRefs_.size(); i++) {
      output.writeUInt32NoTag(labelsRefs_.getInt(i));
    }
    if (java.lang.Double.doubleToRawLongBits(value_) != 0) {
      output.writeDouble(2, value_);
    }
    if (timestamp_ != 0L) {
      output.writeInt64(3, timestamp_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    {
      int dataSize = 0;
      for (int i = 0; i < labelsRefs_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeUInt32SizeNoTag(labelsRefs_.getInt(i));
      }
      size += dataSize;
      if (!getLabelsRefsList().isEmpty()) {
        size += 1;
        size += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(dataSize);
      }
      labelsRefsMemoizedSerializedSize = dataSize;
    }
    if (java.lang.Double.doubleToRawLongBits(value_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(2, value_);
    }
    if (timestamp_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(3, timestamp_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof cn.ecosync.aiot.data.apiserver.api.prometheus.Exemplar)) {
      return super.equals(obj);
    }
    cn.ecosync.aiot.data.apiserver.api.prometheus.Exemplar other = (cn.ecosync.aiot.data.apiserver.api.prometheus.Exemplar) obj;

    if (!getLabelsRefsList()
        .equals(other.getLabelsRefsList())) return false;
    if (java.lang.Double.doubleToLongBits(getValue())
        != java.lang.Double.doubleToLongBits(
            other.getValue())) return false;
    if (getTimestamp()
        != other.getTimestamp()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getLabelsRefsCount() > 0) {
      hash = (37 * hash) + LABELS_REFS_FIELD_NUMBER;
      hash = (53 * hash) + getLabelsRefsList().hashCode();
    }
    hash = (37 * hash) + VALUE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getValue()));
    hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTimestamp());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static cn.ecosync.aiot.data.apiserver.api.prometheus.Exemplar parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cn.ecosync.aiot.data.apiserver.api.prometheus.Exemplar parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cn.ecosync.aiot.data.apiserver.api.prometheus.Exemplar parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cn.ecosync.aiot.data.apiserver.api.prometheus.Exemplar parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cn.ecosync.aiot.data.apiserver.api.prometheus.Exemplar parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cn.ecosync.aiot.data.apiserver.api.prometheus.Exemplar parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cn.ecosync.aiot.data.apiserver.api.prometheus.Exemplar parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static cn.ecosync.aiot.data.apiserver.api.prometheus.Exemplar parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static cn.ecosync.aiot.data.apiserver.api.prometheus.Exemplar parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static cn.ecosync.aiot.data.apiserver.api.prometheus.Exemplar parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static cn.ecosync.aiot.data.apiserver.api.prometheus.Exemplar parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static cn.ecosync.aiot.data.apiserver.api.prometheus.Exemplar parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(cn.ecosync.aiot.data.apiserver.api.prometheus.Exemplar prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Exemplar is an additional information attached to some series' samples.
   * It is typically used to attach an example trace or request ID associated with
   * the metric changes.
   * </pre>
   *
   * Protobuf type {@code io.prometheus.write.v2.Exemplar}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:io.prometheus.write.v2.Exemplar)
      cn.ecosync.aiot.data.apiserver.api.prometheus.ExemplarOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cn.ecosync.aiot.data.apiserver.api.prometheus.PrometheusProto.internal_static_io_prometheus_write_v2_Exemplar_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cn.ecosync.aiot.data.apiserver.api.prometheus.PrometheusProto.internal_static_io_prometheus_write_v2_Exemplar_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cn.ecosync.aiot.data.apiserver.api.prometheus.Exemplar.class, cn.ecosync.aiot.data.apiserver.api.prometheus.Exemplar.Builder.class);
    }

    // Construct using cn.ecosync.aiot.data.apiserver.api.prometheus.Exemplar.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      labelsRefs_ = emptyIntList();
      value_ = 0D;
      timestamp_ = 0L;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return cn.ecosync.aiot.data.apiserver.api.prometheus.PrometheusProto.internal_static_io_prometheus_write_v2_Exemplar_descriptor;
    }

    @java.lang.Override
    public cn.ecosync.aiot.data.apiserver.api.prometheus.Exemplar getDefaultInstanceForType() {
      return cn.ecosync.aiot.data.apiserver.api.prometheus.Exemplar.getDefaultInstance();
    }

    @java.lang.Override
    public cn.ecosync.aiot.data.apiserver.api.prometheus.Exemplar build() {
      cn.ecosync.aiot.data.apiserver.api.prometheus.Exemplar result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public cn.ecosync.aiot.data.apiserver.api.prometheus.Exemplar buildPartial() {
      cn.ecosync.aiot.data.apiserver.api.prometheus.Exemplar result = new cn.ecosync.aiot.data.apiserver.api.prometheus.Exemplar(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(cn.ecosync.aiot.data.apiserver.api.prometheus.Exemplar result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        labelsRefs_.makeImmutable();
        result.labelsRefs_ = labelsRefs_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.value_ = value_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.timestamp_ = timestamp_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof cn.ecosync.aiot.data.apiserver.api.prometheus.Exemplar) {
        return mergeFrom((cn.ecosync.aiot.data.apiserver.api.prometheus.Exemplar)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(cn.ecosync.aiot.data.apiserver.api.prometheus.Exemplar other) {
      if (other == cn.ecosync.aiot.data.apiserver.api.prometheus.Exemplar.getDefaultInstance()) return this;
      if (!other.labelsRefs_.isEmpty()) {
        if (labelsRefs_.isEmpty()) {
          labelsRefs_ = other.labelsRefs_;
          labelsRefs_.makeImmutable();
          bitField0_ |= 0x00000001;
        } else {
          ensureLabelsRefsIsMutable();
          labelsRefs_.addAll(other.labelsRefs_);
        }
        onChanged();
      }
      if (java.lang.Double.doubleToRawLongBits(other.getValue()) != 0) {
        setValue(other.getValue());
      }
      if (other.getTimestamp() != 0L) {
        setTimestamp(other.getTimestamp());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int v = input.readUInt32();
              ensureLabelsRefsIsMutable();
              labelsRefs_.addInt(v);
              break;
            } // case 8
            case 10: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              ensureLabelsRefsIsMutable();
              while (input.getBytesUntilLimit() > 0) {
                labelsRefs_.addInt(input.readUInt32());
              }
              input.popLimit(limit);
              break;
            } // case 10
            case 17: {
              value_ = input.readDouble();
              bitField0_ |= 0x00000002;
              break;
            } // case 17
            case 24: {
              timestamp_ = input.readInt64();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.Internal.IntList labelsRefs_ = emptyIntList();
    private void ensureLabelsRefsIsMutable() {
      if (!labelsRefs_.isModifiable()) {
        labelsRefs_ = makeMutableCopy(labelsRefs_);
      }
      bitField0_ |= 0x00000001;
    }
    /**
     * <pre>
     * labels_refs is an optional list of label name-value pair references, encoded
     * as indices to the Request.symbols array. This list's len is always
     * a multiple of 2, and the underlying labels should be sorted lexicographically.
     * If the exemplar references a trace it should use the `trace_id` label name, as a best practice.
     * </pre>
     *
     * <code>repeated uint32 labels_refs = 1;</code>
     * @return A list containing the labelsRefs.
     */
    public java.util.List<java.lang.Integer>
        getLabelsRefsList() {
      labelsRefs_.makeImmutable();
      return labelsRefs_;
    }
    /**
     * <pre>
     * labels_refs is an optional list of label name-value pair references, encoded
     * as indices to the Request.symbols array. This list's len is always
     * a multiple of 2, and the underlying labels should be sorted lexicographically.
     * If the exemplar references a trace it should use the `trace_id` label name, as a best practice.
     * </pre>
     *
     * <code>repeated uint32 labels_refs = 1;</code>
     * @return The count of labelsRefs.
     */
    public int getLabelsRefsCount() {
      return labelsRefs_.size();
    }
    /**
     * <pre>
     * labels_refs is an optional list of label name-value pair references, encoded
     * as indices to the Request.symbols array. This list's len is always
     * a multiple of 2, and the underlying labels should be sorted lexicographically.
     * If the exemplar references a trace it should use the `trace_id` label name, as a best practice.
     * </pre>
     *
     * <code>repeated uint32 labels_refs = 1;</code>
     * @param index The index of the element to return.
     * @return The labelsRefs at the given index.
     */
    public int getLabelsRefs(int index) {
      return labelsRefs_.getInt(index);
    }
    /**
     * <pre>
     * labels_refs is an optional list of label name-value pair references, encoded
     * as indices to the Request.symbols array. This list's len is always
     * a multiple of 2, and the underlying labels should be sorted lexicographically.
     * If the exemplar references a trace it should use the `trace_id` label name, as a best practice.
     * </pre>
     *
     * <code>repeated uint32 labels_refs = 1;</code>
     * @param index The index to set the value at.
     * @param value The labelsRefs to set.
     * @return This builder for chaining.
     */
    public Builder setLabelsRefs(
        int index, int value) {

      ensureLabelsRefsIsMutable();
      labelsRefs_.setInt(index, value);
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * labels_refs is an optional list of label name-value pair references, encoded
     * as indices to the Request.symbols array. This list's len is always
     * a multiple of 2, and the underlying labels should be sorted lexicographically.
     * If the exemplar references a trace it should use the `trace_id` label name, as a best practice.
     * </pre>
     *
     * <code>repeated uint32 labels_refs = 1;</code>
     * @param value The labelsRefs to add.
     * @return This builder for chaining.
     */
    public Builder addLabelsRefs(int value) {

      ensureLabelsRefsIsMutable();
      labelsRefs_.addInt(value);
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * labels_refs is an optional list of label name-value pair references, encoded
     * as indices to the Request.symbols array. This list's len is always
     * a multiple of 2, and the underlying labels should be sorted lexicographically.
     * If the exemplar references a trace it should use the `trace_id` label name, as a best practice.
     * </pre>
     *
     * <code>repeated uint32 labels_refs = 1;</code>
     * @param values The labelsRefs to add.
     * @return This builder for chaining.
     */
    public Builder addAllLabelsRefs(
        java.lang.Iterable<? extends java.lang.Integer> values) {
      ensureLabelsRefsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, labelsRefs_);
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * labels_refs is an optional list of label name-value pair references, encoded
     * as indices to the Request.symbols array. This list's len is always
     * a multiple of 2, and the underlying labels should be sorted lexicographically.
     * If the exemplar references a trace it should use the `trace_id` label name, as a best practice.
     * </pre>
     *
     * <code>repeated uint32 labels_refs = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearLabelsRefs() {
      labelsRefs_ = emptyIntList();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }

    private double value_ ;
    /**
     * <pre>
     * value represents an exact example value. This can be useful when the exemplar
     * is attached to a histogram, which only gives an estimated value through buckets.
     * </pre>
     *
     * <code>double value = 2;</code>
     * @return The value.
     */
    @java.lang.Override
    public double getValue() {
      return value_;
    }
    /**
     * <pre>
     * value represents an exact example value. This can be useful when the exemplar
     * is attached to a histogram, which only gives an estimated value through buckets.
     * </pre>
     *
     * <code>double value = 2;</code>
     * @param value The value to set.
     * @return This builder for chaining.
     */
    public Builder setValue(double value) {

      value_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * value represents an exact example value. This can be useful when the exemplar
     * is attached to a histogram, which only gives an estimated value through buckets.
     * </pre>
     *
     * <code>double value = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearValue() {
      bitField0_ = (bitField0_ & ~0x00000002);
      value_ = 0D;
      onChanged();
      return this;
    }

    private long timestamp_ ;
    /**
     * <pre>
     * timestamp represents an optional timestamp of the sample in ms.
     *
     * For Go, see github.com/prometheus/prometheus/model/timestamp/timestamp.go
     * for conversion from/to time.Time to Prometheus timestamp.
     *
     * Note that the "optional" keyword is omitted due to
     * https://cloud.google.com/apis/design/design_patterns.md#optional_primitive_fields
     * Zero value means value not set. If you need to use exactly zero value for
     * the timestamp, use 1 millisecond before or after.
     * </pre>
     *
     * <code>int64 timestamp = 3;</code>
     * @return The timestamp.
     */
    @java.lang.Override
    public long getTimestamp() {
      return timestamp_;
    }
    /**
     * <pre>
     * timestamp represents an optional timestamp of the sample in ms.
     *
     * For Go, see github.com/prometheus/prometheus/model/timestamp/timestamp.go
     * for conversion from/to time.Time to Prometheus timestamp.
     *
     * Note that the "optional" keyword is omitted due to
     * https://cloud.google.com/apis/design/design_patterns.md#optional_primitive_fields
     * Zero value means value not set. If you need to use exactly zero value for
     * the timestamp, use 1 millisecond before or after.
     * </pre>
     *
     * <code>int64 timestamp = 3;</code>
     * @param value The timestamp to set.
     * @return This builder for chaining.
     */
    public Builder setTimestamp(long value) {

      timestamp_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * timestamp represents an optional timestamp of the sample in ms.
     *
     * For Go, see github.com/prometheus/prometheus/model/timestamp/timestamp.go
     * for conversion from/to time.Time to Prometheus timestamp.
     *
     * Note that the "optional" keyword is omitted due to
     * https://cloud.google.com/apis/design/design_patterns.md#optional_primitive_fields
     * Zero value means value not set. If you need to use exactly zero value for
     * the timestamp, use 1 millisecond before or after.
     * </pre>
     *
     * <code>int64 timestamp = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearTimestamp() {
      bitField0_ = (bitField0_ & ~0x00000004);
      timestamp_ = 0L;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:io.prometheus.write.v2.Exemplar)
  }

  // @@protoc_insertion_point(class_scope:io.prometheus.write.v2.Exemplar)
  private static final cn.ecosync.aiot.data.apiserver.api.prometheus.Exemplar DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new cn.ecosync.aiot.data.apiserver.api.prometheus.Exemplar();
  }

  public static cn.ecosync.aiot.data.apiserver.api.prometheus.Exemplar getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Exemplar>
      PARSER = new com.google.protobuf.AbstractParser<Exemplar>() {
    @java.lang.Override
    public Exemplar parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Exemplar> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Exemplar> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public cn.ecosync.aiot.data.apiserver.api.prometheus.Exemplar getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

