// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: types.proto
// Protobuf Java Version: 4.30.0

package cn.ecosync.aiot.data.apiserver.api.prometheus;

public interface HistogramOrBuilder extends
    // @@protoc_insertion_point(interface_extends:io.prometheus.write.v2.Histogram)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint64 count_int = 1;</code>
   * @return Whether the countInt field is set.
   */
  boolean hasCountInt();
  /**
   * <code>uint64 count_int = 1;</code>
   * @return The countInt.
   */
  long getCountInt();

  /**
   * <code>double count_float = 2;</code>
   * @return Whether the countFloat field is set.
   */
  boolean hasCountFloat();
  /**
   * <code>double count_float = 2;</code>
   * @return The countFloat.
   */
  double getCountFloat();

  /**
   * <pre>
   * Sum of observations in the histogram.
   * </pre>
   *
   * <code>double sum = 3;</code>
   * @return The sum.
   */
  double getSum();

  /**
   * <pre>
   * The schema defines the bucket schema. Currently, valid numbers
   * are -53 and numbers in range of -4 &lt;= n &lt;= 8. More valid numbers might be
   * added in future for new bucketing layouts.
   *
   * The schema equal to -53 means custom buckets. See
   * custom_values field description for more details.
   *
   * Values between -4 and 8 represent base-2 bucket schema, where 1
   * is a bucket boundary in each case, and then each power of two is
   * divided into 2^n (n is schema value) logarithmic buckets. Or in other words,
   * each bucket boundary is the previous boundary times 2^(2^-n).
   * </pre>
   *
   * <code>sint32 schema = 4;</code>
   * @return The schema.
   */
  int getSchema();

  /**
   * <pre>
   * Breadth of the zero bucket.
   * </pre>
   *
   * <code>double zero_threshold = 5;</code>
   * @return The zeroThreshold.
   */
  double getZeroThreshold();

  /**
   * <code>uint64 zero_count_int = 6;</code>
   * @return Whether the zeroCountInt field is set.
   */
  boolean hasZeroCountInt();
  /**
   * <code>uint64 zero_count_int = 6;</code>
   * @return The zeroCountInt.
   */
  long getZeroCountInt();

  /**
   * <code>double zero_count_float = 7;</code>
   * @return Whether the zeroCountFloat field is set.
   */
  boolean hasZeroCountFloat();
  /**
   * <code>double zero_count_float = 7;</code>
   * @return The zeroCountFloat.
   */
  double getZeroCountFloat();

  /**
   * <pre>
   * Negative Buckets.
   * </pre>
   *
   * <code>repeated .io.prometheus.write.v2.BucketSpan negative_spans = 8;</code>
   */
  java.util.List<cn.ecosync.aiot.data.apiserver.api.prometheus.BucketSpan> 
      getNegativeSpansList();
  /**
   * <pre>
   * Negative Buckets.
   * </pre>
   *
   * <code>repeated .io.prometheus.write.v2.BucketSpan negative_spans = 8;</code>
   */
  cn.ecosync.aiot.data.apiserver.api.prometheus.BucketSpan getNegativeSpans(int index);
  /**
   * <pre>
   * Negative Buckets.
   * </pre>
   *
   * <code>repeated .io.prometheus.write.v2.BucketSpan negative_spans = 8;</code>
   */
  int getNegativeSpansCount();
  /**
   * <pre>
   * Negative Buckets.
   * </pre>
   *
   * <code>repeated .io.prometheus.write.v2.BucketSpan negative_spans = 8;</code>
   */
  java.util.List<? extends cn.ecosync.aiot.data.apiserver.api.prometheus.BucketSpanOrBuilder> 
      getNegativeSpansOrBuilderList();
  /**
   * <pre>
   * Negative Buckets.
   * </pre>
   *
   * <code>repeated .io.prometheus.write.v2.BucketSpan negative_spans = 8;</code>
   */
  cn.ecosync.aiot.data.apiserver.api.prometheus.BucketSpanOrBuilder getNegativeSpansOrBuilder(
      int index);

  /**
   * <pre>
   * Use either "negative_deltas" or "negative_counts", the former for
   * regular histograms with integer counts, the latter for
   * float histograms.
   * </pre>
   *
   * <code>repeated sint64 negative_deltas = 9;</code>
   * @return A list containing the negativeDeltas.
   */
  java.util.List<java.lang.Long> getNegativeDeltasList();
  /**
   * <pre>
   * Use either "negative_deltas" or "negative_counts", the former for
   * regular histograms with integer counts, the latter for
   * float histograms.
   * </pre>
   *
   * <code>repeated sint64 negative_deltas = 9;</code>
   * @return The count of negativeDeltas.
   */
  int getNegativeDeltasCount();
  /**
   * <pre>
   * Use either "negative_deltas" or "negative_counts", the former for
   * regular histograms with integer counts, the latter for
   * float histograms.
   * </pre>
   *
   * <code>repeated sint64 negative_deltas = 9;</code>
   * @param index The index of the element to return.
   * @return The negativeDeltas at the given index.
   */
  long getNegativeDeltas(int index);

  /**
   * <pre>
   * Absolute count of each bucket.
   * </pre>
   *
   * <code>repeated double negative_counts = 10;</code>
   * @return A list containing the negativeCounts.
   */
  java.util.List<java.lang.Double> getNegativeCountsList();
  /**
   * <pre>
   * Absolute count of each bucket.
   * </pre>
   *
   * <code>repeated double negative_counts = 10;</code>
   * @return The count of negativeCounts.
   */
  int getNegativeCountsCount();
  /**
   * <pre>
   * Absolute count of each bucket.
   * </pre>
   *
   * <code>repeated double negative_counts = 10;</code>
   * @param index The index of the element to return.
   * @return The negativeCounts at the given index.
   */
  double getNegativeCounts(int index);

  /**
   * <pre>
   * Positive Buckets.
   *
   * In case of custom buckets (-53 schema value) the positive buckets are interpreted as follows:
   * * The span offset+length points to an the index of the custom_values array
   * or +Inf if pointing to the len of the array.
   * * The counts and deltas have the same meaning as for exponential histograms.
   * </pre>
   *
   * <code>repeated .io.prometheus.write.v2.BucketSpan positive_spans = 11;</code>
   */
  java.util.List<cn.ecosync.aiot.data.apiserver.api.prometheus.BucketSpan> 
      getPositiveSpansList();
  /**
   * <pre>
   * Positive Buckets.
   *
   * In case of custom buckets (-53 schema value) the positive buckets are interpreted as follows:
   * * The span offset+length points to an the index of the custom_values array
   * or +Inf if pointing to the len of the array.
   * * The counts and deltas have the same meaning as for exponential histograms.
   * </pre>
   *
   * <code>repeated .io.prometheus.write.v2.BucketSpan positive_spans = 11;</code>
   */
  cn.ecosync.aiot.data.apiserver.api.prometheus.BucketSpan getPositiveSpans(int index);
  /**
   * <pre>
   * Positive Buckets.
   *
   * In case of custom buckets (-53 schema value) the positive buckets are interpreted as follows:
   * * The span offset+length points to an the index of the custom_values array
   * or +Inf if pointing to the len of the array.
   * * The counts and deltas have the same meaning as for exponential histograms.
   * </pre>
   *
   * <code>repeated .io.prometheus.write.v2.BucketSpan positive_spans = 11;</code>
   */
  int getPositiveSpansCount();
  /**
   * <pre>
   * Positive Buckets.
   *
   * In case of custom buckets (-53 schema value) the positive buckets are interpreted as follows:
   * * The span offset+length points to an the index of the custom_values array
   * or +Inf if pointing to the len of the array.
   * * The counts and deltas have the same meaning as for exponential histograms.
   * </pre>
   *
   * <code>repeated .io.prometheus.write.v2.BucketSpan positive_spans = 11;</code>
   */
  java.util.List<? extends cn.ecosync.aiot.data.apiserver.api.prometheus.BucketSpanOrBuilder> 
      getPositiveSpansOrBuilderList();
  /**
   * <pre>
   * Positive Buckets.
   *
   * In case of custom buckets (-53 schema value) the positive buckets are interpreted as follows:
   * * The span offset+length points to an the index of the custom_values array
   * or +Inf if pointing to the len of the array.
   * * The counts and deltas have the same meaning as for exponential histograms.
   * </pre>
   *
   * <code>repeated .io.prometheus.write.v2.BucketSpan positive_spans = 11;</code>
   */
  cn.ecosync.aiot.data.apiserver.api.prometheus.BucketSpanOrBuilder getPositiveSpansOrBuilder(
      int index);

  /**
   * <pre>
   * Use either "positive_deltas" or "positive_counts", the former for
   * regular histograms with integer counts, the latter for
   * float histograms.
   * </pre>
   *
   * <code>repeated sint64 positive_deltas = 12;</code>
   * @return A list containing the positiveDeltas.
   */
  java.util.List<java.lang.Long> getPositiveDeltasList();
  /**
   * <pre>
   * Use either "positive_deltas" or "positive_counts", the former for
   * regular histograms with integer counts, the latter for
   * float histograms.
   * </pre>
   *
   * <code>repeated sint64 positive_deltas = 12;</code>
   * @return The count of positiveDeltas.
   */
  int getPositiveDeltasCount();
  /**
   * <pre>
   * Use either "positive_deltas" or "positive_counts", the former for
   * regular histograms with integer counts, the latter for
   * float histograms.
   * </pre>
   *
   * <code>repeated sint64 positive_deltas = 12;</code>
   * @param index The index of the element to return.
   * @return The positiveDeltas at the given index.
   */
  long getPositiveDeltas(int index);

  /**
   * <pre>
   * Absolute count of each bucket.
   * </pre>
   *
   * <code>repeated double positive_counts = 13;</code>
   * @return A list containing the positiveCounts.
   */
  java.util.List<java.lang.Double> getPositiveCountsList();
  /**
   * <pre>
   * Absolute count of each bucket.
   * </pre>
   *
   * <code>repeated double positive_counts = 13;</code>
   * @return The count of positiveCounts.
   */
  int getPositiveCountsCount();
  /**
   * <pre>
   * Absolute count of each bucket.
   * </pre>
   *
   * <code>repeated double positive_counts = 13;</code>
   * @param index The index of the element to return.
   * @return The positiveCounts at the given index.
   */
  double getPositiveCounts(int index);

  /**
   * <code>.io.prometheus.write.v2.Histogram.ResetHint reset_hint = 14;</code>
   * @return The enum numeric value on the wire for resetHint.
   */
  int getResetHintValue();
  /**
   * <code>.io.prometheus.write.v2.Histogram.ResetHint reset_hint = 14;</code>
   * @return The resetHint.
   */
  cn.ecosync.aiot.data.apiserver.api.prometheus.Histogram.ResetHint getResetHint();

  /**
   * <pre>
   * timestamp represents timestamp of the sample in ms.
   *
   * For Go, see github.com/prometheus/prometheus/model/timestamp/timestamp.go
   * for conversion from/to time.Time to Prometheus timestamp.
   * </pre>
   *
   * <code>int64 timestamp = 15;</code>
   * @return The timestamp.
   */
  long getTimestamp();

  /**
   * <pre>
   * custom_values is an additional field used by non-exponential bucketing layouts.
   *
   * For custom buckets (-53 schema value) custom_values specify monotonically
   * increasing upper inclusive boundaries for the bucket counts with arbitrary
   * widths for this histogram. In other words, custom_values represents custom,
   * explicit bucketing that could have been converted from the classic histograms.
   *
   * Those bounds are then referenced by spans in positive_spans with corresponding positive
   * counts of deltas (refer to positive_spans for more details). This way we can
   * have encode sparse histograms with custom bucketing (many buckets are often
   * not used).
   *
   * Note that for custom bounds, even negative observations are placed in the positive
   * counts to simplify the implementation and avoid ambiguity of where to place
   * an underflow bucket, e.g. (-2, 1]. Therefore negative buckets and
   * the zero bucket are unused, if the schema indicates custom bucketing.
   *
   * For each upper boundary the previous boundary represent the lower exclusive
   * boundary for that bucket. The first element is the upper inclusive boundary
   * for the first bucket, which implicitly has a lower inclusive bound of -Inf.
   * This is similar to "le" label semantics on classic histograms. You may add a
   * bucket with an upper bound of 0 to make sure that you really have no negative
   * observations, but in practice, native histogram rendering will show both with
   * or without first upper boundary 0 and no negative counts as the same case.
   *
   * The last element is not only the upper inclusive bound of the last regular
   * bucket, but implicitly the lower exclusive bound of the +Inf bucket.
   * </pre>
   *
   * <code>repeated double custom_values = 16;</code>
   * @return A list containing the customValues.
   */
  java.util.List<java.lang.Double> getCustomValuesList();
  /**
   * <pre>
   * custom_values is an additional field used by non-exponential bucketing layouts.
   *
   * For custom buckets (-53 schema value) custom_values specify monotonically
   * increasing upper inclusive boundaries for the bucket counts with arbitrary
   * widths for this histogram. In other words, custom_values represents custom,
   * explicit bucketing that could have been converted from the classic histograms.
   *
   * Those bounds are then referenced by spans in positive_spans with corresponding positive
   * counts of deltas (refer to positive_spans for more details). This way we can
   * have encode sparse histograms with custom bucketing (many buckets are often
   * not used).
   *
   * Note that for custom bounds, even negative observations are placed in the positive
   * counts to simplify the implementation and avoid ambiguity of where to place
   * an underflow bucket, e.g. (-2, 1]. Therefore negative buckets and
   * the zero bucket are unused, if the schema indicates custom bucketing.
   *
   * For each upper boundary the previous boundary represent the lower exclusive
   * boundary for that bucket. The first element is the upper inclusive boundary
   * for the first bucket, which implicitly has a lower inclusive bound of -Inf.
   * This is similar to "le" label semantics on classic histograms. You may add a
   * bucket with an upper bound of 0 to make sure that you really have no negative
   * observations, but in practice, native histogram rendering will show both with
   * or without first upper boundary 0 and no negative counts as the same case.
   *
   * The last element is not only the upper inclusive bound of the last regular
   * bucket, but implicitly the lower exclusive bound of the +Inf bucket.
   * </pre>
   *
   * <code>repeated double custom_values = 16;</code>
   * @return The count of customValues.
   */
  int getCustomValuesCount();
  /**
   * <pre>
   * custom_values is an additional field used by non-exponential bucketing layouts.
   *
   * For custom buckets (-53 schema value) custom_values specify monotonically
   * increasing upper inclusive boundaries for the bucket counts with arbitrary
   * widths for this histogram. In other words, custom_values represents custom,
   * explicit bucketing that could have been converted from the classic histograms.
   *
   * Those bounds are then referenced by spans in positive_spans with corresponding positive
   * counts of deltas (refer to positive_spans for more details). This way we can
   * have encode sparse histograms with custom bucketing (many buckets are often
   * not used).
   *
   * Note that for custom bounds, even negative observations are placed in the positive
   * counts to simplify the implementation and avoid ambiguity of where to place
   * an underflow bucket, e.g. (-2, 1]. Therefore negative buckets and
   * the zero bucket are unused, if the schema indicates custom bucketing.
   *
   * For each upper boundary the previous boundary represent the lower exclusive
   * boundary for that bucket. The first element is the upper inclusive boundary
   * for the first bucket, which implicitly has a lower inclusive bound of -Inf.
   * This is similar to "le" label semantics on classic histograms. You may add a
   * bucket with an upper bound of 0 to make sure that you really have no negative
   * observations, but in practice, native histogram rendering will show both with
   * or without first upper boundary 0 and no negative counts as the same case.
   *
   * The last element is not only the upper inclusive bound of the last regular
   * bucket, but implicitly the lower exclusive bound of the +Inf bucket.
   * </pre>
   *
   * <code>repeated double custom_values = 16;</code>
   * @param index The index of the element to return.
   * @return The customValues at the given index.
   */
  double getCustomValues(int index);

  cn.ecosync.aiot.data.apiserver.api.prometheus.Histogram.CountCase getCountCase();

  cn.ecosync.aiot.data.apiserver.api.prometheus.Histogram.ZeroCountCase getZeroCountCase();
}
