// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: types.proto
// Protobuf Java Version: 4.30.0

package cn.ecosync.aiot.data.apiserver.api.prometheus;

public interface MetadataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:io.prometheus.write.v2.Metadata)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.io.prometheus.write.v2.Metadata.MetricType type = 1;</code>
   * @return The enum numeric value on the wire for type.
   */
  int getTypeValue();
  /**
   * <code>.io.prometheus.write.v2.Metadata.MetricType type = 1;</code>
   * @return The type.
   */
  cn.ecosync.aiot.data.apiserver.api.prometheus.Metadata.MetricType getType();

  /**
   * <pre>
   * help_ref is a reference to the Request.symbols array representing help
   * text for the metric. Help is optional, reference should point to an empty string in
   * such a case.
   * </pre>
   *
   * <code>uint32 help_ref = 3;</code>
   * @return The helpRef.
   */
  int getHelpRef();

  /**
   * <pre>
   * unit_ref is a reference to the Request.symbols array representing a unit
   * for the metric. Unit is optional, reference should point to an empty string in
   * such a case.
   * </pre>
   *
   * <code>uint32 unit_ref = 4;</code>
   * @return The unitRef.
   */
  int getUnitRef();
}
