// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: types.proto
// Protobuf Java Version: 4.30.0

package cn.ecosync.aiot.data.apiserver.api.prometheus;

/**
 * <pre>
 * Metadata represents the metadata associated with the given series' samples.
 * </pre>
 *
 * Protobuf type {@code io.prometheus.write.v2.Metadata}
 */
public final class Metadata extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:io.prometheus.write.v2.Metadata)
    MetadataOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 30,
      /* patch= */ 0,
      /* suffix= */ "",
      Metadata.class.getName());
  }
  // Use Metadata.newBuilder() to construct.
  private Metadata(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private Metadata() {
    type_ = 0;
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return cn.ecosync.aiot.data.apiserver.api.prometheus.PrometheusProto.internal_static_io_prometheus_write_v2_Metadata_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return cn.ecosync.aiot.data.apiserver.api.prometheus.PrometheusProto.internal_static_io_prometheus_write_v2_Metadata_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            cn.ecosync.aiot.data.apiserver.api.prometheus.Metadata.class, cn.ecosync.aiot.data.apiserver.api.prometheus.Metadata.Builder.class);
  }

  /**
   * Protobuf enum {@code io.prometheus.write.v2.Metadata.MetricType}
   */
  public enum MetricType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>METRIC_TYPE_UNSPECIFIED = 0;</code>
     */
    METRIC_TYPE_UNSPECIFIED(0),
    /**
     * <code>METRIC_TYPE_COUNTER = 1;</code>
     */
    METRIC_TYPE_COUNTER(1),
    /**
     * <code>METRIC_TYPE_GAUGE = 2;</code>
     */
    METRIC_TYPE_GAUGE(2),
    /**
     * <code>METRIC_TYPE_HISTOGRAM = 3;</code>
     */
    METRIC_TYPE_HISTOGRAM(3),
    /**
     * <code>METRIC_TYPE_GAUGEHISTOGRAM = 4;</code>
     */
    METRIC_TYPE_GAUGEHISTOGRAM(4),
    /**
     * <code>METRIC_TYPE_SUMMARY = 5;</code>
     */
    METRIC_TYPE_SUMMARY(5),
    /**
     * <code>METRIC_TYPE_INFO = 6;</code>
     */
    METRIC_TYPE_INFO(6),
    /**
     * <code>METRIC_TYPE_STATESET = 7;</code>
     */
    METRIC_TYPE_STATESET(7),
    UNRECOGNIZED(-1),
    ;

    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 30,
        /* patch= */ 0,
        /* suffix= */ "",
        MetricType.class.getName());
    }
    /**
     * <code>METRIC_TYPE_UNSPECIFIED = 0;</code>
     */
    public static final int METRIC_TYPE_UNSPECIFIED_VALUE = 0;
    /**
     * <code>METRIC_TYPE_COUNTER = 1;</code>
     */
    public static final int METRIC_TYPE_COUNTER_VALUE = 1;
    /**
     * <code>METRIC_TYPE_GAUGE = 2;</code>
     */
    public static final int METRIC_TYPE_GAUGE_VALUE = 2;
    /**
     * <code>METRIC_TYPE_HISTOGRAM = 3;</code>
     */
    public static final int METRIC_TYPE_HISTOGRAM_VALUE = 3;
    /**
     * <code>METRIC_TYPE_GAUGEHISTOGRAM = 4;</code>
     */
    public static final int METRIC_TYPE_GAUGEHISTOGRAM_VALUE = 4;
    /**
     * <code>METRIC_TYPE_SUMMARY = 5;</code>
     */
    public static final int METRIC_TYPE_SUMMARY_VALUE = 5;
    /**
     * <code>METRIC_TYPE_INFO = 6;</code>
     */
    public static final int METRIC_TYPE_INFO_VALUE = 6;
    /**
     * <code>METRIC_TYPE_STATESET = 7;</code>
     */
    public static final int METRIC_TYPE_STATESET_VALUE = 7;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static MetricType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static MetricType forNumber(int value) {
      switch (value) {
        case 0: return METRIC_TYPE_UNSPECIFIED;
        case 1: return METRIC_TYPE_COUNTER;
        case 2: return METRIC_TYPE_GAUGE;
        case 3: return METRIC_TYPE_HISTOGRAM;
        case 4: return METRIC_TYPE_GAUGEHISTOGRAM;
        case 5: return METRIC_TYPE_SUMMARY;
        case 6: return METRIC_TYPE_INFO;
        case 7: return METRIC_TYPE_STATESET;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<MetricType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        MetricType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<MetricType>() {
            public MetricType findValueByNumber(int number) {
              return MetricType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return cn.ecosync.aiot.data.apiserver.api.prometheus.Metadata.getDescriptor().getEnumTypes().get(0);
    }

    private static final MetricType[] VALUES = values();

    public static MetricType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private MetricType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:io.prometheus.write.v2.Metadata.MetricType)
  }

  public static final int TYPE_FIELD_NUMBER = 1;
  private int type_ = 0;
  /**
   * <code>.io.prometheus.write.v2.Metadata.MetricType type = 1;</code>
   * @return The enum numeric value on the wire for type.
   */
  @java.lang.Override public int getTypeValue() {
    return type_;
  }
  /**
   * <code>.io.prometheus.write.v2.Metadata.MetricType type = 1;</code>
   * @return The type.
   */
  @java.lang.Override public cn.ecosync.aiot.data.apiserver.api.prometheus.Metadata.MetricType getType() {
    cn.ecosync.aiot.data.apiserver.api.prometheus.Metadata.MetricType result = cn.ecosync.aiot.data.apiserver.api.prometheus.Metadata.MetricType.forNumber(type_);
    return result == null ? cn.ecosync.aiot.data.apiserver.api.prometheus.Metadata.MetricType.UNRECOGNIZED : result;
  }

  public static final int HELP_REF_FIELD_NUMBER = 3;
  private int helpRef_ = 0;
  /**
   * <pre>
   * help_ref is a reference to the Request.symbols array representing help
   * text for the metric. Help is optional, reference should point to an empty string in
   * such a case.
   * </pre>
   *
   * <code>uint32 help_ref = 3;</code>
   * @return The helpRef.
   */
  @java.lang.Override
  public int getHelpRef() {
    return helpRef_;
  }

  public static final int UNIT_REF_FIELD_NUMBER = 4;
  private int unitRef_ = 0;
  /**
   * <pre>
   * unit_ref is a reference to the Request.symbols array representing a unit
   * for the metric. Unit is optional, reference should point to an empty string in
   * such a case.
   * </pre>
   *
   * <code>uint32 unit_ref = 4;</code>
   * @return The unitRef.
   */
  @java.lang.Override
  public int getUnitRef() {
    return unitRef_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (type_ != cn.ecosync.aiot.data.apiserver.api.prometheus.Metadata.MetricType.METRIC_TYPE_UNSPECIFIED.getNumber()) {
      output.writeEnum(1, type_);
    }
    if (helpRef_ != 0) {
      output.writeUInt32(3, helpRef_);
    }
    if (unitRef_ != 0) {
      output.writeUInt32(4, unitRef_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (type_ != cn.ecosync.aiot.data.apiserver.api.prometheus.Metadata.MetricType.METRIC_TYPE_UNSPECIFIED.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, type_);
    }
    if (helpRef_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(3, helpRef_);
    }
    if (unitRef_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(4, unitRef_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof cn.ecosync.aiot.data.apiserver.api.prometheus.Metadata)) {
      return super.equals(obj);
    }
    cn.ecosync.aiot.data.apiserver.api.prometheus.Metadata other = (cn.ecosync.aiot.data.apiserver.api.prometheus.Metadata) obj;

    if (type_ != other.type_) return false;
    if (getHelpRef()
        != other.getHelpRef()) return false;
    if (getUnitRef()
        != other.getUnitRef()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TYPE_FIELD_NUMBER;
    hash = (53 * hash) + type_;
    hash = (37 * hash) + HELP_REF_FIELD_NUMBER;
    hash = (53 * hash) + getHelpRef();
    hash = (37 * hash) + UNIT_REF_FIELD_NUMBER;
    hash = (53 * hash) + getUnitRef();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static cn.ecosync.aiot.data.apiserver.api.prometheus.Metadata parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cn.ecosync.aiot.data.apiserver.api.prometheus.Metadata parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cn.ecosync.aiot.data.apiserver.api.prometheus.Metadata parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cn.ecosync.aiot.data.apiserver.api.prometheus.Metadata parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cn.ecosync.aiot.data.apiserver.api.prometheus.Metadata parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cn.ecosync.aiot.data.apiserver.api.prometheus.Metadata parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cn.ecosync.aiot.data.apiserver.api.prometheus.Metadata parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static cn.ecosync.aiot.data.apiserver.api.prometheus.Metadata parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static cn.ecosync.aiot.data.apiserver.api.prometheus.Metadata parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static cn.ecosync.aiot.data.apiserver.api.prometheus.Metadata parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static cn.ecosync.aiot.data.apiserver.api.prometheus.Metadata parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static cn.ecosync.aiot.data.apiserver.api.prometheus.Metadata parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(cn.ecosync.aiot.data.apiserver.api.prometheus.Metadata prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Metadata represents the metadata associated with the given series' samples.
   * </pre>
   *
   * Protobuf type {@code io.prometheus.write.v2.Metadata}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:io.prometheus.write.v2.Metadata)
      cn.ecosync.aiot.data.apiserver.api.prometheus.MetadataOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cn.ecosync.aiot.data.apiserver.api.prometheus.PrometheusProto.internal_static_io_prometheus_write_v2_Metadata_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cn.ecosync.aiot.data.apiserver.api.prometheus.PrometheusProto.internal_static_io_prometheus_write_v2_Metadata_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cn.ecosync.aiot.data.apiserver.api.prometheus.Metadata.class, cn.ecosync.aiot.data.apiserver.api.prometheus.Metadata.Builder.class);
    }

    // Construct using cn.ecosync.aiot.data.apiserver.api.prometheus.Metadata.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      type_ = 0;
      helpRef_ = 0;
      unitRef_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return cn.ecosync.aiot.data.apiserver.api.prometheus.PrometheusProto.internal_static_io_prometheus_write_v2_Metadata_descriptor;
    }

    @java.lang.Override
    public cn.ecosync.aiot.data.apiserver.api.prometheus.Metadata getDefaultInstanceForType() {
      return cn.ecosync.aiot.data.apiserver.api.prometheus.Metadata.getDefaultInstance();
    }

    @java.lang.Override
    public cn.ecosync.aiot.data.apiserver.api.prometheus.Metadata build() {
      cn.ecosync.aiot.data.apiserver.api.prometheus.Metadata result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public cn.ecosync.aiot.data.apiserver.api.prometheus.Metadata buildPartial() {
      cn.ecosync.aiot.data.apiserver.api.prometheus.Metadata result = new cn.ecosync.aiot.data.apiserver.api.prometheus.Metadata(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(cn.ecosync.aiot.data.apiserver.api.prometheus.Metadata result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.type_ = type_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.helpRef_ = helpRef_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.unitRef_ = unitRef_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof cn.ecosync.aiot.data.apiserver.api.prometheus.Metadata) {
        return mergeFrom((cn.ecosync.aiot.data.apiserver.api.prometheus.Metadata)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(cn.ecosync.aiot.data.apiserver.api.prometheus.Metadata other) {
      if (other == cn.ecosync.aiot.data.apiserver.api.prometheus.Metadata.getDefaultInstance()) return this;
      if (other.type_ != 0) {
        setTypeValue(other.getTypeValue());
      }
      if (other.getHelpRef() != 0) {
        setHelpRef(other.getHelpRef());
      }
      if (other.getUnitRef() != 0) {
        setUnitRef(other.getUnitRef());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              type_ = input.readEnum();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 24: {
              helpRef_ = input.readUInt32();
              bitField0_ |= 0x00000002;
              break;
            } // case 24
            case 32: {
              unitRef_ = input.readUInt32();
              bitField0_ |= 0x00000004;
              break;
            } // case 32
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int type_ = 0;
    /**
     * <code>.io.prometheus.write.v2.Metadata.MetricType type = 1;</code>
     * @return The enum numeric value on the wire for type.
     */
    @java.lang.Override public int getTypeValue() {
      return type_;
    }
    /**
     * <code>.io.prometheus.write.v2.Metadata.MetricType type = 1;</code>
     * @param value The enum numeric value on the wire for type to set.
     * @return This builder for chaining.
     */
    public Builder setTypeValue(int value) {
      type_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.io.prometheus.write.v2.Metadata.MetricType type = 1;</code>
     * @return The type.
     */
    @java.lang.Override
    public cn.ecosync.aiot.data.apiserver.api.prometheus.Metadata.MetricType getType() {
      cn.ecosync.aiot.data.apiserver.api.prometheus.Metadata.MetricType result = cn.ecosync.aiot.data.apiserver.api.prometheus.Metadata.MetricType.forNumber(type_);
      return result == null ? cn.ecosync.aiot.data.apiserver.api.prometheus.Metadata.MetricType.UNRECOGNIZED : result;
    }
    /**
     * <code>.io.prometheus.write.v2.Metadata.MetricType type = 1;</code>
     * @param value The type to set.
     * @return This builder for chaining.
     */
    public Builder setType(cn.ecosync.aiot.data.apiserver.api.prometheus.Metadata.MetricType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000001;
      type_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.io.prometheus.write.v2.Metadata.MetricType type = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearType() {
      bitField0_ = (bitField0_ & ~0x00000001);
      type_ = 0;
      onChanged();
      return this;
    }

    private int helpRef_ ;
    /**
     * <pre>
     * help_ref is a reference to the Request.symbols array representing help
     * text for the metric. Help is optional, reference should point to an empty string in
     * such a case.
     * </pre>
     *
     * <code>uint32 help_ref = 3;</code>
     * @return The helpRef.
     */
    @java.lang.Override
    public int getHelpRef() {
      return helpRef_;
    }
    /**
     * <pre>
     * help_ref is a reference to the Request.symbols array representing help
     * text for the metric. Help is optional, reference should point to an empty string in
     * such a case.
     * </pre>
     *
     * <code>uint32 help_ref = 3;</code>
     * @param value The helpRef to set.
     * @return This builder for chaining.
     */
    public Builder setHelpRef(int value) {

      helpRef_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * help_ref is a reference to the Request.symbols array representing help
     * text for the metric. Help is optional, reference should point to an empty string in
     * such a case.
     * </pre>
     *
     * <code>uint32 help_ref = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearHelpRef() {
      bitField0_ = (bitField0_ & ~0x00000002);
      helpRef_ = 0;
      onChanged();
      return this;
    }

    private int unitRef_ ;
    /**
     * <pre>
     * unit_ref is a reference to the Request.symbols array representing a unit
     * for the metric. Unit is optional, reference should point to an empty string in
     * such a case.
     * </pre>
     *
     * <code>uint32 unit_ref = 4;</code>
     * @return The unitRef.
     */
    @java.lang.Override
    public int getUnitRef() {
      return unitRef_;
    }
    /**
     * <pre>
     * unit_ref is a reference to the Request.symbols array representing a unit
     * for the metric. Unit is optional, reference should point to an empty string in
     * such a case.
     * </pre>
     *
     * <code>uint32 unit_ref = 4;</code>
     * @param value The unitRef to set.
     * @return This builder for chaining.
     */
    public Builder setUnitRef(int value) {

      unitRef_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * unit_ref is a reference to the Request.symbols array representing a unit
     * for the metric. Unit is optional, reference should point to an empty string in
     * such a case.
     * </pre>
     *
     * <code>uint32 unit_ref = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearUnitRef() {
      bitField0_ = (bitField0_ & ~0x00000004);
      unitRef_ = 0;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:io.prometheus.write.v2.Metadata)
  }

  // @@protoc_insertion_point(class_scope:io.prometheus.write.v2.Metadata)
  private static final cn.ecosync.aiot.data.apiserver.api.prometheus.Metadata DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new cn.ecosync.aiot.data.apiserver.api.prometheus.Metadata();
  }

  public static cn.ecosync.aiot.data.apiserver.api.prometheus.Metadata getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Metadata>
      PARSER = new com.google.protobuf.AbstractParser<Metadata>() {
    @java.lang.Override
    public Metadata parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Metadata> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Metadata> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public cn.ecosync.aiot.data.apiserver.api.prometheus.Metadata getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

