// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: types.proto
// Protobuf Java Version: 4.30.0

package cn.ecosync.aiot.data.apiserver.api.prometheus;

public final class PrometheusProto {
  private PrometheusProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 30,
      /* patch= */ 0,
      /* suffix= */ "",
      PrometheusProto.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_prometheus_write_v2_Request_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_io_prometheus_write_v2_Request_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_prometheus_write_v2_TimeSeries_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_io_prometheus_write_v2_TimeSeries_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_prometheus_write_v2_Exemplar_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_io_prometheus_write_v2_Exemplar_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_prometheus_write_v2_Sample_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_io_prometheus_write_v2_Sample_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_prometheus_write_v2_Metadata_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_io_prometheus_write_v2_Metadata_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_prometheus_write_v2_Histogram_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_io_prometheus_write_v2_Histogram_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_prometheus_write_v2_BucketSpan_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_io_prometheus_write_v2_BucketSpan_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013types.proto\022\026io.prometheus.write.v2\"X\n" +
      "\007Request\022\017\n\007symbols\030\004 \003(\t\0226\n\ntimeseries\030" +
      "\005 \003(\0132\".io.prometheus.write.v2.TimeSerie" +
      "sJ\004\010\001\020\004\"\215\002\n\nTimeSeries\022\023\n\013labels_refs\030\001 " +
      "\003(\r\022/\n\007samples\030\002 \003(\0132\036.io.prometheus.wri" +
      "te.v2.Sample\0225\n\nhistograms\030\003 \003(\0132!.io.pr" +
      "ometheus.write.v2.Histogram\0223\n\texemplars" +
      "\030\004 \003(\0132 .io.prometheus.write.v2.Exemplar" +
      "\0222\n\010metadata\030\005 \001(\0132 .io.prometheus.write" +
      ".v2.Metadata\022\031\n\021created_timestamp\030\006 \001(\003\"" +
      "A\n\010Exemplar\022\023\n\013labels_refs\030\001 \003(\r\022\r\n\005valu" +
      "e\030\002 \001(\001\022\021\n\ttimestamp\030\003 \001(\003\"*\n\006Sample\022\r\n\005" +
      "value\030\001 \001(\001\022\021\n\ttimestamp\030\002 \001(\003\"\311\002\n\010Metad" +
      "ata\0229\n\004type\030\001 \001(\0162+.io.prometheus.write." +
      "v2.Metadata.MetricType\022\020\n\010help_ref\030\003 \001(\r" +
      "\022\020\n\010unit_ref\030\004 \001(\r\"\335\001\n\nMetricType\022\033\n\027MET" +
      "RIC_TYPE_UNSPECIFIED\020\000\022\027\n\023METRIC_TYPE_CO" +
      "UNTER\020\001\022\025\n\021METRIC_TYPE_GAUGE\020\002\022\031\n\025METRIC" +
      "_TYPE_HISTOGRAM\020\003\022\036\n\032METRIC_TYPE_GAUGEHI" +
      "STOGRAM\020\004\022\027\n\023METRIC_TYPE_SUMMARY\020\005\022\024\n\020ME" +
      "TRIC_TYPE_INFO\020\006\022\030\n\024METRIC_TYPE_STATESET" +
      "\020\007\"\346\004\n\tHistogram\022\023\n\tcount_int\030\001 \001(\004H\000\022\025\n" +
      "\013count_float\030\002 \001(\001H\000\022\013\n\003sum\030\003 \001(\001\022\016\n\006sch" +
      "ema\030\004 \001(\021\022\026\n\016zero_threshold\030\005 \001(\001\022\030\n\016zer" +
      "o_count_int\030\006 \001(\004H\001\022\032\n\020zero_count_float\030" +
      "\007 \001(\001H\001\022:\n\016negative_spans\030\010 \003(\0132\".io.pro" +
      "metheus.write.v2.BucketSpan\022\027\n\017negative_" +
      "deltas\030\t \003(\022\022\027\n\017negative_counts\030\n \003(\001\022:\n" +
      "\016positive_spans\030\013 \003(\0132\".io.prometheus.wr" +
      "ite.v2.BucketSpan\022\027\n\017positive_deltas\030\014 \003" +
      "(\022\022\027\n\017positive_counts\030\r \003(\001\022?\n\nreset_hin" +
      "t\030\016 \001(\0162+.io.prometheus.write.v2.Histogr" +
      "am.ResetHint\022\021\n\ttimestamp\030\017 \001(\003\022\025\n\rcusto" +
      "m_values\030\020 \003(\001\"d\n\tResetHint\022\032\n\026RESET_HIN" +
      "T_UNSPECIFIED\020\000\022\022\n\016RESET_HINT_YES\020\001\022\021\n\rR" +
      "ESET_HINT_NO\020\002\022\024\n\020RESET_HINT_GAUGE\020\003B\007\n\005" +
      "countB\014\n\nzero_count\",\n\nBucketSpan\022\016\n\006off" +
      "set\030\001 \001(\021\022\016\n\006length\030\002 \001(\rBB\n-cn.ecosync." +
      "aiot.data.apiserver.api.prometheusB\017Prom" +
      "etheusProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_io_prometheus_write_v2_Request_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_io_prometheus_write_v2_Request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_io_prometheus_write_v2_Request_descriptor,
        new java.lang.String[] { "Symbols", "Timeseries", });
    internal_static_io_prometheus_write_v2_TimeSeries_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_io_prometheus_write_v2_TimeSeries_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_io_prometheus_write_v2_TimeSeries_descriptor,
        new java.lang.String[] { "LabelsRefs", "Samples", "Histograms", "Exemplars", "Metadata", "CreatedTimestamp", });
    internal_static_io_prometheus_write_v2_Exemplar_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_io_prometheus_write_v2_Exemplar_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_io_prometheus_write_v2_Exemplar_descriptor,
        new java.lang.String[] { "LabelsRefs", "Value", "Timestamp", });
    internal_static_io_prometheus_write_v2_Sample_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_io_prometheus_write_v2_Sample_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_io_prometheus_write_v2_Sample_descriptor,
        new java.lang.String[] { "Value", "Timestamp", });
    internal_static_io_prometheus_write_v2_Metadata_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_io_prometheus_write_v2_Metadata_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_io_prometheus_write_v2_Metadata_descriptor,
        new java.lang.String[] { "Type", "HelpRef", "UnitRef", });
    internal_static_io_prometheus_write_v2_Histogram_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_io_prometheus_write_v2_Histogram_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_io_prometheus_write_v2_Histogram_descriptor,
        new java.lang.String[] { "CountInt", "CountFloat", "Sum", "Schema", "ZeroThreshold", "ZeroCountInt", "ZeroCountFloat", "NegativeSpans", "NegativeDeltas", "NegativeCounts", "PositiveSpans", "PositiveDeltas", "PositiveCounts", "ResetHint", "Timestamp", "CustomValues", "Count", "ZeroCount", });
    internal_static_io_prometheus_write_v2_BucketSpan_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_io_prometheus_write_v2_BucketSpan_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_io_prometheus_write_v2_BucketSpan_descriptor,
        new java.lang.String[] { "Offset", "Length", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
