// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: types.proto
// Protobuf Java Version: 4.30.0

package cn.ecosync.aiot.data.apiserver.api.prometheus;

public interface RequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:io.prometheus.write.v2.Request)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * symbols contains a de-duplicated array of string elements used for various
   * items in a Request message, like labels and metadata items. For the sender's convenience
   * around empty values for optional fields like unit_ref, symbols array MUST start with
   * empty string.
   *
   * To decode each of the symbolized strings, referenced, by "ref(s)" suffix, you
   * need to lookup the actual string by index from symbols array. The order of
   * strings is up to the sender. The receiver should not assume any particular encoding.
   * </pre>
   *
   * <code>repeated string symbols = 4;</code>
   * @return A list containing the symbols.
   */
  java.util.List<java.lang.String>
      getSymbolsList();
  /**
   * <pre>
   * symbols contains a de-duplicated array of string elements used for various
   * items in a Request message, like labels and metadata items. For the sender's convenience
   * around empty values for optional fields like unit_ref, symbols array MUST start with
   * empty string.
   *
   * To decode each of the symbolized strings, referenced, by "ref(s)" suffix, you
   * need to lookup the actual string by index from symbols array. The order of
   * strings is up to the sender. The receiver should not assume any particular encoding.
   * </pre>
   *
   * <code>repeated string symbols = 4;</code>
   * @return The count of symbols.
   */
  int getSymbolsCount();
  /**
   * <pre>
   * symbols contains a de-duplicated array of string elements used for various
   * items in a Request message, like labels and metadata items. For the sender's convenience
   * around empty values for optional fields like unit_ref, symbols array MUST start with
   * empty string.
   *
   * To decode each of the symbolized strings, referenced, by "ref(s)" suffix, you
   * need to lookup the actual string by index from symbols array. The order of
   * strings is up to the sender. The receiver should not assume any particular encoding.
   * </pre>
   *
   * <code>repeated string symbols = 4;</code>
   * @param index The index of the element to return.
   * @return The symbols at the given index.
   */
  java.lang.String getSymbols(int index);
  /**
   * <pre>
   * symbols contains a de-duplicated array of string elements used for various
   * items in a Request message, like labels and metadata items. For the sender's convenience
   * around empty values for optional fields like unit_ref, symbols array MUST start with
   * empty string.
   *
   * To decode each of the symbolized strings, referenced, by "ref(s)" suffix, you
   * need to lookup the actual string by index from symbols array. The order of
   * strings is up to the sender. The receiver should not assume any particular encoding.
   * </pre>
   *
   * <code>repeated string symbols = 4;</code>
   * @param index The index of the value to return.
   * @return The bytes of the symbols at the given index.
   */
  com.google.protobuf.ByteString
      getSymbolsBytes(int index);

  /**
   * <pre>
   * timeseries represents an array of distinct series with 0 or more samples.
   * </pre>
   *
   * <code>repeated .io.prometheus.write.v2.TimeSeries timeseries = 5;</code>
   */
  java.util.List<cn.ecosync.aiot.data.apiserver.api.prometheus.TimeSeries> 
      getTimeseriesList();
  /**
   * <pre>
   * timeseries represents an array of distinct series with 0 or more samples.
   * </pre>
   *
   * <code>repeated .io.prometheus.write.v2.TimeSeries timeseries = 5;</code>
   */
  cn.ecosync.aiot.data.apiserver.api.prometheus.TimeSeries getTimeseries(int index);
  /**
   * <pre>
   * timeseries represents an array of distinct series with 0 or more samples.
   * </pre>
   *
   * <code>repeated .io.prometheus.write.v2.TimeSeries timeseries = 5;</code>
   */
  int getTimeseriesCount();
  /**
   * <pre>
   * timeseries represents an array of distinct series with 0 or more samples.
   * </pre>
   *
   * <code>repeated .io.prometheus.write.v2.TimeSeries timeseries = 5;</code>
   */
  java.util.List<? extends cn.ecosync.aiot.data.apiserver.api.prometheus.TimeSeriesOrBuilder> 
      getTimeseriesOrBuilderList();
  /**
   * <pre>
   * timeseries represents an array of distinct series with 0 or more samples.
   * </pre>
   *
   * <code>repeated .io.prometheus.write.v2.TimeSeries timeseries = 5;</code>
   */
  cn.ecosync.aiot.data.apiserver.api.prometheus.TimeSeriesOrBuilder getTimeseriesOrBuilder(
      int index);
}
