// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: types.proto
// Protobuf Java Version: 4.30.0

package cn.ecosync.aiot.data.apiserver.api.prometheus;

/**
 * <pre>
 * Request represents a request to write the given timeseries to a remote destination.
 * This message was introduced in the Remote Write 2.0 specification:
 * https://prometheus.io/docs/concepts/remote_write_spec_2_0/
 *
 * The canonical Content-Type request header value for this message is
 * "application/x-protobuf;proto=io.prometheus.write.v2.Request"
 *
 * NOTE: gogoproto options might change in future for this file, they
 * are not part of the spec proto (they only modify the generated Go code, not
 * the serialized message). See: https://github.com/prometheus/prometheus/issues/11908
 * </pre>
 *
 * Protobuf type {@code io.prometheus.write.v2.Request}
 */
public final class Request extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:io.prometheus.write.v2.Request)
    RequestOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 30,
      /* patch= */ 0,
      /* suffix= */ "",
      Request.class.getName());
  }
  // Use Request.newBuilder() to construct.
  private Request(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private Request() {
    symbols_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    timeseries_ = java.util.Collections.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return cn.ecosync.aiot.data.apiserver.api.prometheus.PrometheusProto.internal_static_io_prometheus_write_v2_Request_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return cn.ecosync.aiot.data.apiserver.api.prometheus.PrometheusProto.internal_static_io_prometheus_write_v2_Request_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            cn.ecosync.aiot.data.apiserver.api.prometheus.Request.class, cn.ecosync.aiot.data.apiserver.api.prometheus.Request.Builder.class);
  }

  public static final int SYMBOLS_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private com.google.protobuf.LazyStringArrayList symbols_ =
      com.google.protobuf.LazyStringArrayList.emptyList();
  /**
   * <pre>
   * symbols contains a de-duplicated array of string elements used for various
   * items in a Request message, like labels and metadata items. For the sender's convenience
   * around empty values for optional fields like unit_ref, symbols array MUST start with
   * empty string.
   *
   * To decode each of the symbolized strings, referenced, by "ref(s)" suffix, you
   * need to lookup the actual string by index from symbols array. The order of
   * strings is up to the sender. The receiver should not assume any particular encoding.
   * </pre>
   *
   * <code>repeated string symbols = 4;</code>
   * @return A list containing the symbols.
   */
  public com.google.protobuf.ProtocolStringList
      getSymbolsList() {
    return symbols_;
  }
  /**
   * <pre>
   * symbols contains a de-duplicated array of string elements used for various
   * items in a Request message, like labels and metadata items. For the sender's convenience
   * around empty values for optional fields like unit_ref, symbols array MUST start with
   * empty string.
   *
   * To decode each of the symbolized strings, referenced, by "ref(s)" suffix, you
   * need to lookup the actual string by index from symbols array. The order of
   * strings is up to the sender. The receiver should not assume any particular encoding.
   * </pre>
   *
   * <code>repeated string symbols = 4;</code>
   * @return The count of symbols.
   */
  public int getSymbolsCount() {
    return symbols_.size();
  }
  /**
   * <pre>
   * symbols contains a de-duplicated array of string elements used for various
   * items in a Request message, like labels and metadata items. For the sender's convenience
   * around empty values for optional fields like unit_ref, symbols array MUST start with
   * empty string.
   *
   * To decode each of the symbolized strings, referenced, by "ref(s)" suffix, you
   * need to lookup the actual string by index from symbols array. The order of
   * strings is up to the sender. The receiver should not assume any particular encoding.
   * </pre>
   *
   * <code>repeated string symbols = 4;</code>
   * @param index The index of the element to return.
   * @return The symbols at the given index.
   */
  public java.lang.String getSymbols(int index) {
    return symbols_.get(index);
  }
  /**
   * <pre>
   * symbols contains a de-duplicated array of string elements used for various
   * items in a Request message, like labels and metadata items. For the sender's convenience
   * around empty values for optional fields like unit_ref, symbols array MUST start with
   * empty string.
   *
   * To decode each of the symbolized strings, referenced, by "ref(s)" suffix, you
   * need to lookup the actual string by index from symbols array. The order of
   * strings is up to the sender. The receiver should not assume any particular encoding.
   * </pre>
   *
   * <code>repeated string symbols = 4;</code>
   * @param index The index of the value to return.
   * @return The bytes of the symbols at the given index.
   */
  public com.google.protobuf.ByteString
      getSymbolsBytes(int index) {
    return symbols_.getByteString(index);
  }

  public static final int TIMESERIES_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private java.util.List<cn.ecosync.aiot.data.apiserver.api.prometheus.TimeSeries> timeseries_;
  /**
   * <pre>
   * timeseries represents an array of distinct series with 0 or more samples.
   * </pre>
   *
   * <code>repeated .io.prometheus.write.v2.TimeSeries timeseries = 5;</code>
   */
  @java.lang.Override
  public java.util.List<cn.ecosync.aiot.data.apiserver.api.prometheus.TimeSeries> getTimeseriesList() {
    return timeseries_;
  }
  /**
   * <pre>
   * timeseries represents an array of distinct series with 0 or more samples.
   * </pre>
   *
   * <code>repeated .io.prometheus.write.v2.TimeSeries timeseries = 5;</code>
   */
  @java.lang.Override
  public java.util.List<? extends cn.ecosync.aiot.data.apiserver.api.prometheus.TimeSeriesOrBuilder> 
      getTimeseriesOrBuilderList() {
    return timeseries_;
  }
  /**
   * <pre>
   * timeseries represents an array of distinct series with 0 or more samples.
   * </pre>
   *
   * <code>repeated .io.prometheus.write.v2.TimeSeries timeseries = 5;</code>
   */
  @java.lang.Override
  public int getTimeseriesCount() {
    return timeseries_.size();
  }
  /**
   * <pre>
   * timeseries represents an array of distinct series with 0 or more samples.
   * </pre>
   *
   * <code>repeated .io.prometheus.write.v2.TimeSeries timeseries = 5;</code>
   */
  @java.lang.Override
  public cn.ecosync.aiot.data.apiserver.api.prometheus.TimeSeries getTimeseries(int index) {
    return timeseries_.get(index);
  }
  /**
   * <pre>
   * timeseries represents an array of distinct series with 0 or more samples.
   * </pre>
   *
   * <code>repeated .io.prometheus.write.v2.TimeSeries timeseries = 5;</code>
   */
  @java.lang.Override
  public cn.ecosync.aiot.data.apiserver.api.prometheus.TimeSeriesOrBuilder getTimeseriesOrBuilder(
      int index) {
    return timeseries_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < symbols_.size(); i++) {
      com.google.protobuf.GeneratedMessage.writeString(output, 4, symbols_.getRaw(i));
    }
    for (int i = 0; i < timeseries_.size(); i++) {
      output.writeMessage(5, timeseries_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    {
      int dataSize = 0;
      for (int i = 0; i < symbols_.size(); i++) {
        dataSize += computeStringSizeNoTag(symbols_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getSymbolsList().size();
    }
    for (int i = 0; i < timeseries_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, timeseries_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof cn.ecosync.aiot.data.apiserver.api.prometheus.Request)) {
      return super.equals(obj);
    }
    cn.ecosync.aiot.data.apiserver.api.prometheus.Request other = (cn.ecosync.aiot.data.apiserver.api.prometheus.Request) obj;

    if (!getSymbolsList()
        .equals(other.getSymbolsList())) return false;
    if (!getTimeseriesList()
        .equals(other.getTimeseriesList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getSymbolsCount() > 0) {
      hash = (37 * hash) + SYMBOLS_FIELD_NUMBER;
      hash = (53 * hash) + getSymbolsList().hashCode();
    }
    if (getTimeseriesCount() > 0) {
      hash = (37 * hash) + TIMESERIES_FIELD_NUMBER;
      hash = (53 * hash) + getTimeseriesList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static cn.ecosync.aiot.data.apiserver.api.prometheus.Request parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cn.ecosync.aiot.data.apiserver.api.prometheus.Request parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cn.ecosync.aiot.data.apiserver.api.prometheus.Request parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cn.ecosync.aiot.data.apiserver.api.prometheus.Request parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cn.ecosync.aiot.data.apiserver.api.prometheus.Request parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cn.ecosync.aiot.data.apiserver.api.prometheus.Request parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cn.ecosync.aiot.data.apiserver.api.prometheus.Request parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static cn.ecosync.aiot.data.apiserver.api.prometheus.Request parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static cn.ecosync.aiot.data.apiserver.api.prometheus.Request parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static cn.ecosync.aiot.data.apiserver.api.prometheus.Request parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static cn.ecosync.aiot.data.apiserver.api.prometheus.Request parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static cn.ecosync.aiot.data.apiserver.api.prometheus.Request parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(cn.ecosync.aiot.data.apiserver.api.prometheus.Request prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Request represents a request to write the given timeseries to a remote destination.
   * This message was introduced in the Remote Write 2.0 specification:
   * https://prometheus.io/docs/concepts/remote_write_spec_2_0/
   *
   * The canonical Content-Type request header value for this message is
   * "application/x-protobuf;proto=io.prometheus.write.v2.Request"
   *
   * NOTE: gogoproto options might change in future for this file, they
   * are not part of the spec proto (they only modify the generated Go code, not
   * the serialized message). See: https://github.com/prometheus/prometheus/issues/11908
   * </pre>
   *
   * Protobuf type {@code io.prometheus.write.v2.Request}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:io.prometheus.write.v2.Request)
      cn.ecosync.aiot.data.apiserver.api.prometheus.RequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cn.ecosync.aiot.data.apiserver.api.prometheus.PrometheusProto.internal_static_io_prometheus_write_v2_Request_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cn.ecosync.aiot.data.apiserver.api.prometheus.PrometheusProto.internal_static_io_prometheus_write_v2_Request_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cn.ecosync.aiot.data.apiserver.api.prometheus.Request.class, cn.ecosync.aiot.data.apiserver.api.prometheus.Request.Builder.class);
    }

    // Construct using cn.ecosync.aiot.data.apiserver.api.prometheus.Request.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      symbols_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      if (timeseriesBuilder_ == null) {
        timeseries_ = java.util.Collections.emptyList();
      } else {
        timeseries_ = null;
        timeseriesBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000002);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return cn.ecosync.aiot.data.apiserver.api.prometheus.PrometheusProto.internal_static_io_prometheus_write_v2_Request_descriptor;
    }

    @java.lang.Override
    public cn.ecosync.aiot.data.apiserver.api.prometheus.Request getDefaultInstanceForType() {
      return cn.ecosync.aiot.data.apiserver.api.prometheus.Request.getDefaultInstance();
    }

    @java.lang.Override
    public cn.ecosync.aiot.data.apiserver.api.prometheus.Request build() {
      cn.ecosync.aiot.data.apiserver.api.prometheus.Request result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public cn.ecosync.aiot.data.apiserver.api.prometheus.Request buildPartial() {
      cn.ecosync.aiot.data.apiserver.api.prometheus.Request result = new cn.ecosync.aiot.data.apiserver.api.prometheus.Request(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(cn.ecosync.aiot.data.apiserver.api.prometheus.Request result) {
      if (timeseriesBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0)) {
          timeseries_ = java.util.Collections.unmodifiableList(timeseries_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.timeseries_ = timeseries_;
      } else {
        result.timeseries_ = timeseriesBuilder_.build();
      }
    }

    private void buildPartial0(cn.ecosync.aiot.data.apiserver.api.prometheus.Request result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        symbols_.makeImmutable();
        result.symbols_ = symbols_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof cn.ecosync.aiot.data.apiserver.api.prometheus.Request) {
        return mergeFrom((cn.ecosync.aiot.data.apiserver.api.prometheus.Request)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(cn.ecosync.aiot.data.apiserver.api.prometheus.Request other) {
      if (other == cn.ecosync.aiot.data.apiserver.api.prometheus.Request.getDefaultInstance()) return this;
      if (!other.symbols_.isEmpty()) {
        if (symbols_.isEmpty()) {
          symbols_ = other.symbols_;
          bitField0_ |= 0x00000001;
        } else {
          ensureSymbolsIsMutable();
          symbols_.addAll(other.symbols_);
        }
        onChanged();
      }
      if (timeseriesBuilder_ == null) {
        if (!other.timeseries_.isEmpty()) {
          if (timeseries_.isEmpty()) {
            timeseries_ = other.timeseries_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureTimeseriesIsMutable();
            timeseries_.addAll(other.timeseries_);
          }
          onChanged();
        }
      } else {
        if (!other.timeseries_.isEmpty()) {
          if (timeseriesBuilder_.isEmpty()) {
            timeseriesBuilder_.dispose();
            timeseriesBuilder_ = null;
            timeseries_ = other.timeseries_;
            bitField0_ = (bitField0_ & ~0x00000002);
            timeseriesBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 internalGetTimeseriesFieldBuilder() : null;
          } else {
            timeseriesBuilder_.addAllMessages(other.timeseries_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();
              ensureSymbolsIsMutable();
              symbols_.add(s);
              break;
            } // case 34
            case 42: {
              cn.ecosync.aiot.data.apiserver.api.prometheus.TimeSeries m =
                  input.readMessage(
                      cn.ecosync.aiot.data.apiserver.api.prometheus.TimeSeries.parser(),
                      extensionRegistry);
              if (timeseriesBuilder_ == null) {
                ensureTimeseriesIsMutable();
                timeseries_.add(m);
              } else {
                timeseriesBuilder_.addMessage(m);
              }
              break;
            } // case 42
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.LazyStringArrayList symbols_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    private void ensureSymbolsIsMutable() {
      if (!symbols_.isModifiable()) {
        symbols_ = new com.google.protobuf.LazyStringArrayList(symbols_);
      }
      bitField0_ |= 0x00000001;
    }
    /**
     * <pre>
     * symbols contains a de-duplicated array of string elements used for various
     * items in a Request message, like labels and metadata items. For the sender's convenience
     * around empty values for optional fields like unit_ref, symbols array MUST start with
     * empty string.
     *
     * To decode each of the symbolized strings, referenced, by "ref(s)" suffix, you
     * need to lookup the actual string by index from symbols array. The order of
     * strings is up to the sender. The receiver should not assume any particular encoding.
     * </pre>
     *
     * <code>repeated string symbols = 4;</code>
     * @return A list containing the symbols.
     */
    public com.google.protobuf.ProtocolStringList
        getSymbolsList() {
      symbols_.makeImmutable();
      return symbols_;
    }
    /**
     * <pre>
     * symbols contains a de-duplicated array of string elements used for various
     * items in a Request message, like labels and metadata items. For the sender's convenience
     * around empty values for optional fields like unit_ref, symbols array MUST start with
     * empty string.
     *
     * To decode each of the symbolized strings, referenced, by "ref(s)" suffix, you
     * need to lookup the actual string by index from symbols array. The order of
     * strings is up to the sender. The receiver should not assume any particular encoding.
     * </pre>
     *
     * <code>repeated string symbols = 4;</code>
     * @return The count of symbols.
     */
    public int getSymbolsCount() {
      return symbols_.size();
    }
    /**
     * <pre>
     * symbols contains a de-duplicated array of string elements used for various
     * items in a Request message, like labels and metadata items. For the sender's convenience
     * around empty values for optional fields like unit_ref, symbols array MUST start with
     * empty string.
     *
     * To decode each of the symbolized strings, referenced, by "ref(s)" suffix, you
     * need to lookup the actual string by index from symbols array. The order of
     * strings is up to the sender. The receiver should not assume any particular encoding.
     * </pre>
     *
     * <code>repeated string symbols = 4;</code>
     * @param index The index of the element to return.
     * @return The symbols at the given index.
     */
    public java.lang.String getSymbols(int index) {
      return symbols_.get(index);
    }
    /**
     * <pre>
     * symbols contains a de-duplicated array of string elements used for various
     * items in a Request message, like labels and metadata items. For the sender's convenience
     * around empty values for optional fields like unit_ref, symbols array MUST start with
     * empty string.
     *
     * To decode each of the symbolized strings, referenced, by "ref(s)" suffix, you
     * need to lookup the actual string by index from symbols array. The order of
     * strings is up to the sender. The receiver should not assume any particular encoding.
     * </pre>
     *
     * <code>repeated string symbols = 4;</code>
     * @param index The index of the value to return.
     * @return The bytes of the symbols at the given index.
     */
    public com.google.protobuf.ByteString
        getSymbolsBytes(int index) {
      return symbols_.getByteString(index);
    }
    /**
     * <pre>
     * symbols contains a de-duplicated array of string elements used for various
     * items in a Request message, like labels and metadata items. For the sender's convenience
     * around empty values for optional fields like unit_ref, symbols array MUST start with
     * empty string.
     *
     * To decode each of the symbolized strings, referenced, by "ref(s)" suffix, you
     * need to lookup the actual string by index from symbols array. The order of
     * strings is up to the sender. The receiver should not assume any particular encoding.
     * </pre>
     *
     * <code>repeated string symbols = 4;</code>
     * @param index The index to set the value at.
     * @param value The symbols to set.
     * @return This builder for chaining.
     */
    public Builder setSymbols(
        int index, java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureSymbolsIsMutable();
      symbols_.set(index, value);
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * symbols contains a de-duplicated array of string elements used for various
     * items in a Request message, like labels and metadata items. For the sender's convenience
     * around empty values for optional fields like unit_ref, symbols array MUST start with
     * empty string.
     *
     * To decode each of the symbolized strings, referenced, by "ref(s)" suffix, you
     * need to lookup the actual string by index from symbols array. The order of
     * strings is up to the sender. The receiver should not assume any particular encoding.
     * </pre>
     *
     * <code>repeated string symbols = 4;</code>
     * @param value The symbols to add.
     * @return This builder for chaining.
     */
    public Builder addSymbols(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureSymbolsIsMutable();
      symbols_.add(value);
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * symbols contains a de-duplicated array of string elements used for various
     * items in a Request message, like labels and metadata items. For the sender's convenience
     * around empty values for optional fields like unit_ref, symbols array MUST start with
     * empty string.
     *
     * To decode each of the symbolized strings, referenced, by "ref(s)" suffix, you
     * need to lookup the actual string by index from symbols array. The order of
     * strings is up to the sender. The receiver should not assume any particular encoding.
     * </pre>
     *
     * <code>repeated string symbols = 4;</code>
     * @param values The symbols to add.
     * @return This builder for chaining.
     */
    public Builder addAllSymbols(
        java.lang.Iterable<java.lang.String> values) {
      ensureSymbolsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, symbols_);
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * symbols contains a de-duplicated array of string elements used for various
     * items in a Request message, like labels and metadata items. For the sender's convenience
     * around empty values for optional fields like unit_ref, symbols array MUST start with
     * empty string.
     *
     * To decode each of the symbolized strings, referenced, by "ref(s)" suffix, you
     * need to lookup the actual string by index from symbols array. The order of
     * strings is up to the sender. The receiver should not assume any particular encoding.
     * </pre>
     *
     * <code>repeated string symbols = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearSymbols() {
      symbols_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
      bitField0_ = (bitField0_ & ~0x00000001);;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * symbols contains a de-duplicated array of string elements used for various
     * items in a Request message, like labels and metadata items. For the sender's convenience
     * around empty values for optional fields like unit_ref, symbols array MUST start with
     * empty string.
     *
     * To decode each of the symbolized strings, referenced, by "ref(s)" suffix, you
     * need to lookup the actual string by index from symbols array. The order of
     * strings is up to the sender. The receiver should not assume any particular encoding.
     * </pre>
     *
     * <code>repeated string symbols = 4;</code>
     * @param value The bytes of the symbols to add.
     * @return This builder for chaining.
     */
    public Builder addSymbolsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      ensureSymbolsIsMutable();
      symbols_.add(value);
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.util.List<cn.ecosync.aiot.data.apiserver.api.prometheus.TimeSeries> timeseries_ =
      java.util.Collections.emptyList();
    private void ensureTimeseriesIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        timeseries_ = new java.util.ArrayList<cn.ecosync.aiot.data.apiserver.api.prometheus.TimeSeries>(timeseries_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        cn.ecosync.aiot.data.apiserver.api.prometheus.TimeSeries, cn.ecosync.aiot.data.apiserver.api.prometheus.TimeSeries.Builder, cn.ecosync.aiot.data.apiserver.api.prometheus.TimeSeriesOrBuilder> timeseriesBuilder_;

    /**
     * <pre>
     * timeseries represents an array of distinct series with 0 or more samples.
     * </pre>
     *
     * <code>repeated .io.prometheus.write.v2.TimeSeries timeseries = 5;</code>
     */
    public java.util.List<cn.ecosync.aiot.data.apiserver.api.prometheus.TimeSeries> getTimeseriesList() {
      if (timeseriesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(timeseries_);
      } else {
        return timeseriesBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * timeseries represents an array of distinct series with 0 or more samples.
     * </pre>
     *
     * <code>repeated .io.prometheus.write.v2.TimeSeries timeseries = 5;</code>
     */
    public int getTimeseriesCount() {
      if (timeseriesBuilder_ == null) {
        return timeseries_.size();
      } else {
        return timeseriesBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * timeseries represents an array of distinct series with 0 or more samples.
     * </pre>
     *
     * <code>repeated .io.prometheus.write.v2.TimeSeries timeseries = 5;</code>
     */
    public cn.ecosync.aiot.data.apiserver.api.prometheus.TimeSeries getTimeseries(int index) {
      if (timeseriesBuilder_ == null) {
        return timeseries_.get(index);
      } else {
        return timeseriesBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * timeseries represents an array of distinct series with 0 or more samples.
     * </pre>
     *
     * <code>repeated .io.prometheus.write.v2.TimeSeries timeseries = 5;</code>
     */
    public Builder setTimeseries(
        int index, cn.ecosync.aiot.data.apiserver.api.prometheus.TimeSeries value) {
      if (timeseriesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTimeseriesIsMutable();
        timeseries_.set(index, value);
        onChanged();
      } else {
        timeseriesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * timeseries represents an array of distinct series with 0 or more samples.
     * </pre>
     *
     * <code>repeated .io.prometheus.write.v2.TimeSeries timeseries = 5;</code>
     */
    public Builder setTimeseries(
        int index, cn.ecosync.aiot.data.apiserver.api.prometheus.TimeSeries.Builder builderForValue) {
      if (timeseriesBuilder_ == null) {
        ensureTimeseriesIsMutable();
        timeseries_.set(index, builderForValue.build());
        onChanged();
      } else {
        timeseriesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * timeseries represents an array of distinct series with 0 or more samples.
     * </pre>
     *
     * <code>repeated .io.prometheus.write.v2.TimeSeries timeseries = 5;</code>
     */
    public Builder addTimeseries(cn.ecosync.aiot.data.apiserver.api.prometheus.TimeSeries value) {
      if (timeseriesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTimeseriesIsMutable();
        timeseries_.add(value);
        onChanged();
      } else {
        timeseriesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * timeseries represents an array of distinct series with 0 or more samples.
     * </pre>
     *
     * <code>repeated .io.prometheus.write.v2.TimeSeries timeseries = 5;</code>
     */
    public Builder addTimeseries(
        int index, cn.ecosync.aiot.data.apiserver.api.prometheus.TimeSeries value) {
      if (timeseriesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTimeseriesIsMutable();
        timeseries_.add(index, value);
        onChanged();
      } else {
        timeseriesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * timeseries represents an array of distinct series with 0 or more samples.
     * </pre>
     *
     * <code>repeated .io.prometheus.write.v2.TimeSeries timeseries = 5;</code>
     */
    public Builder addTimeseries(
        cn.ecosync.aiot.data.apiserver.api.prometheus.TimeSeries.Builder builderForValue) {
      if (timeseriesBuilder_ == null) {
        ensureTimeseriesIsMutable();
        timeseries_.add(builderForValue.build());
        onChanged();
      } else {
        timeseriesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * timeseries represents an array of distinct series with 0 or more samples.
     * </pre>
     *
     * <code>repeated .io.prometheus.write.v2.TimeSeries timeseries = 5;</code>
     */
    public Builder addTimeseries(
        int index, cn.ecosync.aiot.data.apiserver.api.prometheus.TimeSeries.Builder builderForValue) {
      if (timeseriesBuilder_ == null) {
        ensureTimeseriesIsMutable();
        timeseries_.add(index, builderForValue.build());
        onChanged();
      } else {
        timeseriesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * timeseries represents an array of distinct series with 0 or more samples.
     * </pre>
     *
     * <code>repeated .io.prometheus.write.v2.TimeSeries timeseries = 5;</code>
     */
    public Builder addAllTimeseries(
        java.lang.Iterable<? extends cn.ecosync.aiot.data.apiserver.api.prometheus.TimeSeries> values) {
      if (timeseriesBuilder_ == null) {
        ensureTimeseriesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, timeseries_);
        onChanged();
      } else {
        timeseriesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * timeseries represents an array of distinct series with 0 or more samples.
     * </pre>
     *
     * <code>repeated .io.prometheus.write.v2.TimeSeries timeseries = 5;</code>
     */
    public Builder clearTimeseries() {
      if (timeseriesBuilder_ == null) {
        timeseries_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        timeseriesBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * timeseries represents an array of distinct series with 0 or more samples.
     * </pre>
     *
     * <code>repeated .io.prometheus.write.v2.TimeSeries timeseries = 5;</code>
     */
    public Builder removeTimeseries(int index) {
      if (timeseriesBuilder_ == null) {
        ensureTimeseriesIsMutable();
        timeseries_.remove(index);
        onChanged();
      } else {
        timeseriesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * timeseries represents an array of distinct series with 0 or more samples.
     * </pre>
     *
     * <code>repeated .io.prometheus.write.v2.TimeSeries timeseries = 5;</code>
     */
    public cn.ecosync.aiot.data.apiserver.api.prometheus.TimeSeries.Builder getTimeseriesBuilder(
        int index) {
      return internalGetTimeseriesFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * timeseries represents an array of distinct series with 0 or more samples.
     * </pre>
     *
     * <code>repeated .io.prometheus.write.v2.TimeSeries timeseries = 5;</code>
     */
    public cn.ecosync.aiot.data.apiserver.api.prometheus.TimeSeriesOrBuilder getTimeseriesOrBuilder(
        int index) {
      if (timeseriesBuilder_ == null) {
        return timeseries_.get(index);  } else {
        return timeseriesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * timeseries represents an array of distinct series with 0 or more samples.
     * </pre>
     *
     * <code>repeated .io.prometheus.write.v2.TimeSeries timeseries = 5;</code>
     */
    public java.util.List<? extends cn.ecosync.aiot.data.apiserver.api.prometheus.TimeSeriesOrBuilder> 
         getTimeseriesOrBuilderList() {
      if (timeseriesBuilder_ != null) {
        return timeseriesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(timeseries_);
      }
    }
    /**
     * <pre>
     * timeseries represents an array of distinct series with 0 or more samples.
     * </pre>
     *
     * <code>repeated .io.prometheus.write.v2.TimeSeries timeseries = 5;</code>
     */
    public cn.ecosync.aiot.data.apiserver.api.prometheus.TimeSeries.Builder addTimeseriesBuilder() {
      return internalGetTimeseriesFieldBuilder().addBuilder(
          cn.ecosync.aiot.data.apiserver.api.prometheus.TimeSeries.getDefaultInstance());
    }
    /**
     * <pre>
     * timeseries represents an array of distinct series with 0 or more samples.
     * </pre>
     *
     * <code>repeated .io.prometheus.write.v2.TimeSeries timeseries = 5;</code>
     */
    public cn.ecosync.aiot.data.apiserver.api.prometheus.TimeSeries.Builder addTimeseriesBuilder(
        int index) {
      return internalGetTimeseriesFieldBuilder().addBuilder(
          index, cn.ecosync.aiot.data.apiserver.api.prometheus.TimeSeries.getDefaultInstance());
    }
    /**
     * <pre>
     * timeseries represents an array of distinct series with 0 or more samples.
     * </pre>
     *
     * <code>repeated .io.prometheus.write.v2.TimeSeries timeseries = 5;</code>
     */
    public java.util.List<cn.ecosync.aiot.data.apiserver.api.prometheus.TimeSeries.Builder> 
         getTimeseriesBuilderList() {
      return internalGetTimeseriesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        cn.ecosync.aiot.data.apiserver.api.prometheus.TimeSeries, cn.ecosync.aiot.data.apiserver.api.prometheus.TimeSeries.Builder, cn.ecosync.aiot.data.apiserver.api.prometheus.TimeSeriesOrBuilder> 
        internalGetTimeseriesFieldBuilder() {
      if (timeseriesBuilder_ == null) {
        timeseriesBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            cn.ecosync.aiot.data.apiserver.api.prometheus.TimeSeries, cn.ecosync.aiot.data.apiserver.api.prometheus.TimeSeries.Builder, cn.ecosync.aiot.data.apiserver.api.prometheus.TimeSeriesOrBuilder>(
                timeseries_,
                ((bitField0_ & 0x00000002) != 0),
                getParentForChildren(),
                isClean());
        timeseries_ = null;
      }
      return timeseriesBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:io.prometheus.write.v2.Request)
  }

  // @@protoc_insertion_point(class_scope:io.prometheus.write.v2.Request)
  private static final cn.ecosync.aiot.data.apiserver.api.prometheus.Request DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new cn.ecosync.aiot.data.apiserver.api.prometheus.Request();
  }

  public static cn.ecosync.aiot.data.apiserver.api.prometheus.Request getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Request>
      PARSER = new com.google.protobuf.AbstractParser<Request>() {
    @java.lang.Override
    public Request parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Request> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Request> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public cn.ecosync.aiot.data.apiserver.api.prometheus.Request getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

