// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: types.proto
// Protobuf Java Version: 4.30.0

package cn.ecosync.aiot.data.apiserver.api.prometheus;

public interface SampleOrBuilder extends
    // @@protoc_insertion_point(interface_extends:io.prometheus.write.v2.Sample)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * value of the sample.
   * </pre>
   *
   * <code>double value = 1;</code>
   * @return The value.
   */
  double getValue();

  /**
   * <pre>
   * timestamp represents timestamp of the sample in ms.
   *
   * For Go, see github.com/prometheus/prometheus/model/timestamp/timestamp.go
   * for conversion from/to time.Time to Prometheus timestamp.
   * </pre>
   *
   * <code>int64 timestamp = 2;</code>
   * @return The timestamp.
   */
  long getTimestamp();
}
