// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: types.proto
// Protobuf Java Version: 4.30.0

package cn.ecosync.aiot.data.apiserver.api.prometheus;

public interface TimeSeriesOrBuilder extends
    // @@protoc_insertion_point(interface_extends:io.prometheus.write.v2.TimeSeries)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * labels_refs is a list of label name-value pair references, encoded
   * as indices to the Request.symbols array. This list's length is always
   * a multiple of two, and the underlying labels should be sorted lexicographically.
   *
   * Note that there might be multiple TimeSeries objects in the same
   * Requests with the same labels e.g. for different exemplars, metadata
   * or created timestamp.
   * </pre>
   *
   * <code>repeated uint32 labels_refs = 1;</code>
   * @return A list containing the labelsRefs.
   */
  java.util.List<java.lang.Integer> getLabelsRefsList();
  /**
   * <pre>
   * labels_refs is a list of label name-value pair references, encoded
   * as indices to the Request.symbols array. This list's length is always
   * a multiple of two, and the underlying labels should be sorted lexicographically.
   *
   * Note that there might be multiple TimeSeries objects in the same
   * Requests with the same labels e.g. for different exemplars, metadata
   * or created timestamp.
   * </pre>
   *
   * <code>repeated uint32 labels_refs = 1;</code>
   * @return The count of labelsRefs.
   */
  int getLabelsRefsCount();
  /**
   * <pre>
   * labels_refs is a list of label name-value pair references, encoded
   * as indices to the Request.symbols array. This list's length is always
   * a multiple of two, and the underlying labels should be sorted lexicographically.
   *
   * Note that there might be multiple TimeSeries objects in the same
   * Requests with the same labels e.g. for different exemplars, metadata
   * or created timestamp.
   * </pre>
   *
   * <code>repeated uint32 labels_refs = 1;</code>
   * @param index The index of the element to return.
   * @return The labelsRefs at the given index.
   */
  int getLabelsRefs(int index);

  /**
   * <pre>
   * Timeseries messages can either specify samples or (native) histogram samples
   * (histogram field), but not both. For a typical sender (real-time metric
   * streaming), in healthy cases, there will be only one sample or histogram.
   *
   * Samples and histograms are sorted by timestamp (older first).
   * </pre>
   *
   * <code>repeated .io.prometheus.write.v2.Sample samples = 2;</code>
   */
  java.util.List<cn.ecosync.aiot.data.apiserver.api.prometheus.Sample> 
      getSamplesList();
  /**
   * <pre>
   * Timeseries messages can either specify samples or (native) histogram samples
   * (histogram field), but not both. For a typical sender (real-time metric
   * streaming), in healthy cases, there will be only one sample or histogram.
   *
   * Samples and histograms are sorted by timestamp (older first).
   * </pre>
   *
   * <code>repeated .io.prometheus.write.v2.Sample samples = 2;</code>
   */
  cn.ecosync.aiot.data.apiserver.api.prometheus.Sample getSamples(int index);
  /**
   * <pre>
   * Timeseries messages can either specify samples or (native) histogram samples
   * (histogram field), but not both. For a typical sender (real-time metric
   * streaming), in healthy cases, there will be only one sample or histogram.
   *
   * Samples and histograms are sorted by timestamp (older first).
   * </pre>
   *
   * <code>repeated .io.prometheus.write.v2.Sample samples = 2;</code>
   */
  int getSamplesCount();
  /**
   * <pre>
   * Timeseries messages can either specify samples or (native) histogram samples
   * (histogram field), but not both. For a typical sender (real-time metric
   * streaming), in healthy cases, there will be only one sample or histogram.
   *
   * Samples and histograms are sorted by timestamp (older first).
   * </pre>
   *
   * <code>repeated .io.prometheus.write.v2.Sample samples = 2;</code>
   */
  java.util.List<? extends cn.ecosync.aiot.data.apiserver.api.prometheus.SampleOrBuilder> 
      getSamplesOrBuilderList();
  /**
   * <pre>
   * Timeseries messages can either specify samples or (native) histogram samples
   * (histogram field), but not both. For a typical sender (real-time metric
   * streaming), in healthy cases, there will be only one sample or histogram.
   *
   * Samples and histograms are sorted by timestamp (older first).
   * </pre>
   *
   * <code>repeated .io.prometheus.write.v2.Sample samples = 2;</code>
   */
  cn.ecosync.aiot.data.apiserver.api.prometheus.SampleOrBuilder getSamplesOrBuilder(
      int index);

  /**
   * <code>repeated .io.prometheus.write.v2.Histogram histograms = 3;</code>
   */
  java.util.List<cn.ecosync.aiot.data.apiserver.api.prometheus.Histogram> 
      getHistogramsList();
  /**
   * <code>repeated .io.prometheus.write.v2.Histogram histograms = 3;</code>
   */
  cn.ecosync.aiot.data.apiserver.api.prometheus.Histogram getHistograms(int index);
  /**
   * <code>repeated .io.prometheus.write.v2.Histogram histograms = 3;</code>
   */
  int getHistogramsCount();
  /**
   * <code>repeated .io.prometheus.write.v2.Histogram histograms = 3;</code>
   */
  java.util.List<? extends cn.ecosync.aiot.data.apiserver.api.prometheus.HistogramOrBuilder> 
      getHistogramsOrBuilderList();
  /**
   * <code>repeated .io.prometheus.write.v2.Histogram histograms = 3;</code>
   */
  cn.ecosync.aiot.data.apiserver.api.prometheus.HistogramOrBuilder getHistogramsOrBuilder(
      int index);

  /**
   * <pre>
   * exemplars represents an optional set of exemplars attached to this series' samples.
   * </pre>
   *
   * <code>repeated .io.prometheus.write.v2.Exemplar exemplars = 4;</code>
   */
  java.util.List<cn.ecosync.aiot.data.apiserver.api.prometheus.Exemplar> 
      getExemplarsList();
  /**
   * <pre>
   * exemplars represents an optional set of exemplars attached to this series' samples.
   * </pre>
   *
   * <code>repeated .io.prometheus.write.v2.Exemplar exemplars = 4;</code>
   */
  cn.ecosync.aiot.data.apiserver.api.prometheus.Exemplar getExemplars(int index);
  /**
   * <pre>
   * exemplars represents an optional set of exemplars attached to this series' samples.
   * </pre>
   *
   * <code>repeated .io.prometheus.write.v2.Exemplar exemplars = 4;</code>
   */
  int getExemplarsCount();
  /**
   * <pre>
   * exemplars represents an optional set of exemplars attached to this series' samples.
   * </pre>
   *
   * <code>repeated .io.prometheus.write.v2.Exemplar exemplars = 4;</code>
   */
  java.util.List<? extends cn.ecosync.aiot.data.apiserver.api.prometheus.ExemplarOrBuilder> 
      getExemplarsOrBuilderList();
  /**
   * <pre>
   * exemplars represents an optional set of exemplars attached to this series' samples.
   * </pre>
   *
   * <code>repeated .io.prometheus.write.v2.Exemplar exemplars = 4;</code>
   */
  cn.ecosync.aiot.data.apiserver.api.prometheus.ExemplarOrBuilder getExemplarsOrBuilder(
      int index);

  /**
   * <pre>
   * metadata represents the metadata associated with the given series' samples.
   * </pre>
   *
   * <code>.io.prometheus.write.v2.Metadata metadata = 5;</code>
   * @return Whether the metadata field is set.
   */
  boolean hasMetadata();
  /**
   * <pre>
   * metadata represents the metadata associated with the given series' samples.
   * </pre>
   *
   * <code>.io.prometheus.write.v2.Metadata metadata = 5;</code>
   * @return The metadata.
   */
  cn.ecosync.aiot.data.apiserver.api.prometheus.Metadata getMetadata();
  /**
   * <pre>
   * metadata represents the metadata associated with the given series' samples.
   * </pre>
   *
   * <code>.io.prometheus.write.v2.Metadata metadata = 5;</code>
   */
  cn.ecosync.aiot.data.apiserver.api.prometheus.MetadataOrBuilder getMetadataOrBuilder();

  /**
   * <pre>
   * created_timestamp represents an optional created timestamp associated with
   * this series' samples in ms format, typically for counter or histogram type
   * metrics. Created timestamp represents the time when the counter started
   * counting (sometimes referred to as start timestamp), which can increase
   * the accuracy of query results.
   *
   * Note that some receivers might require this and in return fail to
   * ingest such samples within the Request.
   *
   * For Go, see github.com/prometheus/prometheus/model/timestamp/timestamp.go
   * for conversion from/to time.Time to Prometheus timestamp.
   *
   * Note that the "optional" keyword is omitted due to
   * https://cloud.google.com/apis/design/design_patterns.md#optional_primitive_fields
   * Zero value means value not set. If you need to use exactly zero value for
   * the timestamp, use 1 millisecond before or after.
   * </pre>
   *
   * <code>int64 created_timestamp = 6;</code>
   * @return The createdTimestamp.
   */
  long getCreatedTimestamp();
}
