// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: types.proto
// Protobuf Java Version: 4.30.0

package cn.ecosync.aiot.data.apiserver.api.prometheus;

/**
 * <pre>
 * TimeSeries represents a single series.
 * </pre>
 *
 * Protobuf type {@code io.prometheus.write.v2.TimeSeries}
 */
public final class TimeSeries extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:io.prometheus.write.v2.TimeSeries)
    TimeSeriesOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 30,
      /* patch= */ 0,
      /* suffix= */ "",
      TimeSeries.class.getName());
  }
  // Use TimeSeries.newBuilder() to construct.
  private TimeSeries(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private TimeSeries() {
    labelsRefs_ = emptyIntList();
    samples_ = java.util.Collections.emptyList();
    histograms_ = java.util.Collections.emptyList();
    exemplars_ = java.util.Collections.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return cn.ecosync.aiot.data.apiserver.api.prometheus.PrometheusProto.internal_static_io_prometheus_write_v2_TimeSeries_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return cn.ecosync.aiot.data.apiserver.api.prometheus.PrometheusProto.internal_static_io_prometheus_write_v2_TimeSeries_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            cn.ecosync.aiot.data.apiserver.api.prometheus.TimeSeries.class, cn.ecosync.aiot.data.apiserver.api.prometheus.TimeSeries.Builder.class);
  }

  private int bitField0_;
  public static final int LABELS_REFS_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private com.google.protobuf.Internal.IntList labelsRefs_ =
      emptyIntList();
  /**
   * <pre>
   * labels_refs is a list of label name-value pair references, encoded
   * as indices to the Request.symbols array. This list's length is always
   * a multiple of two, and the underlying labels should be sorted lexicographically.
   *
   * Note that there might be multiple TimeSeries objects in the same
   * Requests with the same labels e.g. for different exemplars, metadata
   * or created timestamp.
   * </pre>
   *
   * <code>repeated uint32 labels_refs = 1;</code>
   * @return A list containing the labelsRefs.
   */
  @java.lang.Override
  public java.util.List<java.lang.Integer>
      getLabelsRefsList() {
    return labelsRefs_;
  }
  /**
   * <pre>
   * labels_refs is a list of label name-value pair references, encoded
   * as indices to the Request.symbols array. This list's length is always
   * a multiple of two, and the underlying labels should be sorted lexicographically.
   *
   * Note that there might be multiple TimeSeries objects in the same
   * Requests with the same labels e.g. for different exemplars, metadata
   * or created timestamp.
   * </pre>
   *
   * <code>repeated uint32 labels_refs = 1;</code>
   * @return The count of labelsRefs.
   */
  public int getLabelsRefsCount() {
    return labelsRefs_.size();
  }
  /**
   * <pre>
   * labels_refs is a list of label name-value pair references, encoded
   * as indices to the Request.symbols array. This list's length is always
   * a multiple of two, and the underlying labels should be sorted lexicographically.
   *
   * Note that there might be multiple TimeSeries objects in the same
   * Requests with the same labels e.g. for different exemplars, metadata
   * or created timestamp.
   * </pre>
   *
   * <code>repeated uint32 labels_refs = 1;</code>
   * @param index The index of the element to return.
   * @return The labelsRefs at the given index.
   */
  public int getLabelsRefs(int index) {
    return labelsRefs_.getInt(index);
  }
  private int labelsRefsMemoizedSerializedSize = -1;

  public static final int SAMPLES_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private java.util.List<cn.ecosync.aiot.data.apiserver.api.prometheus.Sample> samples_;
  /**
   * <pre>
   * Timeseries messages can either specify samples or (native) histogram samples
   * (histogram field), but not both. For a typical sender (real-time metric
   * streaming), in healthy cases, there will be only one sample or histogram.
   *
   * Samples and histograms are sorted by timestamp (older first).
   * </pre>
   *
   * <code>repeated .io.prometheus.write.v2.Sample samples = 2;</code>
   */
  @java.lang.Override
  public java.util.List<cn.ecosync.aiot.data.apiserver.api.prometheus.Sample> getSamplesList() {
    return samples_;
  }
  /**
   * <pre>
   * Timeseries messages can either specify samples or (native) histogram samples
   * (histogram field), but not both. For a typical sender (real-time metric
   * streaming), in healthy cases, there will be only one sample or histogram.
   *
   * Samples and histograms are sorted by timestamp (older first).
   * </pre>
   *
   * <code>repeated .io.prometheus.write.v2.Sample samples = 2;</code>
   */
  @java.lang.Override
  public java.util.List<? extends cn.ecosync.aiot.data.apiserver.api.prometheus.SampleOrBuilder> 
      getSamplesOrBuilderList() {
    return samples_;
  }
  /**
   * <pre>
   * Timeseries messages can either specify samples or (native) histogram samples
   * (histogram field), but not both. For a typical sender (real-time metric
   * streaming), in healthy cases, there will be only one sample or histogram.
   *
   * Samples and histograms are sorted by timestamp (older first).
   * </pre>
   *
   * <code>repeated .io.prometheus.write.v2.Sample samples = 2;</code>
   */
  @java.lang.Override
  public int getSamplesCount() {
    return samples_.size();
  }
  /**
   * <pre>
   * Timeseries messages can either specify samples or (native) histogram samples
   * (histogram field), but not both. For a typical sender (real-time metric
   * streaming), in healthy cases, there will be only one sample or histogram.
   *
   * Samples and histograms are sorted by timestamp (older first).
   * </pre>
   *
   * <code>repeated .io.prometheus.write.v2.Sample samples = 2;</code>
   */
  @java.lang.Override
  public cn.ecosync.aiot.data.apiserver.api.prometheus.Sample getSamples(int index) {
    return samples_.get(index);
  }
  /**
   * <pre>
   * Timeseries messages can either specify samples or (native) histogram samples
   * (histogram field), but not both. For a typical sender (real-time metric
   * streaming), in healthy cases, there will be only one sample or histogram.
   *
   * Samples and histograms are sorted by timestamp (older first).
   * </pre>
   *
   * <code>repeated .io.prometheus.write.v2.Sample samples = 2;</code>
   */
  @java.lang.Override
  public cn.ecosync.aiot.data.apiserver.api.prometheus.SampleOrBuilder getSamplesOrBuilder(
      int index) {
    return samples_.get(index);
  }

  public static final int HISTOGRAMS_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private java.util.List<cn.ecosync.aiot.data.apiserver.api.prometheus.Histogram> histograms_;
  /**
   * <code>repeated .io.prometheus.write.v2.Histogram histograms = 3;</code>
   */
  @java.lang.Override
  public java.util.List<cn.ecosync.aiot.data.apiserver.api.prometheus.Histogram> getHistogramsList() {
    return histograms_;
  }
  /**
   * <code>repeated .io.prometheus.write.v2.Histogram histograms = 3;</code>
   */
  @java.lang.Override
  public java.util.List<? extends cn.ecosync.aiot.data.apiserver.api.prometheus.HistogramOrBuilder> 
      getHistogramsOrBuilderList() {
    return histograms_;
  }
  /**
   * <code>repeated .io.prometheus.write.v2.Histogram histograms = 3;</code>
   */
  @java.lang.Override
  public int getHistogramsCount() {
    return histograms_.size();
  }
  /**
   * <code>repeated .io.prometheus.write.v2.Histogram histograms = 3;</code>
   */
  @java.lang.Override
  public cn.ecosync.aiot.data.apiserver.api.prometheus.Histogram getHistograms(int index) {
    return histograms_.get(index);
  }
  /**
   * <code>repeated .io.prometheus.write.v2.Histogram histograms = 3;</code>
   */
  @java.lang.Override
  public cn.ecosync.aiot.data.apiserver.api.prometheus.HistogramOrBuilder getHistogramsOrBuilder(
      int index) {
    return histograms_.get(index);
  }

  public static final int EXEMPLARS_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private java.util.List<cn.ecosync.aiot.data.apiserver.api.prometheus.Exemplar> exemplars_;
  /**
   * <pre>
   * exemplars represents an optional set of exemplars attached to this series' samples.
   * </pre>
   *
   * <code>repeated .io.prometheus.write.v2.Exemplar exemplars = 4;</code>
   */
  @java.lang.Override
  public java.util.List<cn.ecosync.aiot.data.apiserver.api.prometheus.Exemplar> getExemplarsList() {
    return exemplars_;
  }
  /**
   * <pre>
   * exemplars represents an optional set of exemplars attached to this series' samples.
   * </pre>
   *
   * <code>repeated .io.prometheus.write.v2.Exemplar exemplars = 4;</code>
   */
  @java.lang.Override
  public java.util.List<? extends cn.ecosync.aiot.data.apiserver.api.prometheus.ExemplarOrBuilder> 
      getExemplarsOrBuilderList() {
    return exemplars_;
  }
  /**
   * <pre>
   * exemplars represents an optional set of exemplars attached to this series' samples.
   * </pre>
   *
   * <code>repeated .io.prometheus.write.v2.Exemplar exemplars = 4;</code>
   */
  @java.lang.Override
  public int getExemplarsCount() {
    return exemplars_.size();
  }
  /**
   * <pre>
   * exemplars represents an optional set of exemplars attached to this series' samples.
   * </pre>
   *
   * <code>repeated .io.prometheus.write.v2.Exemplar exemplars = 4;</code>
   */
  @java.lang.Override
  public cn.ecosync.aiot.data.apiserver.api.prometheus.Exemplar getExemplars(int index) {
    return exemplars_.get(index);
  }
  /**
   * <pre>
   * exemplars represents an optional set of exemplars attached to this series' samples.
   * </pre>
   *
   * <code>repeated .io.prometheus.write.v2.Exemplar exemplars = 4;</code>
   */
  @java.lang.Override
  public cn.ecosync.aiot.data.apiserver.api.prometheus.ExemplarOrBuilder getExemplarsOrBuilder(
      int index) {
    return exemplars_.get(index);
  }

  public static final int METADATA_FIELD_NUMBER = 5;
  private cn.ecosync.aiot.data.apiserver.api.prometheus.Metadata metadata_;
  /**
   * <pre>
   * metadata represents the metadata associated with the given series' samples.
   * </pre>
   *
   * <code>.io.prometheus.write.v2.Metadata metadata = 5;</code>
   * @return Whether the metadata field is set.
   */
  @java.lang.Override
  public boolean hasMetadata() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   * metadata represents the metadata associated with the given series' samples.
   * </pre>
   *
   * <code>.io.prometheus.write.v2.Metadata metadata = 5;</code>
   * @return The metadata.
   */
  @java.lang.Override
  public cn.ecosync.aiot.data.apiserver.api.prometheus.Metadata getMetadata() {
    return metadata_ == null ? cn.ecosync.aiot.data.apiserver.api.prometheus.Metadata.getDefaultInstance() : metadata_;
  }
  /**
   * <pre>
   * metadata represents the metadata associated with the given series' samples.
   * </pre>
   *
   * <code>.io.prometheus.write.v2.Metadata metadata = 5;</code>
   */
  @java.lang.Override
  public cn.ecosync.aiot.data.apiserver.api.prometheus.MetadataOrBuilder getMetadataOrBuilder() {
    return metadata_ == null ? cn.ecosync.aiot.data.apiserver.api.prometheus.Metadata.getDefaultInstance() : metadata_;
  }

  public static final int CREATED_TIMESTAMP_FIELD_NUMBER = 6;
  private long createdTimestamp_ = 0L;
  /**
   * <pre>
   * created_timestamp represents an optional created timestamp associated with
   * this series' samples in ms format, typically for counter or histogram type
   * metrics. Created timestamp represents the time when the counter started
   * counting (sometimes referred to as start timestamp), which can increase
   * the accuracy of query results.
   *
   * Note that some receivers might require this and in return fail to
   * ingest such samples within the Request.
   *
   * For Go, see github.com/prometheus/prometheus/model/timestamp/timestamp.go
   * for conversion from/to time.Time to Prometheus timestamp.
   *
   * Note that the "optional" keyword is omitted due to
   * https://cloud.google.com/apis/design/design_patterns.md#optional_primitive_fields
   * Zero value means value not set. If you need to use exactly zero value for
   * the timestamp, use 1 millisecond before or after.
   * </pre>
   *
   * <code>int64 created_timestamp = 6;</code>
   * @return The createdTimestamp.
   */
  @java.lang.Override
  public long getCreatedTimestamp() {
    return createdTimestamp_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (getLabelsRefsList().size() > 0) {
      output.writeUInt32NoTag(10);
      output.writeUInt32NoTag(labelsRefsMemoizedSerializedSize);
    }
    for (int i = 0; i < labelsRefs_.size(); i++) {
      output.writeUInt32NoTag(labelsRefs_.getInt(i));
    }
    for (int i = 0; i < samples_.size(); i++) {
      output.writeMessage(2, samples_.get(i));
    }
    for (int i = 0; i < histograms_.size(); i++) {
      output.writeMessage(3, histograms_.get(i));
    }
    for (int i = 0; i < exemplars_.size(); i++) {
      output.writeMessage(4, exemplars_.get(i));
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(5, getMetadata());
    }
    if (createdTimestamp_ != 0L) {
      output.writeInt64(6, createdTimestamp_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    {
      int dataSize = 0;
      for (int i = 0; i < labelsRefs_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeUInt32SizeNoTag(labelsRefs_.getInt(i));
      }
      size += dataSize;
      if (!getLabelsRefsList().isEmpty()) {
        size += 1;
        size += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(dataSize);
      }
      labelsRefsMemoizedSerializedSize = dataSize;
    }
    for (int i = 0; i < samples_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, samples_.get(i));
    }
    for (int i = 0; i < histograms_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, histograms_.get(i));
    }
    for (int i = 0; i < exemplars_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, exemplars_.get(i));
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, getMetadata());
    }
    if (createdTimestamp_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(6, createdTimestamp_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof cn.ecosync.aiot.data.apiserver.api.prometheus.TimeSeries)) {
      return super.equals(obj);
    }
    cn.ecosync.aiot.data.apiserver.api.prometheus.TimeSeries other = (cn.ecosync.aiot.data.apiserver.api.prometheus.TimeSeries) obj;

    if (!getLabelsRefsList()
        .equals(other.getLabelsRefsList())) return false;
    if (!getSamplesList()
        .equals(other.getSamplesList())) return false;
    if (!getHistogramsList()
        .equals(other.getHistogramsList())) return false;
    if (!getExemplarsList()
        .equals(other.getExemplarsList())) return false;
    if (hasMetadata() != other.hasMetadata()) return false;
    if (hasMetadata()) {
      if (!getMetadata()
          .equals(other.getMetadata())) return false;
    }
    if (getCreatedTimestamp()
        != other.getCreatedTimestamp()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getLabelsRefsCount() > 0) {
      hash = (37 * hash) + LABELS_REFS_FIELD_NUMBER;
      hash = (53 * hash) + getLabelsRefsList().hashCode();
    }
    if (getSamplesCount() > 0) {
      hash = (37 * hash) + SAMPLES_FIELD_NUMBER;
      hash = (53 * hash) + getSamplesList().hashCode();
    }
    if (getHistogramsCount() > 0) {
      hash = (37 * hash) + HISTOGRAMS_FIELD_NUMBER;
      hash = (53 * hash) + getHistogramsList().hashCode();
    }
    if (getExemplarsCount() > 0) {
      hash = (37 * hash) + EXEMPLARS_FIELD_NUMBER;
      hash = (53 * hash) + getExemplarsList().hashCode();
    }
    if (hasMetadata()) {
      hash = (37 * hash) + METADATA_FIELD_NUMBER;
      hash = (53 * hash) + getMetadata().hashCode();
    }
    hash = (37 * hash) + CREATED_TIMESTAMP_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getCreatedTimestamp());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static cn.ecosync.aiot.data.apiserver.api.prometheus.TimeSeries parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cn.ecosync.aiot.data.apiserver.api.prometheus.TimeSeries parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cn.ecosync.aiot.data.apiserver.api.prometheus.TimeSeries parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cn.ecosync.aiot.data.apiserver.api.prometheus.TimeSeries parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cn.ecosync.aiot.data.apiserver.api.prometheus.TimeSeries parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cn.ecosync.aiot.data.apiserver.api.prometheus.TimeSeries parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cn.ecosync.aiot.data.apiserver.api.prometheus.TimeSeries parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static cn.ecosync.aiot.data.apiserver.api.prometheus.TimeSeries parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static cn.ecosync.aiot.data.apiserver.api.prometheus.TimeSeries parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static cn.ecosync.aiot.data.apiserver.api.prometheus.TimeSeries parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static cn.ecosync.aiot.data.apiserver.api.prometheus.TimeSeries parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static cn.ecosync.aiot.data.apiserver.api.prometheus.TimeSeries parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(cn.ecosync.aiot.data.apiserver.api.prometheus.TimeSeries prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * TimeSeries represents a single series.
   * </pre>
   *
   * Protobuf type {@code io.prometheus.write.v2.TimeSeries}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:io.prometheus.write.v2.TimeSeries)
      cn.ecosync.aiot.data.apiserver.api.prometheus.TimeSeriesOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cn.ecosync.aiot.data.apiserver.api.prometheus.PrometheusProto.internal_static_io_prometheus_write_v2_TimeSeries_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cn.ecosync.aiot.data.apiserver.api.prometheus.PrometheusProto.internal_static_io_prometheus_write_v2_TimeSeries_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cn.ecosync.aiot.data.apiserver.api.prometheus.TimeSeries.class, cn.ecosync.aiot.data.apiserver.api.prometheus.TimeSeries.Builder.class);
    }

    // Construct using cn.ecosync.aiot.data.apiserver.api.prometheus.TimeSeries.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        internalGetSamplesFieldBuilder();
        internalGetHistogramsFieldBuilder();
        internalGetExemplarsFieldBuilder();
        internalGetMetadataFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      labelsRefs_ = emptyIntList();
      if (samplesBuilder_ == null) {
        samples_ = java.util.Collections.emptyList();
      } else {
        samples_ = null;
        samplesBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000002);
      if (histogramsBuilder_ == null) {
        histograms_ = java.util.Collections.emptyList();
      } else {
        histograms_ = null;
        histogramsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000004);
      if (exemplarsBuilder_ == null) {
        exemplars_ = java.util.Collections.emptyList();
      } else {
        exemplars_ = null;
        exemplarsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000008);
      metadata_ = null;
      if (metadataBuilder_ != null) {
        metadataBuilder_.dispose();
        metadataBuilder_ = null;
      }
      createdTimestamp_ = 0L;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return cn.ecosync.aiot.data.apiserver.api.prometheus.PrometheusProto.internal_static_io_prometheus_write_v2_TimeSeries_descriptor;
    }

    @java.lang.Override
    public cn.ecosync.aiot.data.apiserver.api.prometheus.TimeSeries getDefaultInstanceForType() {
      return cn.ecosync.aiot.data.apiserver.api.prometheus.TimeSeries.getDefaultInstance();
    }

    @java.lang.Override
    public cn.ecosync.aiot.data.apiserver.api.prometheus.TimeSeries build() {
      cn.ecosync.aiot.data.apiserver.api.prometheus.TimeSeries result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public cn.ecosync.aiot.data.apiserver.api.prometheus.TimeSeries buildPartial() {
      cn.ecosync.aiot.data.apiserver.api.prometheus.TimeSeries result = new cn.ecosync.aiot.data.apiserver.api.prometheus.TimeSeries(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(cn.ecosync.aiot.data.apiserver.api.prometheus.TimeSeries result) {
      if (samplesBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0)) {
          samples_ = java.util.Collections.unmodifiableList(samples_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.samples_ = samples_;
      } else {
        result.samples_ = samplesBuilder_.build();
      }
      if (histogramsBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0)) {
          histograms_ = java.util.Collections.unmodifiableList(histograms_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.histograms_ = histograms_;
      } else {
        result.histograms_ = histogramsBuilder_.build();
      }
      if (exemplarsBuilder_ == null) {
        if (((bitField0_ & 0x00000008) != 0)) {
          exemplars_ = java.util.Collections.unmodifiableList(exemplars_);
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.exemplars_ = exemplars_;
      } else {
        result.exemplars_ = exemplarsBuilder_.build();
      }
    }

    private void buildPartial0(cn.ecosync.aiot.data.apiserver.api.prometheus.TimeSeries result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        labelsRefs_.makeImmutable();
        result.labelsRefs_ = labelsRefs_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.metadata_ = metadataBuilder_ == null
            ? metadata_
            : metadataBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.createdTimestamp_ = createdTimestamp_;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof cn.ecosync.aiot.data.apiserver.api.prometheus.TimeSeries) {
        return mergeFrom((cn.ecosync.aiot.data.apiserver.api.prometheus.TimeSeries)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(cn.ecosync.aiot.data.apiserver.api.prometheus.TimeSeries other) {
      if (other == cn.ecosync.aiot.data.apiserver.api.prometheus.TimeSeries.getDefaultInstance()) return this;
      if (!other.labelsRefs_.isEmpty()) {
        if (labelsRefs_.isEmpty()) {
          labelsRefs_ = other.labelsRefs_;
          labelsRefs_.makeImmutable();
          bitField0_ |= 0x00000001;
        } else {
          ensureLabelsRefsIsMutable();
          labelsRefs_.addAll(other.labelsRefs_);
        }
        onChanged();
      }
      if (samplesBuilder_ == null) {
        if (!other.samples_.isEmpty()) {
          if (samples_.isEmpty()) {
            samples_ = other.samples_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureSamplesIsMutable();
            samples_.addAll(other.samples_);
          }
          onChanged();
        }
      } else {
        if (!other.samples_.isEmpty()) {
          if (samplesBuilder_.isEmpty()) {
            samplesBuilder_.dispose();
            samplesBuilder_ = null;
            samples_ = other.samples_;
            bitField0_ = (bitField0_ & ~0x00000002);
            samplesBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 internalGetSamplesFieldBuilder() : null;
          } else {
            samplesBuilder_.addAllMessages(other.samples_);
          }
        }
      }
      if (histogramsBuilder_ == null) {
        if (!other.histograms_.isEmpty()) {
          if (histograms_.isEmpty()) {
            histograms_ = other.histograms_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureHistogramsIsMutable();
            histograms_.addAll(other.histograms_);
          }
          onChanged();
        }
      } else {
        if (!other.histograms_.isEmpty()) {
          if (histogramsBuilder_.isEmpty()) {
            histogramsBuilder_.dispose();
            histogramsBuilder_ = null;
            histograms_ = other.histograms_;
            bitField0_ = (bitField0_ & ~0x00000004);
            histogramsBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 internalGetHistogramsFieldBuilder() : null;
          } else {
            histogramsBuilder_.addAllMessages(other.histograms_);
          }
        }
      }
      if (exemplarsBuilder_ == null) {
        if (!other.exemplars_.isEmpty()) {
          if (exemplars_.isEmpty()) {
            exemplars_ = other.exemplars_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureExemplarsIsMutable();
            exemplars_.addAll(other.exemplars_);
          }
          onChanged();
        }
      } else {
        if (!other.exemplars_.isEmpty()) {
          if (exemplarsBuilder_.isEmpty()) {
            exemplarsBuilder_.dispose();
            exemplarsBuilder_ = null;
            exemplars_ = other.exemplars_;
            bitField0_ = (bitField0_ & ~0x00000008);
            exemplarsBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 internalGetExemplarsFieldBuilder() : null;
          } else {
            exemplarsBuilder_.addAllMessages(other.exemplars_);
          }
        }
      }
      if (other.hasMetadata()) {
        mergeMetadata(other.getMetadata());
      }
      if (other.getCreatedTimestamp() != 0L) {
        setCreatedTimestamp(other.getCreatedTimestamp());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int v = input.readUInt32();
              ensureLabelsRefsIsMutable();
              labelsRefs_.addInt(v);
              break;
            } // case 8
            case 10: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              ensureLabelsRefsIsMutable();
              while (input.getBytesUntilLimit() > 0) {
                labelsRefs_.addInt(input.readUInt32());
              }
              input.popLimit(limit);
              break;
            } // case 10
            case 18: {
              cn.ecosync.aiot.data.apiserver.api.prometheus.Sample m =
                  input.readMessage(
                      cn.ecosync.aiot.data.apiserver.api.prometheus.Sample.parser(),
                      extensionRegistry);
              if (samplesBuilder_ == null) {
                ensureSamplesIsMutable();
                samples_.add(m);
              } else {
                samplesBuilder_.addMessage(m);
              }
              break;
            } // case 18
            case 26: {
              cn.ecosync.aiot.data.apiserver.api.prometheus.Histogram m =
                  input.readMessage(
                      cn.ecosync.aiot.data.apiserver.api.prometheus.Histogram.parser(),
                      extensionRegistry);
              if (histogramsBuilder_ == null) {
                ensureHistogramsIsMutable();
                histograms_.add(m);
              } else {
                histogramsBuilder_.addMessage(m);
              }
              break;
            } // case 26
            case 34: {
              cn.ecosync.aiot.data.apiserver.api.prometheus.Exemplar m =
                  input.readMessage(
                      cn.ecosync.aiot.data.apiserver.api.prometheus.Exemplar.parser(),
                      extensionRegistry);
              if (exemplarsBuilder_ == null) {
                ensureExemplarsIsMutable();
                exemplars_.add(m);
              } else {
                exemplarsBuilder_.addMessage(m);
              }
              break;
            } // case 34
            case 42: {
              input.readMessage(
                  internalGetMetadataFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            case 48: {
              createdTimestamp_ = input.readInt64();
              bitField0_ |= 0x00000020;
              break;
            } // case 48
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.Internal.IntList labelsRefs_ = emptyIntList();
    private void ensureLabelsRefsIsMutable() {
      if (!labelsRefs_.isModifiable()) {
        labelsRefs_ = makeMutableCopy(labelsRefs_);
      }
      bitField0_ |= 0x00000001;
    }
    /**
     * <pre>
     * labels_refs is a list of label name-value pair references, encoded
     * as indices to the Request.symbols array. This list's length is always
     * a multiple of two, and the underlying labels should be sorted lexicographically.
     *
     * Note that there might be multiple TimeSeries objects in the same
     * Requests with the same labels e.g. for different exemplars, metadata
     * or created timestamp.
     * </pre>
     *
     * <code>repeated uint32 labels_refs = 1;</code>
     * @return A list containing the labelsRefs.
     */
    public java.util.List<java.lang.Integer>
        getLabelsRefsList() {
      labelsRefs_.makeImmutable();
      return labelsRefs_;
    }
    /**
     * <pre>
     * labels_refs is a list of label name-value pair references, encoded
     * as indices to the Request.symbols array. This list's length is always
     * a multiple of two, and the underlying labels should be sorted lexicographically.
     *
     * Note that there might be multiple TimeSeries objects in the same
     * Requests with the same labels e.g. for different exemplars, metadata
     * or created timestamp.
     * </pre>
     *
     * <code>repeated uint32 labels_refs = 1;</code>
     * @return The count of labelsRefs.
     */
    public int getLabelsRefsCount() {
      return labelsRefs_.size();
    }
    /**
     * <pre>
     * labels_refs is a list of label name-value pair references, encoded
     * as indices to the Request.symbols array. This list's length is always
     * a multiple of two, and the underlying labels should be sorted lexicographically.
     *
     * Note that there might be multiple TimeSeries objects in the same
     * Requests with the same labels e.g. for different exemplars, metadata
     * or created timestamp.
     * </pre>
     *
     * <code>repeated uint32 labels_refs = 1;</code>
     * @param index The index of the element to return.
     * @return The labelsRefs at the given index.
     */
    public int getLabelsRefs(int index) {
      return labelsRefs_.getInt(index);
    }
    /**
     * <pre>
     * labels_refs is a list of label name-value pair references, encoded
     * as indices to the Request.symbols array. This list's length is always
     * a multiple of two, and the underlying labels should be sorted lexicographically.
     *
     * Note that there might be multiple TimeSeries objects in the same
     * Requests with the same labels e.g. for different exemplars, metadata
     * or created timestamp.
     * </pre>
     *
     * <code>repeated uint32 labels_refs = 1;</code>
     * @param index The index to set the value at.
     * @param value The labelsRefs to set.
     * @return This builder for chaining.
     */
    public Builder setLabelsRefs(
        int index, int value) {

      ensureLabelsRefsIsMutable();
      labelsRefs_.setInt(index, value);
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * labels_refs is a list of label name-value pair references, encoded
     * as indices to the Request.symbols array. This list's length is always
     * a multiple of two, and the underlying labels should be sorted lexicographically.
     *
     * Note that there might be multiple TimeSeries objects in the same
     * Requests with the same labels e.g. for different exemplars, metadata
     * or created timestamp.
     * </pre>
     *
     * <code>repeated uint32 labels_refs = 1;</code>
     * @param value The labelsRefs to add.
     * @return This builder for chaining.
     */
    public Builder addLabelsRefs(int value) {

      ensureLabelsRefsIsMutable();
      labelsRefs_.addInt(value);
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * labels_refs is a list of label name-value pair references, encoded
     * as indices to the Request.symbols array. This list's length is always
     * a multiple of two, and the underlying labels should be sorted lexicographically.
     *
     * Note that there might be multiple TimeSeries objects in the same
     * Requests with the same labels e.g. for different exemplars, metadata
     * or created timestamp.
     * </pre>
     *
     * <code>repeated uint32 labels_refs = 1;</code>
     * @param values The labelsRefs to add.
     * @return This builder for chaining.
     */
    public Builder addAllLabelsRefs(
        java.lang.Iterable<? extends java.lang.Integer> values) {
      ensureLabelsRefsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, labelsRefs_);
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * labels_refs is a list of label name-value pair references, encoded
     * as indices to the Request.symbols array. This list's length is always
     * a multiple of two, and the underlying labels should be sorted lexicographically.
     *
     * Note that there might be multiple TimeSeries objects in the same
     * Requests with the same labels e.g. for different exemplars, metadata
     * or created timestamp.
     * </pre>
     *
     * <code>repeated uint32 labels_refs = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearLabelsRefs() {
      labelsRefs_ = emptyIntList();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }

    private java.util.List<cn.ecosync.aiot.data.apiserver.api.prometheus.Sample> samples_ =
      java.util.Collections.emptyList();
    private void ensureSamplesIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        samples_ = new java.util.ArrayList<cn.ecosync.aiot.data.apiserver.api.prometheus.Sample>(samples_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        cn.ecosync.aiot.data.apiserver.api.prometheus.Sample, cn.ecosync.aiot.data.apiserver.api.prometheus.Sample.Builder, cn.ecosync.aiot.data.apiserver.api.prometheus.SampleOrBuilder> samplesBuilder_;

    /**
     * <pre>
     * Timeseries messages can either specify samples or (native) histogram samples
     * (histogram field), but not both. For a typical sender (real-time metric
     * streaming), in healthy cases, there will be only one sample or histogram.
     *
     * Samples and histograms are sorted by timestamp (older first).
     * </pre>
     *
     * <code>repeated .io.prometheus.write.v2.Sample samples = 2;</code>
     */
    public java.util.List<cn.ecosync.aiot.data.apiserver.api.prometheus.Sample> getSamplesList() {
      if (samplesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(samples_);
      } else {
        return samplesBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * Timeseries messages can either specify samples or (native) histogram samples
     * (histogram field), but not both. For a typical sender (real-time metric
     * streaming), in healthy cases, there will be only one sample or histogram.
     *
     * Samples and histograms are sorted by timestamp (older first).
     * </pre>
     *
     * <code>repeated .io.prometheus.write.v2.Sample samples = 2;</code>
     */
    public int getSamplesCount() {
      if (samplesBuilder_ == null) {
        return samples_.size();
      } else {
        return samplesBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * Timeseries messages can either specify samples or (native) histogram samples
     * (histogram field), but not both. For a typical sender (real-time metric
     * streaming), in healthy cases, there will be only one sample or histogram.
     *
     * Samples and histograms are sorted by timestamp (older first).
     * </pre>
     *
     * <code>repeated .io.prometheus.write.v2.Sample samples = 2;</code>
     */
    public cn.ecosync.aiot.data.apiserver.api.prometheus.Sample getSamples(int index) {
      if (samplesBuilder_ == null) {
        return samples_.get(index);
      } else {
        return samplesBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * Timeseries messages can either specify samples or (native) histogram samples
     * (histogram field), but not both. For a typical sender (real-time metric
     * streaming), in healthy cases, there will be only one sample or histogram.
     *
     * Samples and histograms are sorted by timestamp (older first).
     * </pre>
     *
     * <code>repeated .io.prometheus.write.v2.Sample samples = 2;</code>
     */
    public Builder setSamples(
        int index, cn.ecosync.aiot.data.apiserver.api.prometheus.Sample value) {
      if (samplesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSamplesIsMutable();
        samples_.set(index, value);
        onChanged();
      } else {
        samplesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * Timeseries messages can either specify samples or (native) histogram samples
     * (histogram field), but not both. For a typical sender (real-time metric
     * streaming), in healthy cases, there will be only one sample or histogram.
     *
     * Samples and histograms are sorted by timestamp (older first).
     * </pre>
     *
     * <code>repeated .io.prometheus.write.v2.Sample samples = 2;</code>
     */
    public Builder setSamples(
        int index, cn.ecosync.aiot.data.apiserver.api.prometheus.Sample.Builder builderForValue) {
      if (samplesBuilder_ == null) {
        ensureSamplesIsMutable();
        samples_.set(index, builderForValue.build());
        onChanged();
      } else {
        samplesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Timeseries messages can either specify samples or (native) histogram samples
     * (histogram field), but not both. For a typical sender (real-time metric
     * streaming), in healthy cases, there will be only one sample or histogram.
     *
     * Samples and histograms are sorted by timestamp (older first).
     * </pre>
     *
     * <code>repeated .io.prometheus.write.v2.Sample samples = 2;</code>
     */
    public Builder addSamples(cn.ecosync.aiot.data.apiserver.api.prometheus.Sample value) {
      if (samplesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSamplesIsMutable();
        samples_.add(value);
        onChanged();
      } else {
        samplesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * Timeseries messages can either specify samples or (native) histogram samples
     * (histogram field), but not both. For a typical sender (real-time metric
     * streaming), in healthy cases, there will be only one sample or histogram.
     *
     * Samples and histograms are sorted by timestamp (older first).
     * </pre>
     *
     * <code>repeated .io.prometheus.write.v2.Sample samples = 2;</code>
     */
    public Builder addSamples(
        int index, cn.ecosync.aiot.data.apiserver.api.prometheus.Sample value) {
      if (samplesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSamplesIsMutable();
        samples_.add(index, value);
        onChanged();
      } else {
        samplesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * Timeseries messages can either specify samples or (native) histogram samples
     * (histogram field), but not both. For a typical sender (real-time metric
     * streaming), in healthy cases, there will be only one sample or histogram.
     *
     * Samples and histograms are sorted by timestamp (older first).
     * </pre>
     *
     * <code>repeated .io.prometheus.write.v2.Sample samples = 2;</code>
     */
    public Builder addSamples(
        cn.ecosync.aiot.data.apiserver.api.prometheus.Sample.Builder builderForValue) {
      if (samplesBuilder_ == null) {
        ensureSamplesIsMutable();
        samples_.add(builderForValue.build());
        onChanged();
      } else {
        samplesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Timeseries messages can either specify samples or (native) histogram samples
     * (histogram field), but not both. For a typical sender (real-time metric
     * streaming), in healthy cases, there will be only one sample or histogram.
     *
     * Samples and histograms are sorted by timestamp (older first).
     * </pre>
     *
     * <code>repeated .io.prometheus.write.v2.Sample samples = 2;</code>
     */
    public Builder addSamples(
        int index, cn.ecosync.aiot.data.apiserver.api.prometheus.Sample.Builder builderForValue) {
      if (samplesBuilder_ == null) {
        ensureSamplesIsMutable();
        samples_.add(index, builderForValue.build());
        onChanged();
      } else {
        samplesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Timeseries messages can either specify samples or (native) histogram samples
     * (histogram field), but not both. For a typical sender (real-time metric
     * streaming), in healthy cases, there will be only one sample or histogram.
     *
     * Samples and histograms are sorted by timestamp (older first).
     * </pre>
     *
     * <code>repeated .io.prometheus.write.v2.Sample samples = 2;</code>
     */
    public Builder addAllSamples(
        java.lang.Iterable<? extends cn.ecosync.aiot.data.apiserver.api.prometheus.Sample> values) {
      if (samplesBuilder_ == null) {
        ensureSamplesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, samples_);
        onChanged();
      } else {
        samplesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * Timeseries messages can either specify samples or (native) histogram samples
     * (histogram field), but not both. For a typical sender (real-time metric
     * streaming), in healthy cases, there will be only one sample or histogram.
     *
     * Samples and histograms are sorted by timestamp (older first).
     * </pre>
     *
     * <code>repeated .io.prometheus.write.v2.Sample samples = 2;</code>
     */
    public Builder clearSamples() {
      if (samplesBuilder_ == null) {
        samples_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        samplesBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * Timeseries messages can either specify samples or (native) histogram samples
     * (histogram field), but not both. For a typical sender (real-time metric
     * streaming), in healthy cases, there will be only one sample or histogram.
     *
     * Samples and histograms are sorted by timestamp (older first).
     * </pre>
     *
     * <code>repeated .io.prometheus.write.v2.Sample samples = 2;</code>
     */
    public Builder removeSamples(int index) {
      if (samplesBuilder_ == null) {
        ensureSamplesIsMutable();
        samples_.remove(index);
        onChanged();
      } else {
        samplesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * Timeseries messages can either specify samples or (native) histogram samples
     * (histogram field), but not both. For a typical sender (real-time metric
     * streaming), in healthy cases, there will be only one sample or histogram.
     *
     * Samples and histograms are sorted by timestamp (older first).
     * </pre>
     *
     * <code>repeated .io.prometheus.write.v2.Sample samples = 2;</code>
     */
    public cn.ecosync.aiot.data.apiserver.api.prometheus.Sample.Builder getSamplesBuilder(
        int index) {
      return internalGetSamplesFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * Timeseries messages can either specify samples or (native) histogram samples
     * (histogram field), but not both. For a typical sender (real-time metric
     * streaming), in healthy cases, there will be only one sample or histogram.
     *
     * Samples and histograms are sorted by timestamp (older first).
     * </pre>
     *
     * <code>repeated .io.prometheus.write.v2.Sample samples = 2;</code>
     */
    public cn.ecosync.aiot.data.apiserver.api.prometheus.SampleOrBuilder getSamplesOrBuilder(
        int index) {
      if (samplesBuilder_ == null) {
        return samples_.get(index);  } else {
        return samplesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * Timeseries messages can either specify samples or (native) histogram samples
     * (histogram field), but not both. For a typical sender (real-time metric
     * streaming), in healthy cases, there will be only one sample or histogram.
     *
     * Samples and histograms are sorted by timestamp (older first).
     * </pre>
     *
     * <code>repeated .io.prometheus.write.v2.Sample samples = 2;</code>
     */
    public java.util.List<? extends cn.ecosync.aiot.data.apiserver.api.prometheus.SampleOrBuilder> 
         getSamplesOrBuilderList() {
      if (samplesBuilder_ != null) {
        return samplesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(samples_);
      }
    }
    /**
     * <pre>
     * Timeseries messages can either specify samples or (native) histogram samples
     * (histogram field), but not both. For a typical sender (real-time metric
     * streaming), in healthy cases, there will be only one sample or histogram.
     *
     * Samples and histograms are sorted by timestamp (older first).
     * </pre>
     *
     * <code>repeated .io.prometheus.write.v2.Sample samples = 2;</code>
     */
    public cn.ecosync.aiot.data.apiserver.api.prometheus.Sample.Builder addSamplesBuilder() {
      return internalGetSamplesFieldBuilder().addBuilder(
          cn.ecosync.aiot.data.apiserver.api.prometheus.Sample.getDefaultInstance());
    }
    /**
     * <pre>
     * Timeseries messages can either specify samples or (native) histogram samples
     * (histogram field), but not both. For a typical sender (real-time metric
     * streaming), in healthy cases, there will be only one sample or histogram.
     *
     * Samples and histograms are sorted by timestamp (older first).
     * </pre>
     *
     * <code>repeated .io.prometheus.write.v2.Sample samples = 2;</code>
     */
    public cn.ecosync.aiot.data.apiserver.api.prometheus.Sample.Builder addSamplesBuilder(
        int index) {
      return internalGetSamplesFieldBuilder().addBuilder(
          index, cn.ecosync.aiot.data.apiserver.api.prometheus.Sample.getDefaultInstance());
    }
    /**
     * <pre>
     * Timeseries messages can either specify samples or (native) histogram samples
     * (histogram field), but not both. For a typical sender (real-time metric
     * streaming), in healthy cases, there will be only one sample or histogram.
     *
     * Samples and histograms are sorted by timestamp (older first).
     * </pre>
     *
     * <code>repeated .io.prometheus.write.v2.Sample samples = 2;</code>
     */
    public java.util.List<cn.ecosync.aiot.data.apiserver.api.prometheus.Sample.Builder> 
         getSamplesBuilderList() {
      return internalGetSamplesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        cn.ecosync.aiot.data.apiserver.api.prometheus.Sample, cn.ecosync.aiot.data.apiserver.api.prometheus.Sample.Builder, cn.ecosync.aiot.data.apiserver.api.prometheus.SampleOrBuilder> 
        internalGetSamplesFieldBuilder() {
      if (samplesBuilder_ == null) {
        samplesBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            cn.ecosync.aiot.data.apiserver.api.prometheus.Sample, cn.ecosync.aiot.data.apiserver.api.prometheus.Sample.Builder, cn.ecosync.aiot.data.apiserver.api.prometheus.SampleOrBuilder>(
                samples_,
                ((bitField0_ & 0x00000002) != 0),
                getParentForChildren(),
                isClean());
        samples_ = null;
      }
      return samplesBuilder_;
    }

    private java.util.List<cn.ecosync.aiot.data.apiserver.api.prometheus.Histogram> histograms_ =
      java.util.Collections.emptyList();
    private void ensureHistogramsIsMutable() {
      if (!((bitField0_ & 0x00000004) != 0)) {
        histograms_ = new java.util.ArrayList<cn.ecosync.aiot.data.apiserver.api.prometheus.Histogram>(histograms_);
        bitField0_ |= 0x00000004;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        cn.ecosync.aiot.data.apiserver.api.prometheus.Histogram, cn.ecosync.aiot.data.apiserver.api.prometheus.Histogram.Builder, cn.ecosync.aiot.data.apiserver.api.prometheus.HistogramOrBuilder> histogramsBuilder_;

    /**
     * <code>repeated .io.prometheus.write.v2.Histogram histograms = 3;</code>
     */
    public java.util.List<cn.ecosync.aiot.data.apiserver.api.prometheus.Histogram> getHistogramsList() {
      if (histogramsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(histograms_);
      } else {
        return histogramsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .io.prometheus.write.v2.Histogram histograms = 3;</code>
     */
    public int getHistogramsCount() {
      if (histogramsBuilder_ == null) {
        return histograms_.size();
      } else {
        return histogramsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .io.prometheus.write.v2.Histogram histograms = 3;</code>
     */
    public cn.ecosync.aiot.data.apiserver.api.prometheus.Histogram getHistograms(int index) {
      if (histogramsBuilder_ == null) {
        return histograms_.get(index);
      } else {
        return histogramsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .io.prometheus.write.v2.Histogram histograms = 3;</code>
     */
    public Builder setHistograms(
        int index, cn.ecosync.aiot.data.apiserver.api.prometheus.Histogram value) {
      if (histogramsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureHistogramsIsMutable();
        histograms_.set(index, value);
        onChanged();
      } else {
        histogramsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .io.prometheus.write.v2.Histogram histograms = 3;</code>
     */
    public Builder setHistograms(
        int index, cn.ecosync.aiot.data.apiserver.api.prometheus.Histogram.Builder builderForValue) {
      if (histogramsBuilder_ == null) {
        ensureHistogramsIsMutable();
        histograms_.set(index, builderForValue.build());
        onChanged();
      } else {
        histogramsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .io.prometheus.write.v2.Histogram histograms = 3;</code>
     */
    public Builder addHistograms(cn.ecosync.aiot.data.apiserver.api.prometheus.Histogram value) {
      if (histogramsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureHistogramsIsMutable();
        histograms_.add(value);
        onChanged();
      } else {
        histogramsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .io.prometheus.write.v2.Histogram histograms = 3;</code>
     */
    public Builder addHistograms(
        int index, cn.ecosync.aiot.data.apiserver.api.prometheus.Histogram value) {
      if (histogramsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureHistogramsIsMutable();
        histograms_.add(index, value);
        onChanged();
      } else {
        histogramsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .io.prometheus.write.v2.Histogram histograms = 3;</code>
     */
    public Builder addHistograms(
        cn.ecosync.aiot.data.apiserver.api.prometheus.Histogram.Builder builderForValue) {
      if (histogramsBuilder_ == null) {
        ensureHistogramsIsMutable();
        histograms_.add(builderForValue.build());
        onChanged();
      } else {
        histogramsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .io.prometheus.write.v2.Histogram histograms = 3;</code>
     */
    public Builder addHistograms(
        int index, cn.ecosync.aiot.data.apiserver.api.prometheus.Histogram.Builder builderForValue) {
      if (histogramsBuilder_ == null) {
        ensureHistogramsIsMutable();
        histograms_.add(index, builderForValue.build());
        onChanged();
      } else {
        histogramsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .io.prometheus.write.v2.Histogram histograms = 3;</code>
     */
    public Builder addAllHistograms(
        java.lang.Iterable<? extends cn.ecosync.aiot.data.apiserver.api.prometheus.Histogram> values) {
      if (histogramsBuilder_ == null) {
        ensureHistogramsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, histograms_);
        onChanged();
      } else {
        histogramsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .io.prometheus.write.v2.Histogram histograms = 3;</code>
     */
    public Builder clearHistograms() {
      if (histogramsBuilder_ == null) {
        histograms_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
      } else {
        histogramsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .io.prometheus.write.v2.Histogram histograms = 3;</code>
     */
    public Builder removeHistograms(int index) {
      if (histogramsBuilder_ == null) {
        ensureHistogramsIsMutable();
        histograms_.remove(index);
        onChanged();
      } else {
        histogramsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .io.prometheus.write.v2.Histogram histograms = 3;</code>
     */
    public cn.ecosync.aiot.data.apiserver.api.prometheus.Histogram.Builder getHistogramsBuilder(
        int index) {
      return internalGetHistogramsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .io.prometheus.write.v2.Histogram histograms = 3;</code>
     */
    public cn.ecosync.aiot.data.apiserver.api.prometheus.HistogramOrBuilder getHistogramsOrBuilder(
        int index) {
      if (histogramsBuilder_ == null) {
        return histograms_.get(index);  } else {
        return histogramsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .io.prometheus.write.v2.Histogram histograms = 3;</code>
     */
    public java.util.List<? extends cn.ecosync.aiot.data.apiserver.api.prometheus.HistogramOrBuilder> 
         getHistogramsOrBuilderList() {
      if (histogramsBuilder_ != null) {
        return histogramsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(histograms_);
      }
    }
    /**
     * <code>repeated .io.prometheus.write.v2.Histogram histograms = 3;</code>
     */
    public cn.ecosync.aiot.data.apiserver.api.prometheus.Histogram.Builder addHistogramsBuilder() {
      return internalGetHistogramsFieldBuilder().addBuilder(
          cn.ecosync.aiot.data.apiserver.api.prometheus.Histogram.getDefaultInstance());
    }
    /**
     * <code>repeated .io.prometheus.write.v2.Histogram histograms = 3;</code>
     */
    public cn.ecosync.aiot.data.apiserver.api.prometheus.Histogram.Builder addHistogramsBuilder(
        int index) {
      return internalGetHistogramsFieldBuilder().addBuilder(
          index, cn.ecosync.aiot.data.apiserver.api.prometheus.Histogram.getDefaultInstance());
    }
    /**
     * <code>repeated .io.prometheus.write.v2.Histogram histograms = 3;</code>
     */
    public java.util.List<cn.ecosync.aiot.data.apiserver.api.prometheus.Histogram.Builder> 
         getHistogramsBuilderList() {
      return internalGetHistogramsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        cn.ecosync.aiot.data.apiserver.api.prometheus.Histogram, cn.ecosync.aiot.data.apiserver.api.prometheus.Histogram.Builder, cn.ecosync.aiot.data.apiserver.api.prometheus.HistogramOrBuilder> 
        internalGetHistogramsFieldBuilder() {
      if (histogramsBuilder_ == null) {
        histogramsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            cn.ecosync.aiot.data.apiserver.api.prometheus.Histogram, cn.ecosync.aiot.data.apiserver.api.prometheus.Histogram.Builder, cn.ecosync.aiot.data.apiserver.api.prometheus.HistogramOrBuilder>(
                histograms_,
                ((bitField0_ & 0x00000004) != 0),
                getParentForChildren(),
                isClean());
        histograms_ = null;
      }
      return histogramsBuilder_;
    }

    private java.util.List<cn.ecosync.aiot.data.apiserver.api.prometheus.Exemplar> exemplars_ =
      java.util.Collections.emptyList();
    private void ensureExemplarsIsMutable() {
      if (!((bitField0_ & 0x00000008) != 0)) {
        exemplars_ = new java.util.ArrayList<cn.ecosync.aiot.data.apiserver.api.prometheus.Exemplar>(exemplars_);
        bitField0_ |= 0x00000008;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        cn.ecosync.aiot.data.apiserver.api.prometheus.Exemplar, cn.ecosync.aiot.data.apiserver.api.prometheus.Exemplar.Builder, cn.ecosync.aiot.data.apiserver.api.prometheus.ExemplarOrBuilder> exemplarsBuilder_;

    /**
     * <pre>
     * exemplars represents an optional set of exemplars attached to this series' samples.
     * </pre>
     *
     * <code>repeated .io.prometheus.write.v2.Exemplar exemplars = 4;</code>
     */
    public java.util.List<cn.ecosync.aiot.data.apiserver.api.prometheus.Exemplar> getExemplarsList() {
      if (exemplarsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(exemplars_);
      } else {
        return exemplarsBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * exemplars represents an optional set of exemplars attached to this series' samples.
     * </pre>
     *
     * <code>repeated .io.prometheus.write.v2.Exemplar exemplars = 4;</code>
     */
    public int getExemplarsCount() {
      if (exemplarsBuilder_ == null) {
        return exemplars_.size();
      } else {
        return exemplarsBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * exemplars represents an optional set of exemplars attached to this series' samples.
     * </pre>
     *
     * <code>repeated .io.prometheus.write.v2.Exemplar exemplars = 4;</code>
     */
    public cn.ecosync.aiot.data.apiserver.api.prometheus.Exemplar getExemplars(int index) {
      if (exemplarsBuilder_ == null) {
        return exemplars_.get(index);
      } else {
        return exemplarsBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * exemplars represents an optional set of exemplars attached to this series' samples.
     * </pre>
     *
     * <code>repeated .io.prometheus.write.v2.Exemplar exemplars = 4;</code>
     */
    public Builder setExemplars(
        int index, cn.ecosync.aiot.data.apiserver.api.prometheus.Exemplar value) {
      if (exemplarsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureExemplarsIsMutable();
        exemplars_.set(index, value);
        onChanged();
      } else {
        exemplarsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * exemplars represents an optional set of exemplars attached to this series' samples.
     * </pre>
     *
     * <code>repeated .io.prometheus.write.v2.Exemplar exemplars = 4;</code>
     */
    public Builder setExemplars(
        int index, cn.ecosync.aiot.data.apiserver.api.prometheus.Exemplar.Builder builderForValue) {
      if (exemplarsBuilder_ == null) {
        ensureExemplarsIsMutable();
        exemplars_.set(index, builderForValue.build());
        onChanged();
      } else {
        exemplarsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * exemplars represents an optional set of exemplars attached to this series' samples.
     * </pre>
     *
     * <code>repeated .io.prometheus.write.v2.Exemplar exemplars = 4;</code>
     */
    public Builder addExemplars(cn.ecosync.aiot.data.apiserver.api.prometheus.Exemplar value) {
      if (exemplarsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureExemplarsIsMutable();
        exemplars_.add(value);
        onChanged();
      } else {
        exemplarsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * exemplars represents an optional set of exemplars attached to this series' samples.
     * </pre>
     *
     * <code>repeated .io.prometheus.write.v2.Exemplar exemplars = 4;</code>
     */
    public Builder addExemplars(
        int index, cn.ecosync.aiot.data.apiserver.api.prometheus.Exemplar value) {
      if (exemplarsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureExemplarsIsMutable();
        exemplars_.add(index, value);
        onChanged();
      } else {
        exemplarsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * exemplars represents an optional set of exemplars attached to this series' samples.
     * </pre>
     *
     * <code>repeated .io.prometheus.write.v2.Exemplar exemplars = 4;</code>
     */
    public Builder addExemplars(
        cn.ecosync.aiot.data.apiserver.api.prometheus.Exemplar.Builder builderForValue) {
      if (exemplarsBuilder_ == null) {
        ensureExemplarsIsMutable();
        exemplars_.add(builderForValue.build());
        onChanged();
      } else {
        exemplarsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * exemplars represents an optional set of exemplars attached to this series' samples.
     * </pre>
     *
     * <code>repeated .io.prometheus.write.v2.Exemplar exemplars = 4;</code>
     */
    public Builder addExemplars(
        int index, cn.ecosync.aiot.data.apiserver.api.prometheus.Exemplar.Builder builderForValue) {
      if (exemplarsBuilder_ == null) {
        ensureExemplarsIsMutable();
        exemplars_.add(index, builderForValue.build());
        onChanged();
      } else {
        exemplarsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * exemplars represents an optional set of exemplars attached to this series' samples.
     * </pre>
     *
     * <code>repeated .io.prometheus.write.v2.Exemplar exemplars = 4;</code>
     */
    public Builder addAllExemplars(
        java.lang.Iterable<? extends cn.ecosync.aiot.data.apiserver.api.prometheus.Exemplar> values) {
      if (exemplarsBuilder_ == null) {
        ensureExemplarsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, exemplars_);
        onChanged();
      } else {
        exemplarsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * exemplars represents an optional set of exemplars attached to this series' samples.
     * </pre>
     *
     * <code>repeated .io.prometheus.write.v2.Exemplar exemplars = 4;</code>
     */
    public Builder clearExemplars() {
      if (exemplarsBuilder_ == null) {
        exemplars_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
      } else {
        exemplarsBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * exemplars represents an optional set of exemplars attached to this series' samples.
     * </pre>
     *
     * <code>repeated .io.prometheus.write.v2.Exemplar exemplars = 4;</code>
     */
    public Builder removeExemplars(int index) {
      if (exemplarsBuilder_ == null) {
        ensureExemplarsIsMutable();
        exemplars_.remove(index);
        onChanged();
      } else {
        exemplarsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * exemplars represents an optional set of exemplars attached to this series' samples.
     * </pre>
     *
     * <code>repeated .io.prometheus.write.v2.Exemplar exemplars = 4;</code>
     */
    public cn.ecosync.aiot.data.apiserver.api.prometheus.Exemplar.Builder getExemplarsBuilder(
        int index) {
      return internalGetExemplarsFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * exemplars represents an optional set of exemplars attached to this series' samples.
     * </pre>
     *
     * <code>repeated .io.prometheus.write.v2.Exemplar exemplars = 4;</code>
     */
    public cn.ecosync.aiot.data.apiserver.api.prometheus.ExemplarOrBuilder getExemplarsOrBuilder(
        int index) {
      if (exemplarsBuilder_ == null) {
        return exemplars_.get(index);  } else {
        return exemplarsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * exemplars represents an optional set of exemplars attached to this series' samples.
     * </pre>
     *
     * <code>repeated .io.prometheus.write.v2.Exemplar exemplars = 4;</code>
     */
    public java.util.List<? extends cn.ecosync.aiot.data.apiserver.api.prometheus.ExemplarOrBuilder> 
         getExemplarsOrBuilderList() {
      if (exemplarsBuilder_ != null) {
        return exemplarsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(exemplars_);
      }
    }
    /**
     * <pre>
     * exemplars represents an optional set of exemplars attached to this series' samples.
     * </pre>
     *
     * <code>repeated .io.prometheus.write.v2.Exemplar exemplars = 4;</code>
     */
    public cn.ecosync.aiot.data.apiserver.api.prometheus.Exemplar.Builder addExemplarsBuilder() {
      return internalGetExemplarsFieldBuilder().addBuilder(
          cn.ecosync.aiot.data.apiserver.api.prometheus.Exemplar.getDefaultInstance());
    }
    /**
     * <pre>
     * exemplars represents an optional set of exemplars attached to this series' samples.
     * </pre>
     *
     * <code>repeated .io.prometheus.write.v2.Exemplar exemplars = 4;</code>
     */
    public cn.ecosync.aiot.data.apiserver.api.prometheus.Exemplar.Builder addExemplarsBuilder(
        int index) {
      return internalGetExemplarsFieldBuilder().addBuilder(
          index, cn.ecosync.aiot.data.apiserver.api.prometheus.Exemplar.getDefaultInstance());
    }
    /**
     * <pre>
     * exemplars represents an optional set of exemplars attached to this series' samples.
     * </pre>
     *
     * <code>repeated .io.prometheus.write.v2.Exemplar exemplars = 4;</code>
     */
    public java.util.List<cn.ecosync.aiot.data.apiserver.api.prometheus.Exemplar.Builder> 
         getExemplarsBuilderList() {
      return internalGetExemplarsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        cn.ecosync.aiot.data.apiserver.api.prometheus.Exemplar, cn.ecosync.aiot.data.apiserver.api.prometheus.Exemplar.Builder, cn.ecosync.aiot.data.apiserver.api.prometheus.ExemplarOrBuilder> 
        internalGetExemplarsFieldBuilder() {
      if (exemplarsBuilder_ == null) {
        exemplarsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            cn.ecosync.aiot.data.apiserver.api.prometheus.Exemplar, cn.ecosync.aiot.data.apiserver.api.prometheus.Exemplar.Builder, cn.ecosync.aiot.data.apiserver.api.prometheus.ExemplarOrBuilder>(
                exemplars_,
                ((bitField0_ & 0x00000008) != 0),
                getParentForChildren(),
                isClean());
        exemplars_ = null;
      }
      return exemplarsBuilder_;
    }

    private cn.ecosync.aiot.data.apiserver.api.prometheus.Metadata metadata_;
    private com.google.protobuf.SingleFieldBuilder<
        cn.ecosync.aiot.data.apiserver.api.prometheus.Metadata, cn.ecosync.aiot.data.apiserver.api.prometheus.Metadata.Builder, cn.ecosync.aiot.data.apiserver.api.prometheus.MetadataOrBuilder> metadataBuilder_;
    /**
     * <pre>
     * metadata represents the metadata associated with the given series' samples.
     * </pre>
     *
     * <code>.io.prometheus.write.v2.Metadata metadata = 5;</code>
     * @return Whether the metadata field is set.
     */
    public boolean hasMetadata() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <pre>
     * metadata represents the metadata associated with the given series' samples.
     * </pre>
     *
     * <code>.io.prometheus.write.v2.Metadata metadata = 5;</code>
     * @return The metadata.
     */
    public cn.ecosync.aiot.data.apiserver.api.prometheus.Metadata getMetadata() {
      if (metadataBuilder_ == null) {
        return metadata_ == null ? cn.ecosync.aiot.data.apiserver.api.prometheus.Metadata.getDefaultInstance() : metadata_;
      } else {
        return metadataBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * metadata represents the metadata associated with the given series' samples.
     * </pre>
     *
     * <code>.io.prometheus.write.v2.Metadata metadata = 5;</code>
     */
    public Builder setMetadata(cn.ecosync.aiot.data.apiserver.api.prometheus.Metadata value) {
      if (metadataBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        metadata_ = value;
      } else {
        metadataBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * metadata represents the metadata associated with the given series' samples.
     * </pre>
     *
     * <code>.io.prometheus.write.v2.Metadata metadata = 5;</code>
     */
    public Builder setMetadata(
        cn.ecosync.aiot.data.apiserver.api.prometheus.Metadata.Builder builderForValue) {
      if (metadataBuilder_ == null) {
        metadata_ = builderForValue.build();
      } else {
        metadataBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * metadata represents the metadata associated with the given series' samples.
     * </pre>
     *
     * <code>.io.prometheus.write.v2.Metadata metadata = 5;</code>
     */
    public Builder mergeMetadata(cn.ecosync.aiot.data.apiserver.api.prometheus.Metadata value) {
      if (metadataBuilder_ == null) {
        if (((bitField0_ & 0x00000010) != 0) &&
          metadata_ != null &&
          metadata_ != cn.ecosync.aiot.data.apiserver.api.prometheus.Metadata.getDefaultInstance()) {
          getMetadataBuilder().mergeFrom(value);
        } else {
          metadata_ = value;
        }
      } else {
        metadataBuilder_.mergeFrom(value);
      }
      if (metadata_ != null) {
        bitField0_ |= 0x00000010;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * metadata represents the metadata associated with the given series' samples.
     * </pre>
     *
     * <code>.io.prometheus.write.v2.Metadata metadata = 5;</code>
     */
    public Builder clearMetadata() {
      bitField0_ = (bitField0_ & ~0x00000010);
      metadata_ = null;
      if (metadataBuilder_ != null) {
        metadataBuilder_.dispose();
        metadataBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * metadata represents the metadata associated with the given series' samples.
     * </pre>
     *
     * <code>.io.prometheus.write.v2.Metadata metadata = 5;</code>
     */
    public cn.ecosync.aiot.data.apiserver.api.prometheus.Metadata.Builder getMetadataBuilder() {
      bitField0_ |= 0x00000010;
      onChanged();
      return internalGetMetadataFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * metadata represents the metadata associated with the given series' samples.
     * </pre>
     *
     * <code>.io.prometheus.write.v2.Metadata metadata = 5;</code>
     */
    public cn.ecosync.aiot.data.apiserver.api.prometheus.MetadataOrBuilder getMetadataOrBuilder() {
      if (metadataBuilder_ != null) {
        return metadataBuilder_.getMessageOrBuilder();
      } else {
        return metadata_ == null ?
            cn.ecosync.aiot.data.apiserver.api.prometheus.Metadata.getDefaultInstance() : metadata_;
      }
    }
    /**
     * <pre>
     * metadata represents the metadata associated with the given series' samples.
     * </pre>
     *
     * <code>.io.prometheus.write.v2.Metadata metadata = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        cn.ecosync.aiot.data.apiserver.api.prometheus.Metadata, cn.ecosync.aiot.data.apiserver.api.prometheus.Metadata.Builder, cn.ecosync.aiot.data.apiserver.api.prometheus.MetadataOrBuilder> 
        internalGetMetadataFieldBuilder() {
      if (metadataBuilder_ == null) {
        metadataBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            cn.ecosync.aiot.data.apiserver.api.prometheus.Metadata, cn.ecosync.aiot.data.apiserver.api.prometheus.Metadata.Builder, cn.ecosync.aiot.data.apiserver.api.prometheus.MetadataOrBuilder>(
                getMetadata(),
                getParentForChildren(),
                isClean());
        metadata_ = null;
      }
      return metadataBuilder_;
    }

    private long createdTimestamp_ ;
    /**
     * <pre>
     * created_timestamp represents an optional created timestamp associated with
     * this series' samples in ms format, typically for counter or histogram type
     * metrics. Created timestamp represents the time when the counter started
     * counting (sometimes referred to as start timestamp), which can increase
     * the accuracy of query results.
     *
     * Note that some receivers might require this and in return fail to
     * ingest such samples within the Request.
     *
     * For Go, see github.com/prometheus/prometheus/model/timestamp/timestamp.go
     * for conversion from/to time.Time to Prometheus timestamp.
     *
     * Note that the "optional" keyword is omitted due to
     * https://cloud.google.com/apis/design/design_patterns.md#optional_primitive_fields
     * Zero value means value not set. If you need to use exactly zero value for
     * the timestamp, use 1 millisecond before or after.
     * </pre>
     *
     * <code>int64 created_timestamp = 6;</code>
     * @return The createdTimestamp.
     */
    @java.lang.Override
    public long getCreatedTimestamp() {
      return createdTimestamp_;
    }
    /**
     * <pre>
     * created_timestamp represents an optional created timestamp associated with
     * this series' samples in ms format, typically for counter or histogram type
     * metrics. Created timestamp represents the time when the counter started
     * counting (sometimes referred to as start timestamp), which can increase
     * the accuracy of query results.
     *
     * Note that some receivers might require this and in return fail to
     * ingest such samples within the Request.
     *
     * For Go, see github.com/prometheus/prometheus/model/timestamp/timestamp.go
     * for conversion from/to time.Time to Prometheus timestamp.
     *
     * Note that the "optional" keyword is omitted due to
     * https://cloud.google.com/apis/design/design_patterns.md#optional_primitive_fields
     * Zero value means value not set. If you need to use exactly zero value for
     * the timestamp, use 1 millisecond before or after.
     * </pre>
     *
     * <code>int64 created_timestamp = 6;</code>
     * @param value The createdTimestamp to set.
     * @return This builder for chaining.
     */
    public Builder setCreatedTimestamp(long value) {

      createdTimestamp_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * created_timestamp represents an optional created timestamp associated with
     * this series' samples in ms format, typically for counter or histogram type
     * metrics. Created timestamp represents the time when the counter started
     * counting (sometimes referred to as start timestamp), which can increase
     * the accuracy of query results.
     *
     * Note that some receivers might require this and in return fail to
     * ingest such samples within the Request.
     *
     * For Go, see github.com/prometheus/prometheus/model/timestamp/timestamp.go
     * for conversion from/to time.Time to Prometheus timestamp.
     *
     * Note that the "optional" keyword is omitted due to
     * https://cloud.google.com/apis/design/design_patterns.md#optional_primitive_fields
     * Zero value means value not set. If you need to use exactly zero value for
     * the timestamp, use 1 millisecond before or after.
     * </pre>
     *
     * <code>int64 created_timestamp = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearCreatedTimestamp() {
      bitField0_ = (bitField0_ & ~0x00000020);
      createdTimestamp_ = 0L;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:io.prometheus.write.v2.TimeSeries)
  }

  // @@protoc_insertion_point(class_scope:io.prometheus.write.v2.TimeSeries)
  private static final cn.ecosync.aiot.data.apiserver.api.prometheus.TimeSeries DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new cn.ecosync.aiot.data.apiserver.api.prometheus.TimeSeries();
  }

  public static cn.ecosync.aiot.data.apiserver.api.prometheus.TimeSeries getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<TimeSeries>
      PARSER = new com.google.protobuf.AbstractParser<TimeSeries>() {
    @java.lang.Override
    public TimeSeries parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<TimeSeries> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<TimeSeries> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public cn.ecosync.aiot.data.apiserver.api.prometheus.TimeSeries getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

