CREATE DATABASE ibms;
-- debezium
-- CREATE USER 'debezium'@'%' IDENTIFIED BY 'debezium';
-- GRANT SELECT, RELOAD, SHOW DATABASES, REPLICATION SLAVE, REPLICATION CLIENT ON ibms.* TO 'debezium'@'%';
-- iceberg
-- CREATE DATABASE ICEBERG;
-- CREATE USER 'iceberg'@'%' IDENTIFIED BY 'iceberg';
-- REVOKE ALL PRIVILEGES, GRANT OPTION FROM 'iceberg'@'%';
-- GRANT ALL PRIVILEGES ON ICEBERG.* TO 'iceberg'@'%';
FLUSH PRIVILEGES;