{
 "title": "JVM dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "gateway",
    "label": "网关",
    "query": {
     "query": "label_values(jvm_runtime_info,gateway_code)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "运行时长",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{gateway_code=\"$gateway\", job=\"jvm\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "JVM",
   "type": "stat",
   "gridPos": { "h": 4, "w": 10, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_join(jvm_runtime_info{gateway_code=\"qie\", job=\"jvm\"}, \"jvm\", \"\\n\", \"vendor\", \"runtime\", \"version\")",
     "legendFormat": "{{jvm}}"
    }
   ]
  },
  {
   "title": "死锁线程数",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jvm_threads_deadlocked{gateway_code=\"$gateway\"} + jvm_threads_deadlocked_monitor{gateway_code=\"$gateway\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "堆内存使用率",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{gateway_code=\"qie\", area=\"heap\"} / jvm_memory_max_bytes{gateway_code=\"qie\", area=\"heap\"} * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "打开的文件描述符",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_open_fds{gateway_code=\"$gateway\", job=\"jvm\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "内存使用概览",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{gateway_code=\"$gateway\"}",
     "legendFormat": "{{area}}"
    }
   ]
  },
  {
   "title": "内存池使用概览",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 9, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jvm_memory_pool_used_bytes{gateway_code=\"$gateway\"}",
     "legendFormat": "{{pool}}"
    }
   ]
  },
  {
   "title": "内存使用概览",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{gateway_code=\"$gateway\", area=\"heap\"}",
     "legendFormat": "堆内存"
    },
    {
     "expr": "jvm_memory_used_bytes{gateway_code=\"$gateway\", area=\"nonheap\"}",
     "legendFormat": "非堆内存"
    }
   ]
  },
  {
   "title": "内存池使用情况",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_pool_used_bytes{gateway_code=\"$gateway\"}",
     "legendFormat": "{{pool}}"
    }
   ]
  },
  {
   "title": "线程数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "jvm_threads_current{gateway_code=\"$gateway\"}",
     "legendFormat": "当前线程"
    },
    {
     "expr": "jvm_threads_daemon{gateway_code=\"$gateway\"}",
     "legendFormat": "守护线程"
    },
    {
     "expr": "jvm_threads_deadlocked{gateway_code=\"$gateway\"} + jvm_threads_deadlocked_monitor{gateway_code=\"$gateway\"}",
     "legendFormat": "死锁线程"
    }
   ]
  }
 ]
}