server:
  servlet:
    context-path: /ibms
  forward-headers-strategy: framework

---
spring:
  profiles:
    active: @spring.profiles.active@
  application:
    name: gateway
  data:
    jpa:
      repositories:
        enabled: true
  jpa:
    open-in-view: false
    show-sql: true
  quartz:
    job-store-type: jdbc
    auto-startup: true
    wait-for-jobs-to-complete-on-shutdown: false
    overwrite-existing-jobs: true
    jdbc:
      initialize-schema: never

---
spring:
  kafka:
    bootstrap-servers: kafka:19092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        enable.idempotence: true
    consumer:
      group-id: ${spring.application.name}
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    listener:
      ack-mode: manual
    streams:
      application-id: ${spring.application.name}-streams
      bootstrap-servers: ${spring.kafka.bootstrap-servers}
      cleanup:
        on-startup: true
        on-shutdown: true
      state-dir: rocksdb
      properties:
        default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
        default.value.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
        num.stream.threads: 1
        default.dsl.store: rocksDB
      auto-startup: true

---
spring:
  flyway:
    enabled: true
    create-schemas: false
    locations: classpath:db/migration/{vendor}
    encoding: UTF-8
    sql-migration-prefix: V
    sql-migration-separator: __
    sql-migration-suffixes: .sql
    validate-on-migrate: true

logging:
  level:
    org.springframework.jdbc.core.JdbcTemplate: debug
  pattern:
    console: "%clr(%d{${LOG_DATEFORMAT_PATTERN:yyyy-MM-dd'T'HH:mm:ss.SSSXXX}}){faint} %clr(${LOG_LEVEL_PATTERN:%5p}){} %clr(${PID:}){magenta} %clr(--- %esb(){APPLICATION_NAME}%esb{APPLICATION_GROUP}[%15.15t] ${LOG_CORRELATION_PATTERN:}){faint}%clr(%-40.40logger{39}){cyan} %clr(:){faint} %esb(%mdc){}%m%esb(%kvp){}%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"
#    console: "%clr(%d{${LOG_DATEFORMAT_PATTERN:yyyy-MM-dd'T'HH:mm:ss.SSSXXX}}){faint} %clr(${LOG_LEVEL_PATTERN:%5p}){} %clr(${PID:}){magenta} %clr(--- %esb(){APPLICATION_NAME}%esb{APPLICATION_GROUP}[%15.15t] ${LOG_CORRELATION_PATTERN:}){faint}%clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"
