spring:
  datasource:
    url: jdbc:mysql://rm-wz90yr2u19dkvvh779o.mysql.rds.aliyuncs.com:3306/ibms?serverTimezone=Asia/Shanghai
    username: metaiot
    password: cx553YzCSgPKnmX
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
logging:
  level:
    org.springframework.jdbc.core.JdbcTemplate: debug
