spring:
  datasource:
    url: jdbc:mysql://0.0.0.0:3306/ibms?serverTimezone=Asia/Shanghai
    username: root
    password: CJVixCszaS+7raa/5326YJDq3xrSBXHg
    driver-class-name: com.mysql.cj.jdbc.Driver
