services:
  nginx:
    image: nginx:1.27-bookworm
    restart: always
#    extra_hosts:
#      - "host.docker.internal:host-gateway"
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./templates:/etc/nginx/templates
      - /tmp/nginx:/var/log/nginx
