#scrape_configs:
#  - job_name: 'otel-collector'
#    scrape_interval: 5s
#    static_configs:
#      - targets: [ 'otel-collector:8889' ]
#
#storage:
#  tsdb:
#    out_of_order_time_window: 30m
#
#otlp:
#  promote_resource_attributes:
#    - service.instance.id
#    - service.name
#    - service.namespace