volumes:
  prometheus-gateway:

services:
  gateway:
    build: .
    image: ecosync/ibms-gateway:0.0.3
    network_mode: host
    depends_on:
      database:
        condition: service_healthy
    volumes:
      - ./target/ibms-gateway-starter-0.0.1-SNAPSHOT.jar:/opt/app/ibms-gateway-starter-0.0.1-SNAPSHOT.jar
      - ./scrape_config_file.yml:/opt/app/scrape_config_file.yml
    command: [ "java", "-jar", "ibms-gateway-starter-0.0.1-SNAPSHOT.jar" ]
    environment:
      BACNET_IFACE: ens18
      IBMS_HOST: ${IBMS_HOST:?}
  # push
  prometheus-agent:
    image: prom/prometheus:v3.2.0
    network_mode: host
    environment:
      IBMS_GATEWAY_CODE: ${IBMS_GATEWAY_CODE}
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./scrape_config_file.yml:/etc/prometheus/scrape_config_file.yml
      - prometheus-gateway:/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --config.auto-reload-interval=30s
      - --storage.agent.path=/prometheus
      - --enable-feature=auto-reload-config,metadata-wal-records
      - --agent
      - --web.listen-address=0.0.0.0:9091
  # pull
#  prometheus:
#    image: prom/prometheus:v3.2.0
#    network_mode: host
#    environment:
#      IBMS_GATEWAY_CODE: ${IBMS_GATEWAY_CODE}
#    volumes:
#      - ./prometheus.yml:/etc/prometheus/prometheus.yml
#      - ./scrape_config_file.yml:/etc/prometheus/scrape_config_file.yml
#      - prometheus-gateway:/prometheus
#    command:
#      - --config.file=/etc/prometheus/prometheus.yml
#      - --config.auto-reload-interval=30s
#      - --storage.tsdb.path=/prometheus
#      - --enable-feature=auto-reload-config
