services:
  gateway:
    build: .
    image: ecosync/ibms-gateway:0.0.3
    network_mode: host
    depends_on:
      database:
        condition: service_healthy
    volumes:
      - ./target/ibms-gateway-starter-0.0.1-SNAPSHOT.jar:/opt/app/ibms-gateway-starter-0.0.1-SNAPSHOT.jar
      - ../ibms-prometheus/scrape_config_file.yml:/opt/app/scrape_config_file.yml
    command: [ "java", "-jar", "ibms-gateway-starter-0.0.1-SNAPSHOT.jar" ]
    environment:
      BACNET_IFACE: ens18
      IBMS_HOST: ${IBMS_HOST:?}
      IBMS_GATEWAY_CODE: ${IBMS_GATEWAY_CODE:?}
