# Default system properties included when running spark-submit.
# This is useful for setting default environmental settings.

# Example:
# spark.sql.extensions                   org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions
spark.sql.catalog.ibms                 org.apache.iceberg.spark.SparkSessionCatalog
spark.sql.catalog.ibms.type            jdbc
spark.sql.catalog.ibms.uri             jdbc:postgresql://postgresql:5432/iceberg
spark.sql.catalog.ibms.jdbc.user       iceberg
spark.sql.catalog.ibms.jdbc.password   a123451!
spark.sql.catalog.ibms.io-impl         org.apache.iceberg.aws.s3.S3FileIO
spark.sql.catalog.ibms.warehouse       s3://ecosync-ibms
spark.sql.catalog.ibms.s3.endpoint     https://oss-cn-shenzhen.aliyuncs.com
spark.sql.defaultCatalog               ibms
