services:
  grafana:
    image: grafana/grafana:11.4.0
    network_mode: host
    environment:
      GF_DEFAULT_INSTANCE_NAME: ${COMPOSE_PROJECT_NAME}
      GF_SERVER_ROOT_URL: http://${IBMS_EXTERNAL_HOST:?}/grafana
      GF_SERVER_SERVE_FROM_SUB_PATH: true
      GF_SECURITY_ADMIN_USER: ${GRAFANA_ADMIN_USER:?}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_ADMIN_PASSWORD:?}
    volumes:
      - grafana:/var/lib/grafana
