volumes:
  prometheus:

services:
  prometheus:
    image: prom/prometheus:v3.2.0
    network_mode: host
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus:/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --web.route-prefix=/
      - --web.external-url=http://${IBMS_EXTERNAL_HOST:?}/prometheus
      - --web.enable-remote-write-receiver
      - --web.remote-write-receiver.accepted-protobuf-messages=io.prometheus.write.v2.Request
      - --web.listen-address=0.0.0.0:9090
