package cn.ecosync.ibms.bacnet.model;

import com.fasterxml.jackson.annotation.JsonValue;
import lombok.Getter;
import lombok.ToString;

@Getter
@ToString
public enum BacnetObjectType {
    OBJECT_ANALOG_INPUT(0, "ANALOG_INPUT"),
    OBJECT_ANALOG_OUTPUT(1, "ANALOG_OUTPUT"),
    OBJECT_ANALOG_VALUE(2, "ANALOG_VALUE"),
    OBJECT_BINARY_INPUT(3, "BINARY_INPUT"),
    OBJECT_BINARY_OUTPUT(4, "BINARY_OUTPUT"),
    OBJECT_BINARY_VALUE(5, "BINARY_VALUE"),
    OBJECT_CALENDAR(6, "CALENDAR"),
    OBJECT_COMMAND(7, "COMMAND"),
    OBJECT_DEVICE(8, "DEVICE"),
    OBJECT_EVENT_ENROLLMENT(9, "EVENT_ENROLLMENT"),
    OBJECT_FILE(10, "FILE"),
    OBJECT_GROUP(11, "GROUP"),
    OBJECT_LOOP(12, "LOOP"),
    OBJECT_MULTI_STATE_INPUT(13, "MULTI_STATE_INPUT"),
    OBJECT_MULTI_STATE_OUTPUT(14, "MULTI_STATE_OUTPUT"),
    OBJECT_NOTIFICATION_CLASS(15, "NOTIFICATION_CLASS"),
    OBJECT_PROGRAM(16, "PROGRAM"),
    OBJECT_SCHEDULE(17, "SCHEDULE"),
    OBJECT_AVERAGING(18, "AVERAGING"),
    OBJECT_MULTI_STATE_VALUE(19, "MULTI_STATE_VALUE"),
    OBJECT_TRENDLOG(20, "TRENDLOG"),
    OBJECT_LIFE_SAFETY_POINT(21, "LIFE_SAFETY_POINT"),
    OBJECT_LIFE_SAFETY_ZONE(22, "LIFE_SAFETY_ZONE"),
    OBJECT_ACCUMULATOR(23, "ACCUMULATOR"),
    OBJECT_PULSE_CONVERTER(24, "PULSE_CONVERTER"),
    OBJECT_EVENT_LOG(25, "EVENT_LOG"),
    OBJECT_GLOBAL_GROUP(26, "GLOBAL_GROUP"),
    OBJECT_TREND_LOG_MULTIPLE(27, "TREND_LOG_MULTIPLE"),
    OBJECT_LOAD_CONTROL(28, "LOAD_CONTROL"),
    OBJECT_STRUCTURED_VIEW(29, "STRUCTURED_VIEW"),
    OBJECT_ACCESS_DOOR(30, "ACCESS_DOOR"),
    OBJECT_TIMER(31, "TIMER"),/* Note: 31 was lighting output, but BACnet editor changed it... */
    OBJECT_ACCESS_CREDENTIAL(32, "ACCESS_CREDENTIAL"), /* Addendum 2008-j */
    OBJECT_ACCESS_POINT(33, "ACCESS_POINT"),
    OBJECT_ACCESS_RIGHTS(34, "ACCESS_RIGHTS"),
    OBJECT_ACCESS_USER(35, "ACCESS_USER"),
    OBJECT_ACCESS_ZONE(36, "ACCESS_ZONE"),
    OBJECT_CREDENTIAL_DATA_INPUT(37, "CREDENTIAL_DATA_INPUT"), /* authentication-factor-input */
    OBJECT_NETWORK_SECURITY(38, "NETWORK_SECURITY"), /* Addendum 2008-g */
    OBJECT_BITSTRING_VALUE(39, "BITSTRING_VALUE"), /* Addendum 2008-w */
    OBJECT_CHARACTERSTRING_VALUE(40, "CHARACTERSTRING_VALUE"), /* Addendum 2008-w */
    OBJECT_DATE_PATTERN_VALUE(41, "DATE_PATTERN_VALUE"), /* Addendum 2008-w */
    OBJECT_DATE_VALUE(42, "DATE_VALUE"), /* Addendum 2008-w */
    OBJECT_DATETIME_PATTERN_VALUE(43, "DATETIME_PATTERN_VALUE"), /* Addendum 2008-w */
    OBJECT_DATETIME_VALUE(44, "DATETIME_VALUE"), /* Addendum 2008-w */
    OBJECT_INTEGER_VALUE(45, "INTEGER_VALUE"), /* Addendum 2008-w */
    OBJECT_LARGE_ANALOG_VALUE(46, "LARGE_ANALOG_VALUE"), /* Addendum 2008-w */
    OBJECT_OCTETSTRING_VALUE(47, "OCTETSTRING_VALUE"), /* Addendum 2008-w */
    OBJECT_POSITIVE_INTEGER_VALUE(48, "POSITIVE_INTEGER_VALUE"), /* Addendum 2008-w */
    OBJECT_TIME_PATTERN_VALUE(49, "TIME_PATTERN_VALUE"), /* Addendum 2008-w */
    OBJECT_TIME_VALUE(50, "TIME_VALUE"), /* Addendum 2008-w */
    OBJECT_NOTIFICATION_FORWARDER(51, "NOTIFICATION_FORWARDER"), /* Addendum 2010-af */
    OBJECT_ALERT_ENROLLMENT(52, "ALERT_ENROLLMENT"), /* Addendum 2010-af */
    OBJECT_CHANNEL(53, "CHANNEL"), /* Addendum 2010-aa */
    OBJECT_LIGHTING_OUTPUT(54, "LIGHTING_OUTPUT"), /* Addendum 2010-i */
    OBJECT_BINARY_LIGHTING_OUTPUT(55, "BINARY_LIGHTING_OUTPUT"), /* Addendum 135-2012az */
    OBJECT_NETWORK_PORT(56, "NETWORK_PORT"), /* Addendum 135-2012az */
    OBJECT_ELEVATOR_GROUP(57, "ELEVATOR_GROUP"), /* Addendum 135-2012aq */
    OBJECT_ESCALATOR(58, "ESCALATOR"), /* Addendum 135-2012aq */
    OBJECT_LIFT(59, "LIFT"), /* Addendum 135-2012aq */
    OBJECT_STAGING(60, "STAGING"), /* Addendum 135-2016bd */
    OBJECT_AUDIT_LOG(61, "AUDIT_LOG"), /* Addendum 135-2016bi */
    OBJECT_AUDIT_REPORTER(62, "AUDIT_REPORTER"), /* Addendum 135-2016bi */
    OBJECT_COLOR(63, "COLOR"), /* Addendum 135-2020ca */
    OBJECT_COLOR_TEMPERATURE(64, "COLOR_TEMPERATURE"), /* Addendum 135-2020ca */;

    @JsonValue
    private final int code;
    private final String name;

    BacnetObjectType(int code, String name) {
        this.code = code;
        this.name = name;
    }
}
